{
  "hash": "2e1cdffe2d0990dab892a3fa8b061765",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"G-Computation: Intuition and Math\"\n---\n\n## Overview\n\nWelcome to Week 7. In our previous sessions, we explored how to control for confounding using methods that operate on the probability of treatment, namely Inverse Probability (IP) Weighting. This week, we turn to a powerful and conceptually distinct alternative: **G-Computation**.\n\nAlso known as the g-formula, standardization, or the substitution estimator, g-computation is one of the oldest and most intuitive methods for confounding adjustment. At its core, g-computation works by building a model of the world—specifically, a model of how the outcome depends on the treatment and confounders. It then uses this model to simulate a perfect randomized trial. We will ask our model: \"What would the average outcome have been in our entire population if everyone had received the treatment?\" and \"What would it have been if, instead, no one had received the treatment?\"\n\nThe difference between the answers to these two questions is our estimate of the average causal effect. This approach is powerful because it directly estimates the quantities of interest from the potential outcomes framework, $\\E{Y^{a=1}}$ and $\\E{Y^{a=0}}$. However, its validity rests heavily on a critical, untestable assumption: that our model of the world is correctly specified. We will dedicate significant time to understanding this trade-off and its practical implications for our research.\n\n## Learning Objectives\n\nBy the end of this week's module and lab, you will be able to:\n\n1.  **Describe** the three-step g-computation algorithm (model, predict, average) and explain how it simulates a target trial to control for confounding.\n2.  **State** and **interpret** the three key identification assumptions required for g-computation: conditional exchangeability, positivity, and consistency.\n3.  **Derive** the g-formula (standardization formula) and connect each of its mathematical terms to the practical steps of the g-computation algorithm.\n4.  **Implement** parametric g-computation in R by fitting an outcome model, generating counterfactual predictions, and averaging to estimate the Average Treatment Effect (ATE).\n5.  **Critically assess** the primary limitation of parametric g-computation—its reliance on correct model specification—and discuss its implications for causal inference.\n\n## R Packages\n\nThis week, we'll focus on outcome modeling and prediction. The `boot` package will be essential for calculating confidence intervals for our g-computation estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) {\n  install.packages(\"pacman\")\n}\npacman::p_load(\n  tidyverse, # For data manipulation and visualization\n  ggdag, # For plotting DAGs\n  broom, # For tidying model outputs\n  knitr, # For table formatting\n  boot # For bootstrapping confidence intervals\n)\n\n# A consistent plot theme\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\n## 1. Comprehensive Topic Explanation\n\n### The Logic of G-Computation (Standardization)\n\nG-computation tackles confounding from the opposite direction of IP weighting. While weighting methods create a pseudo-population by modeling the *treatment assignment process* (`A ~ L`), g-computation works by modeling the *outcome generating process* (`Y ~ A + L`).\n\nThe method is best understood as a three-step algorithm that directly operationalizes the concept of standardization, a classic technique in epidemiology.\n\n**The Algorithm:**\n\n1.  **Fit an Outcome Model:** First, using your observational data, fit a regression model for the outcome $Y$ as a function of the treatment $A$ and the full set of confounders $L$. This model, often called the \"Q-model,\" learns the conditional expectation of the outcome, $\\E{Y|A, L}$.\n2.  **Predict Potential Outcomes under Interventions:**\n    -   **Intervention 1 (Everyone Treated):** Create a new dataset where the treatment variable $A$ is set to 1 for *every individual* in your study. The confounder values $L$ remain at their observed, real-world levels for each person. Use the model from Step 1 to predict the outcome for every person in this hypothetical dataset. These are the predicted potential outcomes under treatment, $\\hat{Y}^{a=1}$.\n    -   **Intervention 2 (No one Treated):** Create a second new dataset where $A$ is set to 0 for everyone, again keeping their observed $L$ values. Use the model from Step 1 to predict the outcome for everyone in this second hypothetical dataset. These are the predicted potential outcomes under no treatment, $\\hat{Y}^{a=0}$.\n3.  **Average and Contrast:**\n    -   Calculate the average of all the predicted outcomes from Intervention 1. This is your estimate of the standardized mean outcome under treatment, $\\Ehat{Y^{a=1}}$.\n    -   Calculate the average of all the predicted outcomes from Intervention 2. This is your estimate of the standardized mean outcome under no treatment, $\\Ehat{Y^{a=0}}$.\n    -   The Average Treatment Effect (ATE) is the difference between these two means: $\\text{ATE} = \\Ehat{Y^{a=1}} - \\Ehat{Y^{a=0}}$.\n\nThis procedure breaks the confounding link between $L$ and $A$ not by re-weighting, but by forcing the distribution of $L$ to be identical in the two scenarios we compare (since both scenarios use the exact same population with their observed values of $L$).\n\n### The G-Formula: Mathematical Foundation\n\nThe algorithm described above is the computational implementation of the **g-formula**, or standardization formula. This formula provides the mathematical bridge from the unobservable world of potential outcomes to the observable world of data, under key assumptions.\n\nThe goal is to identify $\\E{Y^a}$. The g-formula for a discrete set of confounders $L$ is:\n\n$$\n\\E{Y^a} = \\sum_l \\E{Y | A=a, L=l} \\times P(L=l)\n$$\n\nFor continuous confounders, the sum becomes an integral:\n\n$$\n\\E{Y^a} = \\int \\E{Y | A=a, L=l} f(l) dl\n$$\n\n**Connecting the Math to the Algorithm:**\n\n-   $\\E{Y | A=a, L=l}$: This is the conditional expectation of the outcome. In parametric g-computation, this is precisely what our regression model from **Step 1** aims to estimate. The model gives us a way to get this value for any combination of $a$ and $l$.\n-   $\\sum_l ... \\times P(L=l)$: This part of the formula represents averaging over the entire population's distribution of confounders. In our algorithm, we accomplish this in **Steps 2 and 3**. By predicting the outcome for every single person in our original dataset (first under $A=1$, then under $A=0$), and then taking the mean of those predictions, we are effectively calculating the weighted average, where the weights are simply $1/N$ for each person, thus perfectly representing the empirical distribution of $L$ in our sample.\n\n### Key Assumptions for Identification\n\nFor the g-formula to hold and for g-computation to yield a valid causal estimate, three core assumptions are required:\n\n1.  **Conditional Exchangeability (Ignorability):** $Y^a \\indep A | L$. We must have measured and adjusted for a set of covariates $L$ that is sufficient to break all backdoor paths between treatment $A$ and outcome $Y$. This is the crucial \"no unmeasured confounding\" assumption.\n2.  **Positivity (Overlap):** $P(A=a|L=l) > 0$ for all $l$ with $P(L=l) \\neq 0$. For every type of person in our population (i.e., for every level of $L$), there must be a non-zero chance of being both treated and untreated. If a certain type of person is *always* treated, we can never learn from the data what would have happened to them had they not been treated.\n3.  **Consistency:** An individual's observed outcome is their potential outcome corresponding to the treatment they actually received. This links the potential outcomes framework to the observed data.\n\n::: callout-warning\n### The Achilles' Heel of G-Computation: Model Specification\n\nIn addition to the three causal assumptions, parametric g-computation carries a fourth, statistical assumption: **correct model specification**. The entire method hinges on the Q-model ($Y \\sim A+L$) being a correct representation of reality. If the true relationship between the confounders and the outcome is non-linear, but we fit a linear model, our predictions in Step 2 will be wrong, and our final ATE estimate will be biased due to **residual confounding**. This is the fundamental trade-off compared to IPW, which instead relies on a correctly specified *treatment* model.\n:::\n\n## 2. Intuitive Clarifications of Challenging Ideas\n\n### Analogy: The Plant Scientist\n\nImagine a scientist wants to know the causal effect of a new fertilizer ($A=1$) vs. a standard one ($A=0$) on crop yield ($Y$). The scientist knows that soil quality ($L$) is a major confounder: better soil both improves yield directly and might influence which plots get the new, expensive fertilizer.\n\nShe has observational data from 100 different farm plots. A naive comparison of yield from plots that got the new fertilizer vs. the old one would be biased.\n\n**The G-Computation Approach:**\n\n1.  **Model the Farm:** The scientist fits a regression model: `Yield ~ Fertilizer + Soil_Quality`. This model learns the fundamental relationship between these variables from the 100 observed plots.\n2.  **Simulate a Universe-Wide Experiment:**\n    -   **Scenario 1:** She takes her list of 100 plots, with their *actual observed soil quality*, and asks her model: \"What would the yield have been for each of these 100 plots if they had *all* received the new fertilizer ($A=1$)?\".\n    -   **Scenario 2:** She does the same, but this time asks: \"What would the yield have been for each of these 100 plots if they had *all* received the standard fertilizer ($A=0$)?\".\n3.  **Average the Results:** She calculates the average predicted yield across all 100 plots in Scenario 1 to get $\\E{Y^{a=1}}$. She does the same for Scenario 2 to get $\\E{Y^{a=0}}$. The difference is her causal effect estimate.\n\nThis works because she is comparing two hypothetical universes that are identical in every way (they have the same 100 plots with the same soil quality distribution), except for the fertilizer they received.\n\n### G-Computation vs. IP Weighting: A Comparison\n\nThese two methods are the foundational pillars of confounding adjustment. They approach the problem from opposite directions.\n\n| Feature                | **G-Computation (Standardization)**                                                  | **IP Weighting (IPTW)**                                                                                         |\n| ---------------------- | ------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------- |\n| **Core Idea**          | Outcome Modeling & Simulation                                                        | Treatment Modeling & Re-weighting                                                                               |\n| **Model Required**     | A model for the outcome: **`Y ~ A + L`** (the Q-model)                               | A model for the treatment: **`A ~ L`** (the propensity score model)                                             |\n| **Main Vulnerability** | **Outcome model misspecification.** If the Q-model is wrong, the estimate is biased. | **Positivity violations.** If propensity scores are near 0 or 1, weights become extreme and estimates unstable. |\n| **Intuition**          | \"What would the outcome look like in a standardized population?\"                     | \"What would the A-Y association look like in a pseudo-population where L no longer predicts A?\"                 |\n\n## 3. Simple, Hand-Calculation Numerical Example(s)\n\nLet's use a very simple dataset to perform g-computation by hand. We want to find the effect of a Tutoring program ($A$) on a final Exam Score ($Y$), adjusting for a binary confounder, Prior Grades ($L$).\n\n**Observed Data (8 Students):**\n\n| Student | Prior Grades (L) | Tutoring (A) | Exam Score (Y) |\n| :-----: | :--------------: | :----------: | :------------: |\n|    1    |       Good       |      1       |       95       |\n|    2    |       Good       |      1       |       90       |\n|    3    |       Good       |      0       |       88       |\n|    4    |       Good       |      0       |       85       |\n|    5    |       Weak       |      1       |       80       |\n|    6    |       Weak       |      1       |       78       |\n|    7    |       Weak       |      0       |       70       |\n|    8    |       Weak       |      0       |       68       |\n\n**Step 1: Fit an Outcome Model.** Let's fit a simple linear model to our data. Let `L_good` be an indicator variable (1 if \"Good\", 0 if \"Weak\"). Suppose our model fit is:\n\n$$\n\\widehat{Score} = 69 + 11 \\times A + 16 \\times L_{good}\n$$\n\n-   **Interpretation:** The baseline score for a weak student without tutoring is 69. Tutoring adds 11 points, and having good prior grades adds 16 points.\n\n**Step 2: Predict Potential Outcomes for the Entire Population.**\n\n**Scenario 1: Everyone gets Tutoring (**$A=1$) We use our model to predict the score for all 8 students, forcing $A=1$.\n\n| Student | Prior Grades ($L_{good}$) | Hypothetical A | Predicted Score $\\hat{Y}^{a=1}$ |\n| :-----: | :-----------------------: | :------------: | :-----------------------------: |\n|    1    |             1             |       1        |    $69 + 11(1) + 16(1) = 96$    |\n|    2    |             1             |       1        |    $69 + 11(1) + 16(1) = 96$    |\n|    3    |             1             |       1        |    $69 + 11(1) + 16(1) = 96$    |\n|    4    |             1             |       1        |    $69 + 11(1) + 16(1) = 96$    |\n|    5    |             0             |       1        |    $69 + 11(1) + 16(0) = 80$    |\n|    6    |             0             |       1        |    $69 + 11(1) + 16(0) = 80$    |\n|    7    |             0             |       1        |    $69 + 11(1) + 16(0) = 80$    |\n|    8    |             0             |       1        |    $69 + 11(1) + 16(0) = 80$    |\n\n**Scenario 2: No one gets Tutoring (**$A=0$) Now we predict for all 8 students, forcing $A=0$.\n\n| Student | Prior Grades ($L_{good}$) | Hypothetical A | Predicted Score $\\hat{Y}^{a=0}$ |\n| :-----: | :-----------------------: | :------------: | :-----------------------------: |\n|    1    |             1             |       0        |    $69 + 11(0) + 16(1) = 85$    |\n|    2    |             1             |       0        |    $69 + 11(0) + 16(1) = 85$    |\n|    3    |             1             |       0        |    $69 + 11(0) + 16(1) = 85$    |\n|    4    |             1             |       0        |    $69 + 11(0) + 16(1) = 85$    |\n|    5    |             0             |       0        |    $69 + 11(0) + 16(0) = 69$    |\n|    6    |             0             |       0        |    $69 + 11(0) + 16(0) = 69$    |\n|    7    |             0             |       0        |    $69 + 11(0) + 16(0) = 69$    |\n|    8    |             0             |       0        |    $69 + 11(0) + 16(0) = 69$    |\n\n**Step 3: Average and Contrast.**\n\n-   $\\Ehat{Y^{a=1}} = \\frac{96+96+96+96+80+80+80+80}{8} = \\frac{4 \\times 96 + 4 \\times 80}{8} = 88$\n-   $\\Ehat{Y^{a=0}} = \\frac{85+85+85+85+69+69+69+69}{8} = \\frac{4 \\times 85 + 4 \\times 69}{8} = 77$\n-   $\\text{ATE} = 88 - 77 = 11$\n\n**Conclusion:** Our g-computation estimate of the causal effect of tutoring is an 11-point increase in exam scores. This correctly matches the coefficient for `A` in our outcome model, because the model was linear and had no interactions.\n\n## 4. R Code Examples & Interpretation\n\nLet's implement the g-computation algorithm in R and, crucially, use the bootstrap method to obtain a confidence interval.\n\n### Step 1: Simulate Confounded Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 1000\n# L is a Continuous Confounder (e.g., age)\nL <- rnorm(n, mean = 50, sd = 10)\n# Treatment A Depends on L (confounding)\nprob_A <- plogis(-5 + 0.1 * L)\nA <- rbinom(n, 1, prob_A)\n# Outcome Y Depends on A and L. True ATE = -15\nY <- 100 - 15 * A + 2 * L + rnorm(n, 0, 8)\n\ndf <- tibble(Y, A, L)\n\n# Naive (biased) Analysis for Comparison\nnaive_model <- lm(Y ~ A, data = df)\ntidy(naive_model) |>\n  filter(term == \"A\") |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|term | estimate| std.error| statistic| p.value|\n|:----|--------:|---------:|---------:|-------:|\n|A    |     1.14|      1.26|       0.9|    0.37|\n\n\n:::\n:::\n\n\n**Interpretation:** The naive analysis shows an effect of 1.14 on the outcome, which is biased towards the null compared to the true effect of -15. This is because older people (higher L) are more likely to get the treatment and also tend to have higher outcomes, making the treatment look less effective than it truly is.\n\n### Step 2: Implement G-Computation with Bootstrapped Confidence Intervals\n\nThe best way to get a confidence interval for a g-computation estimate is via the bootstrap. This involves repeatedly resampling our data and running the entire algorithm on each resample to see how much the ATE estimate varies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First, Write a Function that Performs the G-computation Steps.\n# This Function Will Be Called by the boot() Function.\ncalculate_ate <- function(data, indices) {\n  # Allow Boot to Select Resampled Datasets\n  d <- data[indices, ]\n\n  # 1. Fit the Outcome Model on the Resampled Data\n  q_model <- lm(Y ~ A + L, data = d)\n\n  # 2. Create Counterfactual Datasets\n  d_a1 <- d |> mutate(A = 1) # Everyone treated\n  d_a0 <- d |> mutate(A = 0) # No one treated\n\n  # 3. Predict Potential Outcomes\n  y_hat_a1 <- predict(q_model, newdata = d_a1)\n  y_hat_a0 <- predict(q_model, newdata = d_a0)\n\n  # 4. Average and Contrast\n  mean_y1 <- mean(y_hat_a1)\n  mean_y0 <- mean(y_hat_a0)\n\n  return(mean_y1 - mean_y0)\n}\n\n# Now, Run the Bootstrap\nset.seed(123)\nbootstrap_results <- boot(\n  data = df,\n  statistic = calculate_ate,\n  R = 999 # Number of bootstrap replications\n)\n\n# View the Results\nprint(bootstrap_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nORDINARY NONPARAMETRIC BOOTSTRAP\n\n\nCall:\nboot(data = df, statistic = calculate_ate, R = 999)\n\n\nBootstrap Statistics :\n    original       bias    std. error\nt1* -15.2348 -0.009824715   0.5744005\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate a 95% Percentile Confidence Interval\nci_boot_gcomp <- boot.ci(bootstrap_results, type = \"perc\")\nci_boot_gcomp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 999 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = bootstrap_results, type = \"perc\")\n\nIntervals : \nLevel     Percentile     \n95%   (-16.40, -14.08 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\n**Interpretation:**\n\n-   **`original`**: This value (`t1*`) is the ATE calculated on our original, un-resampled dataset. It should be very close to the true effect of -15.\n-   **`bias`**: This is the difference between the average of the bootstrap estimates and the original estimate. We want this to be small.\n-   **`std. error`**: This is the standard deviation of the bootstrap estimates, which is our bootstrap standard error for the ATE.\n-   **`boot.ci` output**: This provides the 95% confidence interval. A correct interpretation would be: \"Using parametric g-computation, the estimated average causal effect of the treatment is -15.23. We are 95% confident that the true average causal effect lies between -16.4 and -14.08, based on our bootstrap. Since this interval is far from 0, we can conclude there is a statistically significant, negative causal effect.\n\n## 5. Hands-On R Lab\n\n### Lab: Estimating the Effect of a Diet Plan on Cholesterol\n\n**Purpose:** This lab will provide hands-on experience implementing the full parametric g-computation workflow, including fitting an outcome model that includes interactions and using the bootstrap to generate confidence intervals.\n\n**Lab Objectives:**\n\n1.  Fit a parametric outcome model (Q-model) to observational data.\n2.  Implement the g-computation algorithm to estimate the ATE.\n3.  Write a function to perform g-computation that is compatible with the `boot` package.\n4.  Generate and interpret bootstrapped confidence intervals for the ATE.\n\n**Scenario:** You are a health analyst examining the effect of a new, intensive diet plan ($A=1$) versus standard advice ($A=0$) on cholesterol reduction ($Y$, measured in mg/dL). You have observational data and suspect that **baseline BMI** ($L$) is a major confounder, as individuals with higher BMI might be more likely to be assigned to the intensive plan and also have different cholesterol outcomes. Furthermore, you suspect the diet plan might be *more effective* for people with higher BMI (i.e., there is effect modification).\n\n#### Task 1: Simulate Data and Examine the Naive Effect\n\n**Instructions:**\n\n1.  Generate the confounded data using the block below.\n2.  Run a naive linear model (`lm(Y ~ A, ...)`) to see the biased association.\n3.  The true ATE in this simulation is -10. How does the naive estimate compare?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn_lab <- 500\n# L = Baseline BMI (confounder)\nL <- rnorm(n_lab, 28, 4)\n# A = Assigned to Intensive Diet Plan\nprob_A <- plogis(-3 + 0.1 * L)\nA <- rbinom(n_lab, 1, prob_A)\n# Y = Cholesterol Reduction. Note the Interaction Term A*L (effect modification)\nY <- 5 - 10 * A + 0.5 * L - 0.2 * A * L + rnorm(n_lab, 0, 5)\nlab_df <- tibble(Y, A, L)\n```\n:::\n\n\n<details>\n\n<summary>Solution to Task 1</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_lab_model <- lm(Y ~ A, data = lab_df)\ntidy(naive_lab_model) |> filter(term == \"A\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"A\",\"2\":\"-13.6413\",\"3\":\"0.4737788\",\"4\":\"-28.79256\",\"5\":\"4.667386e-108\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Interpretation:** The naive estimate is around -5.5, which is severely biased towards the null compared to the true ATE of -10. This is because people with high BMI (who are more likely to get the diet plan) have smaller cholesterol reductions in this scenario, making the plan look less effective than it is.\n\n</details>\n\n#### Task 2: Fit the Outcome Model (Q-model)\n\n**Instructions:** Based on the data-generating process, we know there is an interaction between the diet plan `A` and baseline BMI `L`. Fit a linear model for the outcome `Y` that includes `A`, `L`, and their interaction term (`A * L` or `A:L`). Examine the coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO: Fit the Q-model with the Interaction Term\nq_model_lab <- lm(...)\n\n# TODO: Tidy the Model and Look at the Coefficients\ntidy(...)\n```\n:::\n\n\n<details>\n\n<summary>Solution to Task 2</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq_model_lab <- lm(Y ~ A * L, data = lab_df)\ntidy(q_model_lab)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"4.8615234\",\"3\":\"2.22742273\",\"4\":\"2.182578\",\"5\":\"2.953521e-02\"},{\"1\":\"A\",\"2\":\"-7.2557083\",\"3\":\"3.45187284\",\"4\":\"-2.101963\",\"5\":\"3.606018e-02\"},{\"1\":\"L\",\"2\":\"0.4892053\",\"3\":\"0.08088487\",\"4\":\"6.048169\",\"5\":\"2.886538e-09\"},{\"1\":\"A:L\",\"2\":\"-0.2509521\",\"3\":\"0.12063424\",\"4\":\"-2.080272\",\"5\":\"3.801334e-02\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Interpretation:** The model has successfully recovered coefficients that are close to the true parameters in our simulation (`Intercept=5`, `A=-10`, `L=0.5`, `A:L=-0.2`). This correctly specified Q-model is the foundation for our g-computation.\n\n</details>\n\n#### Task 3: Implement the G-Computation Bootstrap\n\n**Instructions:** Following the lecture example, write a function `calculate_ate_diet` that takes `data` and `indices` as input. Inside the function, you should:\n\n1.  Fit the correct Q-model (`Y ~ A * L`).\n2.  Create the two counterfactual datasets.\n3.  Predict the outcomes for both.\n4.  Return the difference in the mean predictions.\n\nThen, call the `boot()` function using your new function to get the bootstrapped results and a 95% confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO: Write the G-computation Function\ncalculate_ate_diet <- function(data, indices) {\n  d <- data[indices, ]\n\n  # Step 1: Fit Model\n  q_model <- lm(...)\n\n  # Step 2: Create Counterfactual Data\n  d_a1 <- ...\n  d_a0 <- ...\n\n  # Step 3: Predict\n  y1_hat <- ...\n  y0_hat <- ...\n\n  # Step 4: Average and Contrast\n  ...\n  return(...)\n}\n\n# TODO: Call boot() with Your Function\nboot_results_lab <- boot(...)\n\n# TODO: Print the Results and the Confidence Interval\nprint(...)\nboot.ci(...)\n```\n:::\n\n\n<details>\n\n<summary>Solution to Task 3</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_ate_diet <- function(data, indices) {\n  d <- data[indices, ]\n\n  # Step 1: Fit Model\n  q_model <- lm(Y ~ A * L, data = d)\n\n  # Step 2: Create Counterfactual Data\n  d_a1 <- d |> mutate(A = 1)\n  d_a0 <- d |> mutate(A = 0)\n\n  # Step 3: Predict\n  y1_hat <- predict(q_model, newdata = d_a1)\n  y0_hat <- predict(q_model, newdata = d_a0)\n\n  # Step 4: Average and Contrast\n  mean_y1 <- mean(y1_hat)\n  mean_y0 <- mean(y0_hat)\n\n  return(mean_y1 - mean_y0)\n}\n\nset.seed(321)\nboot_results_lab <- boot(\n  data = lab_df,\n  statistic = calculate_ate_diet,\n  R = 999\n)\n\nprint(boot_results_lab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nORDINARY NONPARAMETRIC BOOTSTRAP\n\n\nCall:\nboot(data = lab_df, statistic = calculate_ate_diet, R = 999)\n\n\nBootstrap Statistics :\n     original      bias    std. error\nt1* -14.31709 -0.00969678   0.4702048\n```\n\n\n:::\n\n```{.r .cell-code}\nboot.ci(boot_results_lab, type = \"perc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS\nBased on 999 bootstrap replicates\n\nCALL : \nboot.ci(boot.out = boot_results_lab, type = \"perc\")\n\nIntervals : \nLevel     Percentile     \n95%   (-15.23, -13.40 )  \nCalculations and Intervals on Original Scale\n```\n\n\n:::\n:::\n\n\n</details>\n\n#### **Task 4: Final Reflection and Interpretation**\n\n1.  **Interpretation:** Look at the `original` estimate from your bootstrap output. How close is it to the true ATE of -10? Write a one-sentence conclusion for a collaborator, reporting your point estimate and 95% confidence interval.\n2.  **Conceptual:** Why did we have to include an interaction term (`A*L`) in our Q-model for this lab, but not in the main lecture example? What would have happened to our ATE estimate if we had forgotten it?\n3.  **Retrieval Quiz:**\n    -   What are the three main steps of the g-computation algorithm?\n    -   What is the name of the key untestable assumption that states we have measured all common causes of the treatment and outcome?\n    -   G-computation is to the **outcome model** as IP Weighting is to the **__________ model**.\n\n## 6. Common Pitfalls & Checks\n\n::: callout-warning\n### The Peril of Model Misspecification\n\nThe single greatest risk in parametric g-computation is that your outcome model is wrong. If you omit important confounders, forget to model non-linearities (e.g., using `L + I(L^2)`), or miss key interaction terms, your Q-model will be misspecified. This means your predictions of potential outcomes will be biased, and this bias will be directly inherited by your final ATE estimate. Always conduct standard model diagnostics on your Q-model and consider flexible approaches like splines or machine learning models if you suspect complex relationships.\n:::\n\n::: callout-tip\n### G-Computation Handles Effect Modification Naturally\n\nA major strength of g-computation is that it correctly estimates the *average* causal effect even when the true effect differs across subgroups (effect modification). By including interaction terms (e.g., `A*L`) in your Q-model, you allow the effect of `A` to vary by `L`. The algorithm's final step—averaging over the entire population's distribution of `L`—automatically computes the correct population-averaged ATE.\n:::\n\n## 7. Advanced Teaching Activities & Interactivity\n\n1.  **Live Coding: The Cost of Misspecification.**\n\n    -   **Activity:** Using the lab data, I will deliberately fit the wrong Q-model: `lm(Y ~ A + L, data = lab_df)`, leaving out the crucial interaction term. We will run the bootstrap and compare the ATE and its confidence interval to the correct result.\n    -   **Goal:** This provides a live demonstration of how sensitive g-computation is to model misspecification and makes the abstract concept of \"bias\" tangible.\n\n2.  **Think-Pair-Share: Causal Assumptions vs. Statistical Assumptions.**\n\n    -   **Think:** \"We've discussed four assumptions for parametric g-computation: exchangeability, positivity, consistency, and correct model specification. Which of these are *causal* assumptions about the world, and which are *statistical* assumptions about our methods? Which are testable with the data?\"\n    -   **Pair:** Discuss with a neighbor.\n    -   **Share:** We will classify the assumptions. Exchangeability is causal and untestable. Positivity is causal and testable. Consistency is causal/definitional. Correct model specification is statistical and partially testable with model diagnostics.\n\n## 8. Appendix: Advanced Theory & Derivations\n\n### Derivation of the G-Formula (Standardization Formula)\n\nThe g-formula allows us to express the unobservable potential outcome mean, $E[Y^a]$, in terms of observable quantities. The derivation for a discrete confounder $L$ is as follows:\n\n$$\n\\begin{aligned}\n\\E{Y^a} & = \\sum_l \\E{Y^a | L=l} P(L=l) && \\text{(1. By the Law of Total Expectation)} \\\\\n& = \\sum_l \\E{Y^a | A=a, L=l} P(L=l) && \\text{(2. Using Conditional Exchangeability)} \\\\\n& = \\sum_l \\E{Y | A=a, L=l} P(L=l) && \\text{(3. Using Consistency)}\n\\end{aligned}\n$$\n\nLet's break this down:\n\n1.  **Step 1:** This is a fundamental rule of probability. We can express the overall average of $Y^a$ as a weighted average of the stratum-specific means of $Y^a$, where the weights are the probability of being in each stratum $l$.\n2.  **Step 2:** This is the critical step where we invoke our main causal assumption. Because we assume potential outcomes $Y^a$ are independent of the actual treatment received $A$ *within levels of L*, conditioning on $A=a$ provides no new information about the expected value of $Y^a$. So, $\\E{Y^a | L=l}$ is the same as $\\E{Y^a | A=a, L=l}$.\n3.  **Step 3:** By the consistency assumption, for the group of people who actually received treatment $a$ (i.e., where $A=a$), their observed outcome $Y$ is precisely their potential outcome $Y^a$. Therefore, we can substitute the unobservable $\\E{Y^a | A=a, L=l}$ with the observable quantity $\\E{Y | A=a, L=l}$, which is the average outcome among those with treatment $a$ and confounder value $l$.\n\nThe final expression is the g-formula.\n\n## References",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}