{
  "hash": "37cb94258f51932ee525455655a7b641",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 10: Time-Varying Treatments and Marginal Structural Models\"\n---\n\n# Week 10: Time-Varying Treatments & MSMs ⏳\n\nWelcome, everyone. This week, we venture into one of the most complex and realistic scenarios in applied causal inference: analyzing longitudinal data where treatments, confounders, and outcomes are measured over time. Standard methods can fail spectacularly here. Our goal is to understand *why* they fail and to master a powerful tool for this challenge: the **Marginal Structural Model (MSM)**.\n\n## R Packages\n\nFirst, let's ensure our R environment is ready. We'll use `pacman` to load all necessary packages for today's lecture and lab.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) {\n  install.packages(\"pacman\")\n}\npacman::p_load(\n  tidyverse, # For data manipulation and plotting\n  dagitty, # For creating and analyzing DAGs\n  ggdag, # For plotting DAGs with ggplot2\n  geepack, # For fitting generalized estimating equations (for MSMs)\n  cobalt, # For checking covariate balance\n  knitr, # For table formatting\n  kableExtra # More table formatting options\n)\n```\n:::\n\n\n## Learning Objectives\n\nBy the end of this week's lecture and lab, you will be able to:\n\n1.  **Identify** and **illustrate** the problem of treatment-confounder feedback using a Directed Acyclic Graph (DAG).\n2.  **Explain** the limitations of standard regression adjustment in the presence of time-varying confounders that are also mediators.\n3.  **Define** a \"treatment strategy\" and differentiate its causal effect from that of a static, one-time treatment.\n4.  **Articulate** the key assumption of sequential exchangeability and its role in estimating the effects of treatment strategies.\n5.  **Calculate** stabilized inverse probability of treatment weights (IPWs) by hand for a simple, two-timepoint scenario.\n6.  **Implement** an MSM in R by modeling treatment probabilities, calculating stabilized weights, and fitting a weighted regression model using `geeglm()`.\n7.  **Assess** the validity of an MSM analysis by checking weight distribution and covariate balance in the pseudo-population.\n\n## 1. Comprehensive Topic Explanation\n\nIn many longitudinal studies, a patient's treatment in a given time interval may depend on their evolving health status. The challenge arises when that same health status is *also* affected by prior treatments. This creates a feedback loop that can severely bias our causal estimates if not handled correctly.\n\n## The Core Problem: Treatment-Confounder Feedback\n\nLet's consider a common clinical scenario. A patient with a chronic disease receives a treatment ($A$). Their response is monitored using a time-varying biomarker ($L$), such as viral load or blood pressure. The physician then uses the current value of $L$ to decide whether to continue or modify treatment in the next period.\n\nHere, the biomarker $L$ is:\n\n1.  A **confounder** for the *next* treatment's effect, because it predicts both future treatment ($A_{t+1}$) and the final outcome ($Y$).\n2.  A **mediator** of the *previous* treatment's effect, as past treatment ($A_t$) affects the biomarker's value ($L_{t+1}$), which in turn affects the outcome ($Y$).\n\nThis dual role is the essence of **treatment-confounder feedback**.\n\nLet's visualize this for two time points ($t=0$ and $t=1$). Let $L_0$ be a baseline confounder, $A_0$ the initial treatment, $L_1$ the time-varying confounder, $A_1$ the second treatment, and $Y$ the final outcome.\n\n\n::: {.cell .column-margin}\n\n:::\n\n\n::: {#fig-dag-time-varying-confounding}\n\n```tikz\n% In your preamble:\n% \\usepackage{tikz}\n% \\usetikzlibrary{positioning, fit, arrows.meta}\n\n\\begin{tikzpicture}[\n  % --- styles ---\n  >=Stealth, % modern arrow tip\n  var/.style   = {draw, rounded corners, align=center, minimum width=20mm, minimum height=7mm},\n  treat/.style = {var, fill=black!3},\n  outcome/.style = {var, fill=black!5},\n  timebox/.style = {draw, rounded corners, inner sep=6pt},\n  node distance = 18mm and 26mm\n]\n\n% --- nodes: Time 0 ---\n\\node[var]   (L0) {$L_0$: Baseline Confounder};\n\\node[treat, right=of L0] (A0) {$A_0$: Treatment};\n\n% --- nodes: Time 1 ---\n\\node[var, below=of L0]   (L1) {$L_1$: Time-Varying Confounder};\n\\node[treat, right=of L1] (A1) {$A_1$: Treatment};\n\n% --- node: Outcome ---\n\\node[outcome, right=30mm of A1] (Y) {$Y$: Final Outcome};\n\n% --- group boxes (fit) ---\n\\node[timebox, fit=(L0) (A0), label={[yshift=2mm]above:\\strut Time 0}]   (T0) {};\n\\node[timebox, fit=(L1) (A1), label={[yshift=2mm]above:\\strut Time 1}]   (T1) {};\n\\node[timebox, fit=(Y),    label={[yshift=2mm]above:\\strut Outcome}]     (TO) {};\n\n% --- edges (causal paths) ---\n\\draw[->] (L0) -- (A0);\n\\draw[->] (L0) -- (L1);\n\\draw[->] (A0) -- (L1);\n\\draw[->] (A0) -- (A1);\n\\draw[->] (L1) -- (A1);\n\\draw[->] (L1) to[bend right=20] (Y);\n\\draw[->] (A1) -- (Y);\n% Optional direct path:\n\\draw[->] (A0) to[bend left=10] (Y);\n\n\\end{tikzpicture}\n```\nDAG for Time-Varying Confounding\n:::\n\nLook at the path $A_0 \\rightarrow L_1 \\rightarrow A_1 \\rightarrow Y$. $L_1$ lies on this causal path. Now, consider the confounding of the $A_1 \\rightarrow Y$ relationship. There is a backdoor path $A_1 \\leftarrow L_1 \\rightarrow Y$. To close this backdoor path and get an unbiased estimate of the effect of $A_1$, conventional wisdom says we must \"adjust for\" or \"condition on\" $L_1$.\n\nHowever, conditioning on $L_1$ is problematic. Because $L_1$ is a descendant of $A_0$ (it's on the causal pathway from $A_0$ to $Y$), conditioning on it blocks part of the total causal effect of the treatment sequence ($A_0$, then $A_1$). As Hernán & Robins (2025, Part III) emphasize, standard adjustment methods like stratification or regression, which condition on $L_1$, will produce biased estimates of the total effect of the treatment strategy.\n\n## The Solution: Marginal Structural Models (MSMs)\n\nInstead of conditioning on the problematic variable $L_1$, MSMs take a different approach. They use **Inverse Probability of Treatment Weighting (IPW)** to create a \"pseudo-population\" in which the arrows from the time-varying confounders (like $L_1$) into subsequent treatments (like $A_1$) are broken. In this pseudo-population, treatment assignment is no longer confounded by the prior covariate history, and we can directly estimate the causal effect using a simple weighted model.\n\nThe model is \"marginal\" because it models the marginal mean of the potential outcome, $E[Y^{\\bar{a}}]$, over the entire population, not conditional on the confounders. It is \"structural\" because it aims to estimate the causal effect of a specified treatment strategy.\n\nA **treatment strategy** (or \"regime\"), denoted $\\bar{a} = (a_0, a_1, \\dots, a_K)$, is a sequence of treatment decisions over the study period. The goal of an MSM is to compare the outcomes under different strategies, for example, the strategy \"always treat\" ($\\bar{a}=(1,1,\\dots,1)$) versus \"never treat\" ($\\bar{a}=(0,0,\\dots,0)$).\n\n## 2. Intuitive Clarifications of Challenging Ideas\n\n## Analogy: Creating a Fair Race with Handicaps\n\nImagine a multi-stage race where, after each stage, healthier-looking runners are given a heavier backpack for the next stage. The organizers want to know the \"causal effect\" of always wearing a heavy backpack versus always wearing a light one. A naive comparison would be biased because the healthier runners (who are more likely to win anyway) are the ones assigned the heavy backpacks.\n\nIPW is like re-weighting the runners' results to simulate a fair race. A runner who was healthy but, against the odds, was given a *light* backpack gets a large weight. Their outcome now \"counts for more\" because they represent many other healthy runners who were forced to take heavy backpacks. Conversely, a less-healthy runner who (as expected) got a light backpack gets a smaller weight.\n\nBy creating these weights, we generate a pseudo-population of runners where the choice of backpack at each stage is independent of their health. In this new, weighted population, we can finally make a fair comparison. This is exactly what MSMs do, but with patient data instead of runners.\n\n## Sequential Exchangeability: The Key Assumption\n\nFor a single time-point study, we needed the assumption of *exchangeability* ($Y^a \\indep A \\mid L$) to control for confounding. For time-varying treatments, we need a stronger, sequential version of this assumption.\n\n::: callout-important\n## 📌 Key Assumption: Sequential Exchangeability\n\nSequential exchangeability states that at every time point $k$, the treatment $A_k$ is independent of the potential outcomes $Y^{\\bar{a}}$, conditional on the observed past treatment history ($\\bar{A}_{k-1}$) and past covariate history ($\\bar{L}_k$). Formally:\n\n$$\nY^{\\bar{a}} \\indep A_k \\mid \\bar{A}_{k-1} = \\bar{a}_{k-1}, \\bar{L}_k\n$$\n\nfor all strategies $\\bar{a}$ and time points $k$.\n\nThis means that within any given history of past treatments and covariates, the specific treatment a person receives at time $k$ is effectively random with respect to their ultimate potential outcome. It is the crucial assumption that allows us to use IPW to adjust for confounding over time.\n:::\n\n## 3. Simple, Hand-Calculation Numerical Example(s)\n\nLet's solidify these ideas with a toy example. Consider a two-day study ($k=0, 1$) with 5 patients.\n\n-   $L_0=1$ for all (baseline, not a confounder here).\n-   $A_k$: Treatment at day $k$ (1=Treated, 0=Untreated).\n-   $L_1$: Biomarker on day 1 (1=High, 0=Low). High is \"bad\".\n-   $Y$: Outcome at day 2 (1=Recovered, 0=Not).\n\nOur goal is to estimate the causal risk ratio of the strategy \"always treat\" ($A_0=1, A_1=1$) versus \"never treat\" ($A_0=0, A_1=0$).\n\nHere is our observed data:\n\n| ID  | $A_0$ | $L_1$ | $A_1$ | $Y$ |\n|:---:|:-----:|:-----:|:-----:|:---:|\n|  1  |   0   |   0   |   0   |  1  |\n|  2  |   0   |   1   |   1   |  0  |\n|  3  |   1   |   0   |   0   |  1  |\n|  4  |   1   |   0   |   1   |  1  |\n|  5  |   1   |   1   |   1   |  0  |\n\n: Table 1: Observed Data for 5 Patients Over 2 Days {#tbl:obs-data}\n\n### Step 1: Model Treatment Probabilities\n\nWe need to estimate $\\Prob{A_k=a_k \\mid \\bar{L}_k, \\bar{A}_{k-1}}$.\n\n-   For $A_0$: It only depends on $L_0$. Since $L_0=1$ for everyone, $\\Prob{A_0=1} = 3/5 = 0.6$.\n-   For $A_1$: It depends on $A_0$ and $L_1$.\n    -   $\\Prob{A_1=1 \\mid A_0=0, L_1=0} = 0/1 = 0$\n    -   $\\Prob{A_1=1 \\mid A_0=0, L_1=1} = 1/1 = 1$\n    -   $\\Prob{A_1=1 \\mid A_0=1, L_1=0} = 1/2 = 0.5$\n    -   $\\Prob{A_1=1 \\mid A_0=1, L_1=1} = 1/1 = 1$\n\n### Step 2: Calculate Stabilized IP Weights ($SW_i$)\n\nThe formula for the stabilized weight for an individual $i$ is:\n\n$$\nSW_i = \\prod_{k=0}^{K} \\frac{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}}}{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}, \\bar{L}_{i,k}}} \n$$\n\nThe numerator is the marginal probability of receiving the observed treatment at time $k$, given past *treatment* history. The denominator is the probability conditional on past treatment *and* covariate history.\n\n-   **Numerator Models (marginal probability of treatment):**\n    -   $\\Prob{A_0=1} = 3/5 = 0.6$. So $\\Prob{A_0=0}=0.4$.\n    -   $\\Prob{A_1=1 \\mid A_0=0} = \\frac{\\text{ID=2}}{\\text{ID=1,2}} = 1/2 = 0.5$.\n    -   $\\Prob{A_1=1 \\mid A_0=1} = \\frac{\\text{ID=4,5}}{\\text{ID=3,4,5}} = 2/3$.\n\nLet's calculate the weight for **Patient 2**: ($A_0=0, A_1=1, L_1=1$)\n\n-   Numerator (k=0): $\\Prob{A_0=0} = 0.4$\n-   Denominator (k=0): $\\Prob{A_0=0} = 0.4$ (no confounders at baseline)\n-   Numerator (k=1): $\\Prob{A_1=1 \\mid A_0=0} = 0.5$\n-   Denominator (k=1): $\\Prob{A_1=1 \\mid A_0=0, L_1=1} = 1.0$\n-   $SW_2 = \\frac{0.4}{0.4} \\times \\frac{0.5}{1.0} = 0.5$\n\nLet's calculate the weight for **Patient 3**: ($A_0=1, A_1=0, L_1=0$)\n\n-   Numerator (k=0): $\\Prob{A_0=1} = 0.6$\n-   Denominator (k=0): $\\Prob{A_0=1} = 0.6$\n-   Numerator (k=1): $\\Prob{A_1=0 \\mid A_0=1} = 1/3$\n-   Denominator (k=1): $\\Prob{A_1=0 \\mid A_0=1, L_1=0} = 1 - 0.5 = 0.5$\n-   $SW_3 = \\frac{0.6}{0.6} \\times \\frac{1/3}{0.5} \\approx 0.67$\n\nYou can calculate the weights for all patients this way:\n\n| ID | $A_0$ | $L_1$ | $A_1$ | $Y$ | Numerator | Denominator | $SW_i$ |   |   |\n|:------:|:------:|:------:|:------:|:------:|:-------|:-------|:------:|--------|--------|\n| 1 | 0 | 0 | 0 | 1 | $P(A_0=0)P(A_1=0 | A_0=0) = 0.4 \\times 0.5$ | $P(A_0=0)P(A_1=0 | A_0=0,L_1=0) = 0.4 \\times 1.0$ | 0.5 |  |  |\n| 2 | 0 | 1 | 1 | 0 | $P(A_0=0)P(A_1=1 | A_0=0) = 0.4 \\times 0.5$ | $P(A_0=0)P(A_1=1 | A_0=0,L_1=1) = 0.4 \\times 1.0$ | 0.5 |  |  |\n| 3 | 1 | 0 | 0 | 1 | $P(A_0=1)P(A_1=0 | A_0=1) = 0.6 \\times 1/3$ | $P(A_0=1)P(A_1=0 | A_0=1,L_1=0) = 0.6 \\times 0.5$ | 0.67 |  |  |\n| 4 | 1 | 0 | 1 | 1 | $P(A_0=1)P(A_1=1 | A_0=1) = 0.6 \\times 2/3$ | $P(A_0=1)P(A_1=1 | A_0=1,L_1=0) = 0.6 \\times 0.5$ | 1.33 |  |  |\n| 5 | 1 | 1 | 1 | 0 | $P(A_0=1)P(A_1=1 | A_0=1) = 0.6 \\times 2/3$ | $P(A_0=1)P(A_1=1 | A_0=1,L_1=1) = 0.6 \\times 1.0$ | 0.67 |  |  |\n\n: Calculation of Stabilized Weights {#tbl:weights}\n\n### Step 3: Fit the Weighted Model\n\nNow we fit a model for the outcome $Y$ on treatments $A_0$ and $A_1$, weighted by $SW_i$. The model is: $\\E{Y \\mid A_0, A_1} = \\beta_0 + \\beta_1 A_0 + \\beta_2 A_1$. We are interested in comparing the strategy $(A_0=1, A_1=1)$ vs $(A_0=0, A_1=0)$.\n\nRisk under \"Always Treat\" ($A_0=1, A_1=1$): Only patients 4 and 5 followed this.\n\n-   Weighted mean: $\\frac{\\sum (Y_i \\times SW_i)}{\\sum SW_i} = \\frac{(1 \\times 1.33) + (0 \\times 0.67)}{1.33 + 0.67} = \\frac{1.33}{2.0} = 0.665$\n\nRisk under \"Never Treat\" ($A_0=0, A_1=0$): Only patient 1 followed this.\n\n-   Weighted mean: $\\frac{\\sum (Y_i \\times SW_i)}{\\sum SW_i} = \\frac{1 \\times 0.5}{0.5} = 1.0$\n\n**Causal Risk Ratio (RR)** = Risk(Always)/Risk(Never) = 0.665 / 1.0 = 0.665.\n\nThis hand-calculation shows how the weights create a pseudo-population where the effect of the treatment strategy can be estimated via a simple weighted average.\n\n## 4. R Code Examples & Interpretation\n\nLet's work through a more realistic simulation. We'll simulate data according to the DAG above, show that a naive model fails, and then correctly implement an MSM.\n\n## Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(579)\nn <- 1000 # number of patients\n# Baseline confounder L0\nL0 <- rnorm(n)\n# Treatment at time 0 depends on L0\nA0_prob <- plogis(-1 + L0)\nA0 <- rbinom(n, 1, A0_prob)\n# Time-varying confounder L1 depends on A0 and L0\nL1 <- -0.5 * A0 + 0.8 * L0 + rnorm(n)\n# Treatment at time 1 depends on L1, A0, and L0\nA1_prob <- plogis(-1 + 0.6 * A0 + 1.2 * L1 + 0.5 * L0)\nA1 <- rbinom(n, 1, A1_prob)\n# Outcome Y depends on A0, A1, and L1\nY <- 1 + 2 * A0 + 2 * A1 - 0.9 * L1 + rnorm(n)\n\nsim_data <- data.frame(id = 1:n, L0, A0, L1, A1, Y)\nhead(sim_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"id\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"L0\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"A0\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"L1\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"A1\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Y\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"-0.8920998\",\"3\":\"0\",\"4\":\"-0.45416965\",\"5\":\"0\",\"6\":\"1.6415684\",\"_rn_\":\"1\"},{\"1\":\"2\",\"2\":\"1.1454240\",\"3\":\"1\",\"4\":\"1.11859403\",\"5\":\"0\",\"6\":\"3.3790354\",\"_rn_\":\"2\"},{\"1\":\"3\",\"2\":\"1.2482900\",\"3\":\"1\",\"4\":\"0.99526687\",\"5\":\"0\",\"6\":\"2.4076204\",\"_rn_\":\"3\"},{\"1\":\"4\",\"2\":\"-0.2885184\",\"3\":\"0\",\"4\":\"0.03554861\",\"5\":\"0\",\"6\":\"0.8584807\",\"_rn_\":\"4\"},{\"1\":\"5\",\"2\":\"0.6030561\",\"3\":\"0\",\"4\":\"-0.19005879\",\"5\":\"0\",\"6\":\"2.2045154\",\"_rn_\":\"5\"},{\"1\":\"6\",\"2\":\"-1.9201312\",\"3\":\"0\",\"4\":\"0.36221283\",\"5\":\"0\",\"6\":\"0.8429704\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIn this simulation, the true causal effect of $A_0$ is +2 and $A_1$ is +2. So, the average causal effect (ACE) of the strategy $(A_0=1, A_1=1)$ vs $(A_0=0, A_1=0)$ is 4.\n\n## The Naive (Biased) Model\n\nA standard approach would be to regress $Y$ on the treatments and the time-varying confounder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive_model <- lm(Y ~ A0 + A1 + L1, data = sim_data)\nsummary(naive_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error   t value      Pr(>|t|)\n(Intercept)  1.016757 0.04386305  23.18028  2.074371e-95\nA0           2.028523 0.07162024  28.32333 6.309233e-130\nA1           1.980419 0.08042995  24.62291 6.101070e-105\nL1          -0.931388 0.02976920 -31.28696 3.229921e-150\n```\n\n\n:::\n:::\n\n\nThe estimate for `A0` is 2.03 and for `A1` is 1.98. Both are biased downwards. The `A0` coefficient is particularly attenuated because we conditioned on a mediator (`L1`) of its effect.\n\n## MSM Step 1: Estimate Weights\n\nWe need to fit two logistic regression models for the treatment probabilities, one for $A_0$ and one for $A_1$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Denominator model for A0\nden_mod_A0 <- glm(A0 ~ L0, data = sim_data, family = binomial)\n# Denominator model for A1\nden_mod_A1 <- glm(A1 ~ L1 + A0 + L0, data = sim_data, family = binomial)\n\n# Numerator model for A0 (no past history)\nnum_mod_A0 <- glm(A0 ~ 1, data = sim_data, family = binomial)\n# Numerator model for A1\nnum_mod_A1 <- glm(A1 ~ A0, data = sim_data, family = binomial)\n\n# Get probabilities\nsim_data$pd_A0 <- predict(den_mod_A0, type = \"response\")\nsim_data$pd_A1 <- predict(den_mod_A1, type = \"response\")\nsim_data$pn_A0 <- predict(num_mod_A0, type = \"response\")\nsim_data$pn_A1 <- predict(num_mod_A1, type = \"response\")\n```\n:::\n\n\nNow, calculate the stabilized weight for each person at each time point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Weight for A0\nsim_data$sw_A0 <- ifelse(\n  sim_data$A0 == 1,\n  sim_data$pn_A0 / sim_data$pd_A0,\n  (1 - sim_data$pn_A0) / (1 - sim_data$pd_A0)\n)\n# Weight for A1\nsim_data$sw_A1 <- ifelse(\n  sim_data$A1 == 1,\n  sim_data$pn_A1 / sim_data$pd_A1,\n  (1 - sim_data$pn_A1) / (1 - sim_data$pd_A1)\n)\n# Final weight is the product\nsim_data$sw <- sim_data$sw_A0 * sim_data$sw_A1\n```\n:::\n\n\n## MSM Step 2: Fit the Weighted Model\n\nWe use `geeglm` from the `geepack` package. This is a generalization of `glm` that can account for repeated measures on the same subject (though in this specific simulation, we only have one outcome per subject, for more complex MSM setups it's essential). We specify the weights using the `weights` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The model for the outcome Y does NOT include the confounder L1\n# It is a marginal model\nmsm_fit <- geeglm(\n  Y ~ A0 + A1,\n  data = sim_data,\n  id = id, # cluster by patient\n  weights = sw,\n  corstr = \"independence\"\n)\n\nsummary(msm_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ngeeglm(formula = Y ~ A0 + A1, data = sim_data, weights = sw, \n    id = id, corstr = \"independence\")\n\n Coefficients:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std.err   Wald Pr(>|W|)    \n(Intercept)   0.9257  0.1673  30.63 3.13e-08 ***\nA0            2.4856  0.1588 244.84  < 2e-16 ***\nA1            1.8154  0.1735 109.47  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation structure = independence \nEstimated Scale Parameters:\n\n            Estimate Std.err\n(Intercept)    2.362  0.2988\nNumber of clusters:   1000  Maximum cluster size: 1 \n```\n\n\n:::\n:::\n\n\n**Interpretation**: The coefficient for `A0` is 2.49 and for `A1` is 1.82. Their sum is 4.3, which is very close to our true simulated effect of 4. We have successfully recovered the true causal effect by using IPW to break the treatment-confounder feedback loop.\n\n## 5. Hands-On R Lab\n\n## Lab Objectives\n\n-   Practice estimating stabilized IP weights for an MSM.\n-   Diagnose potential issues by examining the distribution of weights.\n-   Fit and interpret a marginal structural model to estimate the causal effect of a treatment strategy.\n\n## Reading Warm-Up\n\nBefore you begin, please review Hernán & Robins (2025), Chapter 21, on Marginal Structural Models.\n\n## Lab Task: HIV Treatment Strategy\n\nWe will use a simulated dataset (`hiv_data.csv`) that mimics a real-world cohort of HIV patients.\n\n-   `id`: Patient identifier.\n-   `time`: Visit number (0, 1, 2).\n-   `cd4`: CD4 count at that visit (a time-varying confounder). A lower CD4 count is worse.\n-   `azt`: Whether the patient started AZT therapy at that visit (1=Yes, 0=No). This is our time-varying treatment.\n-   `cd4_final`: CD4 count at the end of the study (the outcome `Y`).\n\n**Goal**: Estimate the causal effect of a strategy of \"always starting AZT at the first opportunity\" versus \"never starting AZT\".\n\n### Setup: Load and Reshape Data\n\nFirst, let's create and inspect the data. In longitudinal studies, data is often in \"long\" format, with one row per person-time-point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn_lab <- 500\n# Baseline\nid <- 1:n_lab\ncd4_0 <- rnorm(n_lab, 500, 50)\n# Time 1\nazt_0_prob <- plogis(-8 + (cd4_0 / 50)) # Lower CD4 -> higher chance of AZT\nazt_0 <- rbinom(n_lab, 1, azt_0_prob)\ncd4_1 <- 0.8 * cd4_0 + 20 * azt_0 + rnorm(n_lab, 50, 10)\n# Time 2\nazt_1_prob <- plogis(-8 + (cd4_1 / 50) + 0.5 * azt_0)\nazt_1 <- rbinom(n_lab, 1, azt_1_prob)\ncd4_final <- 0.7 * cd4_1 + 40 * azt_1 + 30 * azt_0 + rnorm(n_lab, 100, 20)\n\n# Create a long dataset\ndata_t0 <- data.frame(id, time = 0, azt = azt_0, cd4 = cd4_0)\ndata_t1 <- data.frame(id, time = 1, azt = azt_1, cd4 = cd4_1)\nhiv_long <- rbind(data_t0, data_t1)\n\n# Create a wide dataset for modeling\nhiv_wide <- data.frame(\n  id,\n  L0_cd4 = cd4_0,\n  A0_azt = azt_0,\n  L1_cd4 = cd4_1,\n  A1_azt = azt_1,\n  Y_cd4 = cd4_final\n)\n\n# Display some of the wide data\nkable(head(hiv_wide), \"html\") %>%\n  kable_styling(bootstrap_options = \"striped\", full_width = F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> id </th>\n   <th style=\"text-align:right;\"> L0_cd4 </th>\n   <th style=\"text-align:right;\"> A0_azt </th>\n   <th style=\"text-align:right;\"> L1_cd4 </th>\n   <th style=\"text-align:right;\"> A1_azt </th>\n   <th style=\"text-align:right;\"> Y_cd4 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 472.0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 463.0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 437.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 488.5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 459.7 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 485.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:right;\"> 577.9 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 537.5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 528.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 503.5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 475.0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 515.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 506.5 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 473.3 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 523.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 585.8 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 537.4 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 588.7 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Task 1: Model Treatment Probabilities\n\nFit the logistic regression models needed to calculate the stabilized weights. You need one model for `A0_azt` and another for `A1_azt`.\n\n``` r\n#| label: lab-task-1\n# Skeleton code for you to fill in\n\n# Denominator model for A0\nden_mod_A0_lab <- glm(A0_azt ~ # … your code here\n                     , data = hiv_wide, family = binomial)\n\n# Denominator model for A1\nden_mod_A1_lab <- glm(A1_azt ~ # … your code here\n                     , data = hiv_wide, family = binomial)\n\n# Numerator model for A0\nnum_mod_A0_lab <- glm(A0_azt ~ # … your code here\n                     , data = hiv_wide, family = binomial)\n\n# Numerator model for A1\nnum_mod_A1_lab <- glm(A1_azt ~ # … your code here\n                     , data = hiv_wide, family = binomial)\n```\n\n\\<details\\>\n\n\\<summary\\>Solution to Task 1\\</summary\\>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Denominator model for A0 (depends on baseline covariates)\nden_mod_A0_lab <- glm(A0_azt ~ L0_cd4, data = hiv_wide, family = binomial)\n# Denominator model for A1 (depends on past treatment and full covariate history)\nden_mod_A1_lab <- glm(\n  A1_azt ~ A0_azt + L0_cd4 + L1_cd4,\n  data = hiv_wide,\n  family = binomial\n)\n# Numerator model for A0 (unconditional)\nnum_mod_A0_lab <- glm(A0_azt ~ 1, data = hiv_wide, family = binomial)\n# Numerator model for A1 (depends only on past treatment)\nnum_mod_A1_lab <- glm(A1_azt ~ A0_azt, data = hiv_wide, family = binomial)\n```\n:::\n\n\n\\</details\\>\n\n### Task 2: Calculate Stabilized Weights\n\nUsing the models from Task 1, calculate the final stabilized weight (`sw`) for each patient.\n\n``` r\n#| label: lab-task-2\n\n# Skeleton code for you to fill in\n\n# Predict probabilities\nhiv_wide$pd0 <- predict(den_mod_A0_lab, type = \"response\")\n# … add predictions for the other 3 models …\n\n# Calculate weight for A0\nhiv_wide$sw0 <- # … your code here …\n  # Calculate weight for A1\n  hiv_wide$sw1 <- # … your code here …\n    # Calculate final weight\n    hiv_wide$sw <- # … your code here …\n      # Look at the summary of the weights\n      summary(hiv_wide$sw)\n```\n\n\\<details\\>\n\n\\<summary\\>Solution to Task 2\\</summary\\>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict probabilities\nhiv_wide$pd0 <- predict(den_mod_A0_lab, type = \"response\")\nhiv_wide$pd1 <- predict(den_mod_A1_lab, type = \"response\")\nhiv_wide$pn0 <- predict(num_mod_A0_lab, type = \"response\")\nhiv_wide$pn1 <- predict(num_mod_A1_lab, type = \"response\")\n\n# Calculate weight for A0\n\nhiv_wide$sw0 <- ifelse(\n  hiv_wide$A0_azt == 1,\n  hiv_wide$pn0 / hiv_wide$pd0,\n  (1 - hiv_wide$pn0) / (1 - hiv_wide$pd0)\n)\n\n# Calculate weight for A1\n\nhiv_wide$sw1 <- ifelse(\n  hiv_wide$A1_azt == 1,\n  hiv_wide$pn1 / hiv_wide$pd1,\n  (1 - hiv_wide$pn1) / (1 - hiv_wide$pd1)\n)\n\n# Calculate final weight\n\nhiv_wide$sw <- hiv_wide$sw0 * hiv_wide$sw1\n\n# Look at the summary of the weights\n\nsummary(hiv_wide$sw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.109   0.819   0.905   1.001   1.045   7.541 \n```\n\n\n:::\n\n```{.r .cell-code}\nhist(\n  hiv_wide$sw,\n  breaks = 50,\n  main = \"Distribution of Stabilized Weights\",\n  xlab = \"sw\"\n)\n```\n\n::: {.cell-output-display}\n![](week-10_time_varying_treatment-rev1_files/figure-html/lab-sol-2-1.png){width=672}\n:::\n:::\n\n\n</details>\n\n### Task 3: Fit the Final MSM and Interpret\n\nFit a weighted linear model using `geeglm` to estimate the effect of the AZT treatment strategy (`A0_azt` and `A1_azt`) on the final CD4 count (`Y_cd4`).\n\n``` r\n#| label: lab-task-3\n\n# Skeleton code for you to fill in\n\nmsm_lab_fit <- geeglm(\n  Y_cd4 ~ # … your model formula …\n  ,\n  data = hiv_wide,\n  id = id,\n  weights = sw,\n  corstr = \"independence\"\n)\n\nsummary(msm_lab_fit)\n```\n\n\\<details\\>\n\n\\<summary\\>Solution to Task 3\\</summary\\>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmsm_lab_fit <- geeglm(\n  Y_cd4 ~ A0_azt + A1_azt,\n  data = hiv_wide,\n  id = id,\n  weights = sw,\n  corstr = \"independence\"\n)\n\nsummary(msm_lab_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ngeeglm(formula = Y_cd4 ~ A0_azt + A1_azt, data = hiv_wide, weights = sw, \n    id = id, corstr = \"independence\")\n\n Coefficients:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std.err   Wald Pr(>|W|)    \n(Intercept)   413.29    5.83 5020.3  < 2e-16 ***\nA0_azt         44.37    6.56   45.8  1.3e-11 ***\nA1_azt         44.16    5.57   62.8  2.2e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation structure = independence \nEstimated Scale Parameters:\n\n            Estimate Std.err\n(Intercept)     1150    88.3\nNumber of clusters:   500  Maximum cluster size: 1 \n```\n\n\n:::\n:::\n\n\n</details>\n\n### Retrieval & Reflection\n\n1.  **Interpret the coefficient for `A0_azt`** from the final model. What does it represent?\n2.  Using the model output, what is the estimated average causal effect on final CD4 count of the strategy \"take AZT at time 0 and time 1\" compared to the strategy \"never take AZT\"?\n3.  Why did we use `L0_cd4` and `L1_cd4` in the *denominator* models for the weights, but not in the *final outcome model*?\n4.  Look at the histogram of your weights. What would it mean if you saw one patient with a weight of 500? What problem would this indicate?\n\n## 6. Common Pitfalls & Checks\n\n::: callout-warning\n## Common Pitfall: Model Misspecification & Extreme Weights\n\nThe validity of your MSM depends entirely on the correct specification of the weight models. If your models for $\\Prob{A_k \\mid \\dots}$ are wrong, your weights will be wrong, and your final estimate will be biased.\n\nA major warning sign is the presence of **extreme weights**. A very large weight for one individual means that their observed treatment history was extremely unlikely given their covariate history. This suggests a violation of the **positivity assumption** (i.e., that all patients have a non-zero probability of receiving any treatment history). These influential individuals can destabilize your results. Always check the distribution of your weights. If you see extreme weights, you may need to reconsider your model, or in some cases, truncate the weights.\n:::\n\n::: callout-tip\n## Checking Balance\n\nA key check is to see if your weighting scheme worked. In the pseudo-population (i.e., using the weights), the baseline covariates should not predict treatment assignment. We can check this using the `cobalt` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking balance for treatment A1\n# We are checking if L0_cd4 and L1_cd4 are balanced across A1 groups\n# in the weighted sample.\nbal.tab(\n  A1_azt ~ L0_cd4 + L1_cd4 + A0_azt,\n  data = hiv_wide,\n  weights = \"sw\",\n  method = \"weighting\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n          Type Diff.Adj\nL0_cd4 Contin.    0.089\nL1_cd4 Contin.    0.171\nA0_azt  Binary    0.171\n\nEffective sample sizes\n           Control Treated\nUnadjusted    85.      415\nAdjusted      43.3     363\n```\n\n\n:::\n:::\n\n\nWe are looking for \"Mean Diff\" values close to zero in the `Balanced` table, which indicates that our weighting has successfully removed the association between the confounders and the treatment.\n:::\n\n## 7. Advanced Teaching Activities & Interactivity\n\n1.  **Think-Pair-Share**:\n    -   **Prompt**: \"Consider a study on the effect of a dynamic anti-hypertension drug regimen on risk of stroke. Blood pressure is measured monthly. When is blood pressure a confounder, and when is it a mediator? Draw the DAG. Why can't you just 'put blood pressure in the regression model'?\"\n    -   **Activity**: Students first think individually (1 min), then draw the DAG and discuss with a partner (3 min), then share their conclusions with the class (3 min).\n2.  **Problem-Based Case**:\n    -   **Case**: Present a simplified version of a real clinical trial protocol with longitudinal treatment decisions.\n    -   **Task**: In small groups, students must identify the time-varying treatments and confounders, define the causal question in terms of a \"treatment strategy,\" and outline the full analysis plan, including the specific models they would need to fit for an MSM analysis.\n3.  **Self-Explanation Task**:\n    -   After the hand-calculation example, ask students to write a short paragraph explaining in their own words *why* the IPW pseudo-population allows for an unbiased estimate. This forces them to process the core logic rather than just mechanically executing steps.\n\n## 8. Appendix: Advanced Theory & Derivations\n\n## The Mathematics of Stabilized Weights\n\nOur goal is to estimate the parameters of a marginal structural model, such as:\n\n$$\n\\E{Y^{\\bar{a}}} = \\beta_0 + \\beta_1 \\sum_k a_k\n$$\n\nwhere $\\bar{a} = (a_0, \\dots, a_K)$ is a specific treatment strategy.\n\nThe problem is that in our observed data, the association between treatment $\\bar{A}$ and outcome $Y$ is confounded. IPW creates a pseudo-population where this confounding is removed. The weight for an individual $i$ is:\n\n$$\nW_i = \\frac{1}{\\prod_{k=0}^{K} \\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i,k-1}, \\bar{L}_{i,k}}}\n$$\n\nThese are \"unstabilized\" weights. They have a mean of 1 but can have very high variance. High variance in weights leads to inefficient and unstable estimates.\n\n**Stabilized weights** ($SW_i$) were developed to reduce this variance. The formula is:\n\n$$\nSW_i = \\prod_{k=0}^{K} \\frac{f(A_k \\mid \\bar{A}_{k-1})}{f(A_k \\mid \\bar{A}_{k-1}, \\bar{L}_k)}\n$$\n\nwhere $f(\\cdot)$ is the probability density or mass function. The denominator is the same as before: the probability of the observed treatment given past treatment and covariate history. The numerator, however, is new. It is the probability of the observed treatment given only past *treatment* history.\n\nThis numerator \"stabilizes\" the weights by pulling them back towards 1, reducing their variance. As shown by Hernán & Robins (2025, Chapter 21), fitting a weighted model with $SW_i$ still yields a consistent estimator for the MSM parameters, provided the key assumptions (sequential exchangeability, positivity, consistency, no measurement error) hold and the models for the weights are correctly specified. The resulting estimator is more efficient than one using unstabilized weights.\n\n## Numeric Illustration\n\nConsider Patient 3 from our hand-calculation example.\n\n-   Observed history: $A_0=1, A_1=0$.\n\n-   Unstabilized Weight: $$\n    W_3 = \\frac{1}{P(A_0=1) \\times P(A_1=0 \\mid A_0=1, L_1=0)} = \\frac{1}{0.6 \\times 0.5} = \\frac{1}{0.3} \\approx 3.33\n    $$\n\n-   Stabilized Weight: $$\n    SW_3 = \\frac{P(A_0=1) \\times P(A_1=0 \\mid A_0=1)}{P(A_0=1) \\times P(A_1=0 \\mid A_0=1, L_1=0)} = \\frac{0.6 \\times (1/3)}{0.6 \\times 0.5} = \\frac{0.2}{0.3} \\approx 0.67\n    $$\n\nNote how the stabilized weight is much smaller and less extreme than the unstabilized version. This leads to more stable and precise final estimates.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}