{
  "hash": "4a9287d8166b67034573c2308fc3628f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inverse Probability Weighting and Marginal Structural Models\"\nnocite: \"@cunningham2021causal, @pearl2009causality, @imbens2015causal, @vanderweele2015book\"\n---\n\n\n\n## R Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  # Core data manipulation and visualization\n  tidyverse, # ggplot2, dplyr, tidyr, purrr, etc.\n  data.table, # Efficient large data handling\n  here, # File path management\n\n  # Causal inference specialized packages\n  dagitty, # DAG creation and analysis\n  ggdag, # DAG visualization\n  survey, # For weighted analyses and complex surveys\n  MatchIt, # Propensity score matching\n  WeightIt, # Advanced weighting methods\n  tableone, # Balance tables\n  cobalt, # Balance assessment and visualization\n  marginaleffects, # Counterfactual predictions and contrasts\n  tmle, # Targeted maximum likelihood estimation\n\n  # Statistical modeling\n  sandwich, # Robust variance estimation\n  lmtest, # Hypothesis testing for linear models\n  boot, # Bootstrap methods\n\n  # Visualization extras\n  patchwork, # Combining ggplot2 plots\n  ggridges, # Ridge plots for distribution visualization\n  scales # Better scale formatting\n)\n```\n:::\n\n\n\n## The Scenario: Managing High Blood Pressure\n\nImagine a doctor treating a patient for high blood pressure over several months.\n\n- **Time-Varying Treatment:** The doctor can change the **dosage of blood pressure medication** at each visit. This is a \"time-varying treatment\" because it's not a one-time decision.\n- **Time-Varying Confounder:** The patient's **blood pressure reading** itself. It changes from visit to visit.\n- **Outcome:** The ultimate goal is to prevent a **heart attack**.\n\nHere's where the problem, known as **treatment-confounder feedback**, comes in.\n\n## The Feedback Loop 🔄\n\nThis situation creates a tricky chicken-and-egg loop that makes it very difficult to figure out if the medication is truly working.\n\n1. **Treatment Affects the Confounder:** The medication you take today directly impacts your blood pressure reading at your next visit. If you take a high dose, your blood pressure will likely be lower next month.\n    - Medication Dose (Today) $\\rightarrow$ Blood Pressure (Next Month)\n\n2. **Confounder Affects the Treatment:** When the doctor sees your lower blood pressure next month, they will use that information to decide on your next dose. Seeing a good reading, they might keep the dose the same or even lower it.\n    - Blood Pressure (Next Month) $\\rightarrow$ Medication Dose (Next Month)\n\nThis loop is problematic because the variable we need to \"control for\" (blood pressure) is also something we are trying to change with our treatment. The blood pressure reading is both a **confounder** for the *next* treatment decision and a **mediator** of the *last* treatment's effect.\n\n## Why Standard Statistical Methods Fail\n\nNormally, to isolate a treatment's effect, a statistician would try to \"adjust for\" or \"control for\" the confounder. In this case, that would mean trying to answer the question: \"Holding blood pressure constant, what is the effect of the medication?\"\n\n## This is the Wrong Question to Ask, and here’s why\n\nImagine you're trying to figure out if a new fertilizer makes plants grow taller. The fertilizer works by helping the plant build a stronger stem, which then allows it to grow. The stem's strength is part of the causal pathway.\n\nIf you try to \"control for\" the stem's strength, you are essentially asking: \"For plants with the *exact same* stem strength, which one grew taller?\" This question is nonsensical. You've just eliminated the very mechanism through which the fertilizer works! You've blocked the causal path.\n\nIt's the same with the blood pressure medication. The medication works *by lowering blood pressure*. If we statistically \"hold blood pressure constant,\" we block the main pathway of the drug's effect. Doing so makes the medication look ineffective, even if it's saving lives.\n\n**This is the fundamental challenge**: the confounder isn't just a nuisance variable to be adjusted away; it is a key piece of the causal story that is directly influenced by what we did in the past. Standard methods can't untangle this feedback loop, which is why specialized techniques like Marginal Structural Models (MSMs) were invented.\n\n## How it Works\n\nWe left off with our doctor, who is stuck in a feedback loop: the medication dose affects the patient's blood pressure, and the blood pressure then affects the next medication dose. We can't just \"control for\" blood pressure because that would block the very effect we want to measure.\n\nSo, how do Marginal Structural Models (MSMs) solve this puzzle?\n\nThe big idea is this: **Instead of trying to statistically adjust for blood pressure, we create a new, imaginary version of our dataset where the feedback loop never existed in the first place.**\n\nWe do this using a powerful technique called **Inverse Probability Weighting (IPW)**. Here’s the intuition.\n\n## Creating a \"Fair\" Comparison with Weights\n\nImagine in our study, we have two patients with dangerously high blood pressure.\n\n- **Patient A** is given a high dose of medication. This is the **expected** decision. The doctor saw the high blood pressure and acted accordingly.\n- **Patient B**, for some unusual reason, is given a **low** dose of medication. This is a **surprising** decision. It goes against what the doctor would normally do.\n\nPatient B is incredibly valuable to us. They are a rare example of someone who breaks the feedback loop. They show us what happens when a high-risk person gets a low dose. Because they are so rare and informative, we want to give their outcome **more weight** in our analysis.\n\nConversely, Patient A’s outcome is less informative. They are just one of many high-risk patients who got the expected high dose. So, we give their outcome **less weight**.\n\nMSMs do this systematically for every patient at every visit. Each person is given a statistical \"weight\" based on the treatment they received.\n\n- If the treatment was **surprising** (like getting a low dose despite high blood pressure), the patient gets a **large weight**.\n- If the treatment was **expected** (like getting a high dose for high blood pressure), the patient gets a **small weight**.\n\n## The Magic of the \"Pseudo-Population\"\n\nAfter calculating these weights for everyone, we have essentially created a new, weighted dataset. We call this a **pseudo-population**.\n\nIn this new, imaginary population, something amazing has happened: the link between blood pressure and the medication dose has been statistically erased. It's as if we've created a parallel universe where the doctor made treatment decisions **at random**, without ever looking at the patient's blood pressure readings.\n\nBecause the confounding from the feedback loop is now gone, we have simulated a **perfect randomized controlled trial**.\n\n## The Final, Simple Step\n\nOnce we have this \"fair\" pseudo-population, the final analysis is incredibly simple. We no longer need to worry about adjusting for blood pressure. We can now directly and fairly compare the long-term outcomes (like heart attacks) of patients who followed a strategy of \"always take a high dose\" versus those who followed a strategy of \"always take a low dose.\"\n\nIn short, MSMs solve the feedback problem not by trying to adjust for the time-varying confounder, but by **re-weighting the entire study population to create a new dataset where the confounding doesn't exist.** It's a clever way to simulate the ideal experiment that we couldn't run in real life.\n\n## From a Biased Sample to a Fair Representation\n\nThink about a national political poll. If a pollster only calls people from one state, say California, their results won't represent the entire country. The sample is biased. To fix this, pollsters use weights. If they have too few respondents from Texas, they give each Texan's answer a little more weight. If they have too many from California, they give each Californian's answer a little less weight. By doing this, they create a weighted sample that statistically mirrors the entire country.\n\nThe pseudo-population in an MSM works on the exact same principle.\n\n - **Our Real-World Data (The Biased Sample)**: Our observational study is like the biased poll. It's biased because the doctor's decisions weren't random. Patients with high blood pressure were far more likely to get high-dose medication. The \"surprising\" patients (high blood pressure, low dose) are like the under-sampled Texans—they are rare but crucial.\n - **The Weights (The Correction Factor)**: The Inverse Probability Weights are the correction factors. We give a large weight to the \"surprising\" patients and a small weight to the \"expected\" patients.\n - **The Pseudo-Population (The Fair Representation)**: When we apply these weights, we generate our pseudo-population. This new, imaginary dataset is no longer biased. It now represents a world where the treatment decisions were fair and unbiased.\n\n## What Does \"Statistically Erased\" Mean?\n\nLet's make this concrete. Imagine we look at just the patients in our study who had high blood pressure at their second visit.\n\nIn the REAL data, the table might look like this:\n\n| Patient's Blood Pressure | Medication Dose | Number of Patients |\n| :--- | :--- | :--- |\n| High | High Dose | 90 |\n| High | Low Dose | 10 |\n\nYou can see the bias immediately. For high-risk patients, there's a 90% chance they get a high dose. The link between blood pressure and treatment is strong.\n\nIn the PSEUDO-POPULATION, after weighting, it looks like this:\n\n| Patient's Blood Pressure | Medication Dose | Weighted Number of Patients |\n| :--- | :--- | :--- |\n| High | High Dose | 50 |\n| High | Low Dose | 50 |\n\nThe magic is that the total number of patients is still the same, but their influence has been redistributed. The 10 \"surprising\" patients who got a low dose now have such a large weight that they count for as much as the 90 \"expected\" patients.\n\nWithin the group of high-risk patients, the treatment is now perfectly balanced—50/50. The arrow from \"Blood Pressure\" to \"Medication Dose\" has been statistically erased. We've created a dataset where it appears the doctor just flipped a coin to decide the dose, which is exactly what happens in a randomized controlled trial.\n\nThat's the essence of the pseudo-population: it's a carefully re-weighted version of our real data that mathematically undoes the biases of real-world decision-making, allowing us to ask our causal question fairly.\n\n## Scaffolding the Core Idea: Probability and Its Inverse\n\nAt its heart, the weight is just the number one divided by a probability.\n\n$$\nW = \\frac{1}{\\text{Probability}}\n$$\n\nThe whole point is to give more influence to things that were unlikely to happen, and less influence to things that were likely.\n\n - If an event had a low probability (it was surprising), its inverse is a big number.\n   - Example: Probability = 10% or 0.10. The weight is 1 / 0.10 = 10.\n - If an event had a high probability (it was expected), its inverse is a small number.\n   - Example: Probability = 80% or 0.80. The weight is 1 / 0.80 = 1.25.\n\nThink of it like this: if you find a rare Pokémon card (a low probability event), it's worth a lot. If you find a common one (a high probability event), it's worth very little. The weight represents the \"value\" or \"informativeness\" of an observation.\n\n## Building the Math, Step by Step\n\nLet's get specific. Our goal is to calculate a weight for each person in our study. This weight will depend on the entire sequence of treatments they received over time.\n\n## The Unstabilized Weight ($W_i$)\n\nFirst, let's look at the basic, \"unstabilized\" weight for a single person, whom we'll call person i.\n\nThe formula for the unstabilized weight is:\n\n$$\nW_i = \\frac{1}{\\prod_{k=0}^{K} \\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i,k-1}, \\bar{L}_{i,k}}}\n$$\n\nLet's decode that:\n\n - $A_{i,k}$: The actual treatment person i received at time k.\n - $\\bar{A}_{i,k-1}$: The person's entire history of treatment before time k.\n - $\\bar{L}_{i,k}$: The person's entire history of confounders up to and including time k.\n - $\\Prob{\\dots}$: This is the probability of receiving their actual treatment, given their specific history. We get this from a statistical model (like logistic regression).\n - $\\prod_{k=0}^{K}$: This is the \"product\" symbol. It means we multiply the probabilities from each time point together (from the start of the study, k=0, to the end, $k=K$).\n\n> [!NOTE]\n> In plain English: For each person, we calculate the probability of them getting the treatment they got at each visit, given their past. Then we multiply all those probabilities together. The final weight is just 1 divided by that result.\n\n::: {.callout-tip}\n\n## 🧠 Learning Tip: The Denominator is \"The Story of What Happened\"\n\nThink of the denominator as telling the story of why the doctor made the decisions they did. It's the probability of the observed treatment sequence, fully explained by the patient's entire medical history.\n\n:::\n\n## The Stabilized Weight (SW_i)\n\nUnstabilized weights work, but they can sometimes become huge, making our results unstable. To fix this, we use \"stabilized\" weights, which are much better behaved.\n\nThe formula for the stabilized weight is:\n\n$$\nSW_i = \\prod_{k=0}^{K} \\frac{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}}}{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}, \\bar{L}_{i,k}}}\n$$\n\nThis looks more complex, but it's a simple, brilliant tweak.\n\n - The denominator is the same as before. It's the probability of the treatment given the full history (treatments and confounders).\n - The numerator is new. It's the probability of receiving the treatment given only the past treatment history, ignoring the confounders ($\\bar{L}$).\n\nIn plain English: The stabilized weight is a ratio. For each time point, we ask:\n\n - What was the chance of this treatment, given only past treatments? (Numerator)\n - What was the chance of this treatment, given the full medical history? (Denominator)\n\nWe calculate this fraction for every time point and multiply them all together. This process \"stabilizes\" the weights by preventing them from getting too large.\n\n## A Simple Numerical Example by Hand\n\nLet's use our tiny 5-patient dataset from the lecture. We will calculate the stabilized weight for Patient.\n\nPatient 4's History:\n\n - Time 0: Was Treated ($A_0 = 1$)\n - Time 1: Had a good biomarker result ($L_1=0$) and was Treated ($A_1=1$).\nThe formula for their weight is:\n\n$$\nSW_4 = \\left( \\frac{\\Prob{A_0=1}}{\\Prob{A_0=1}} \\right) \\times \\left( \\frac{\\Prob{A_1=1 \\mid A_0=1}}{\\Prob{A_1=1 \\mid A_0=1, L_1=0}} \\right)\n$$\n\n**Step 1**: Calculate the needed probabilities from the data.\n\n(These are the same probabilities we calculated in the lecture.)\n\n - For the Numerator:\n   - $\\Prob{A_0=1}$: 3 out of 5 patients were treated at Time 0. So, the probability is 0.6.\n   - $\\Prob{A_1=1 \\mid A_0=1}$: Of the 3 patients who got treated at Time 0 (IDs 3, 4, 5), 2 of them were treated at Time 1 (IDs 4, 5). So, the probability is 2/3.\n - For the Denominator:\n   - $\\Prob{A_0=1}$: Same as above, 0.6. (There are no past confounders L_0 to worry about).\n   - $\\Prob{A_1=1 \\mid A_0=1, L_1=0}$: We look only at patients who had $A_0=1$ and $L_1=0$ (IDs 3, 4). Of these 2 patients, 1 was treated at Time 1 (ID 4). So, the probability is 1/2 or 0.5.\n**Step 2**: Plug the numbers into the formula.\n - For Time 0: The fraction is $\\frac{0.6}{0.6} = 1$.\n - For Time 1: The fraction is $\\frac{2/3}{1/2} = \\frac{0.667}{0.5} \\approx 1.33$.\n**Step 3**: Multiply the results together.\n\n$$\nSW_4 = 1 \\times 1.33 = \\mathbf{1.33}\n$$\n\nThis is the stabilized weight for Patient 4. We are giving them slightly more weight in our pseudo-population. Why? Because getting treated at Time 1 was only a 50/50 chance for people with their specific history ($A_0=1$, $L_1=0$). It wasn't a \"sure thing,\" so their outcome is more informative than someone whose treatment was 100% predictable.\n\n::: {.callout-question}\n\n## ❓ Check Your Understanding\n\nNow, try it yourself! Using the same logic and the probabilities from our example, calculate the stabilized weight for Patient.\n\n - Patient's History: Was Untreated ($A_0=0$), had a bad biomarker ($L_1=1$), and was then Treated ($A_1=1$).\n\n<details>\n<summary>Click for a step-by-step solution.</summary>\n1. Set up the formula for Patient #2:\n$$\nSW_2 = \\left( \\frac{\\Prob{A_0=0}}{\\Prob{A_0=0}} \\right) \\times \\left( \\frac{\\Prob{A_1=1 \\mid A_0=0}}{\\Prob{A_1=1 \\mid A_0=0, L_1=1}} \\right)\n$$\n\n2. Find the probabilities:\n * Numerator:\n   * $\\Prob{A_0=0} = 2/5 = 0.4$\n   * $\\Prob{A_1=1 \\mid A_0=0}$: Look at patients with $A_0=0$ (IDs 1, 2). One of them got$ A_1=1$ (ID 2). So, probability = 1/2 or 0.5.\n * Denominator:\n   *$\\Prob{A_0=0} = 0.4$\n   * $\\Prob{A_1=1 \\mid A_0=0, L_1=1}$: Look at patients with $A_0=0$ and $L_1=1$ (only ID 2). That one patient got $A_1=1$. So, probability = 1/1 or 1.0.\n1. Plug and solve:\n$$\nSW_2 = \\left( \\frac{0.4}{0.4} \\right) \\times \\left( \\frac{0.5}{1.0} \\right) = 1 \\times 0.5 = \\mathbf{0.5}\n$$\n\nMeaning: We give Patient #2 less weight. Why? Because their treatment at Time 1 was completely predictable. For every patient with their history, the doctor gave them the treatment. Their outcome is less surprising and thus less informative for breaking the feedback loop.\n</details>\n:::\n\nThis mathematical process of weighting is how we build the pseudo-population. By carefully adjusting the \"influence\" of each person, we create a new, balanced dataset where the link between confounders and treatments is broken, allowing for a fair causal comparison.\n\n## Assumptions\n\nThe mathematical \"magic\" of creating a pseudo-population is powerful, but it's not infallible. It rests on a few critical assumptions about our data and the world. If these assumptions are violated, our weights will be incorrect and our causal conclusions will be biased.\n\nLet's go through the three most important assumptions: *sequential exchangeability*, *positivity*, and *consistency*.\n\n## 1. Sequential Exchangeability (No Unmeasured Confounding Over Time)\n\nThis is the most important and untestable assumption. It's the longitudinal version of the standard \"exchangeability\" or \"ignorability\" assumption we've seen before.\n\n**The Core Idea**: At every point in time, the reason a person gets a particular treatment must be fully explained by their *observed past history*—that is, the data we have in our spreadsheet. There can be no hidden or unmeasured factors that influence the treatment decision.\n\n**Analogy: The All-Knowing Researcher**\nImagine you are the researcher, and you are watching our doctor treat the patient with high blood pressure.\n- **Assumption Holds**: At each visit, the doctor looks at the patient's chart—past blood pressure readings, past medication doses, age, etc.—and makes a decision. As long as you have that same chart (all the same data), you can build an accurate model of the doctor's decision-making. The reason for the treatment is known.\n- **Assumption Violated**: What if the doctor also bases their decision on something you *can't* see? For example, the doctor might notice \"the patient looks especially pale today\" or \"the patient mentioned feeling dizzy.\" If these factors influence the treatment dose but are not recorded in your dataset, you have an **unmeasured confounder**.\n\nWhen this happens, your model for the probability of treatment will be wrong because it's missing a key predictor. The weights you calculate will be incorrect, and the pseudo-population will still be biased.\n\n::: {.callout-important}\n\n## 📌 Sequential Exchangeability\n\nFormally, this means that at any time $k$, the potential outcome $Y^{\\bar{a}}$ is independent of the actual treatment received $A_k$, conditional on the observed past treatment ($\\bar{A}_{k-1}$) and confounder ($\\bar{L}_k$) histories.\n\n$$\nY^{\\bar{a}} \\indep A_k \\mid \\bar{A}_{k-1}, \\bar{L}_k\n$$\n\nThis must hold for all time points $k$. It is a strong assumption that requires deep subject-matter expertise to justify.\n\n:::\n\n## 2. Positivity (Anything Can Happen)\n\nThis is a more practical, and in principle, testable assumption.\n\n**The Core Idea**: For any given patient history, there must be a non-zero probability of receiving *either* treatment. Treatment decisions cannot be deterministic.\n\n**Analogy: The Doctor With No \"Never\" or \"Always\" Rules**\nPositivity is violated if our doctor has a strict, unbreakable rule.\n- **Violation Example**: Imagine the hospital has a rigid policy: \"Any patient whose blood pressure is above 180 mmHg **must** be given the high dose, no exceptions.\"\n- **The Problem**: For this group of very sick patients, the probability of receiving the *low dose* is exactly zero.\n\n**Why This Breaks the Math**: The weight calculation involves dividing by this probability ($\\text{weight} \\approx 1/\\text{probability}$). If the probability is zero, we are trying to divide by zero, which is impossible. The weight becomes infinite, and our analysis fails.\n\n**The Practical Meaning**: We can't learn about the effect of a treatment in a certain type of person if no one in that group ever receives it. To learn what happens to very sick patients under a low-dose regimen, we need at least *some* very sick patients to have actually received the low dose in our study.\n\n## 3. Consistency (What You See Is What You Get)\n\nThis assumption connects the data we observe to the causal effects we want to estimate.\n\n**The Core Idea**: The treatment value in our dataset (e.g., $A=1$ for \"high dose\") must correspond to a clearly defined, real-world intervention. And the outcome we observe for a person who got that intervention must be the same as their potential outcome under that intervention.\n\n**Analogy: A Standardized Recipe**\nImagine \"high dose\" is our treatment.\n- **Assumption Holds**: \"High dose\" means exactly \"50mg of Drug X, taken once daily\" for every patient, every time. The intervention is well-defined.\n- **Assumption Violated**: What if for some patients, \"high dose\" meant \"50mg of Drug X,\" but for others, it meant \"50mg of Drug X *plus* a recommendation to follow a low-salt diet\"? In this case, $A=1$ refers to two different versions of the treatment. If we get a causal effect estimate, we won't know if it's due to the drug, the diet, or the combination.\n\nThe consistency assumption ensures that we are estimating the effect of a specific, non-ambiguous intervention.\n\nThese three assumptions are the theoretical foundation upon which Marginal Structural Models are built. Justifying them is the most important step in any such analysis.\n\n# Violation of Assumptions\n\n## When Sequential Exchangeability Fails (Unmeasured Confounding)\n\nThis is the most difficult violation to handle because you can't definitively prove it with data. It relies on subject-matter knowledge.\n\n**The Problem**: You suspect there are important, unmeasured confounders that influenced both treatment and outcome. Your weights are wrong because the model for the denominator is missing key variables.\n\n**What to Do**:\n\n1. **Think Harder (A Priori)**: The best \"solution\" is prevention. Before the study, consult with domain experts to identify and measure *all* potential confounders. If you are using existing data, try to find proxy variables that might capture some of the unmeasured confounding.\n2. **Conduct a Sensitivity Analysis (Post Hoc)**: Since you can't measure the unmeasured confounder, the next best thing is to quantify how much it could affect your results.\n    - **The Core Idea**: A sensitivity analysis asks, \"How strong would an unmeasured confounder have to be to change my conclusion?\"\n    - **Analogy: Stress-Testing a Bridge**: Imagine you've built a bridge and concluded it's safe. A sensitivity analysis is like putting it in a wind tunnel. You increase the wind speed until the bridge breaks. This tells you its limits. Similarly, we can calculate how strong the associations between an unmeasured confounder, the treatment, and the outcome would need to be to, for example, make our estimated effect of zero.\n    - **The Result**: You can then make a statement like, \"Our finding that the drug is effective would be overturned only if there were an unmeasured confounder that was three times more prevalent in the treated group and increased the risk of the outcome by 300%—a confounder far stronger than any known risk factor.\" This provides a quantitative measure of how robust your conclusion is.\n\n## When Positivity Fails (Deterministic Treatment)\n\nThis violation is often detectable in your data and is a common issue in practice.\n\n**The Problem**: You have subgroups of people who, given their history, had a 0% or 100% chance of getting the treatment. This results in infinite or near-infinite weights.\n\n**How to Diagnose It**:\n- **Examine strata**: Look for combinations of covariates where everyone or no one gets the treatment.\n- **Look at your weights**: This is the most common method. Plot a histogram of your calculated stabilized weights ($SW_i$). If you see a few weights that are dramatically larger than the rest (e.g., weights of 50, 100, or 1000), you have a practical positivity problem.\n\n**What to Do**:\n\n1. **Redefine the Target Population**: If the positivity violation is confined to a specific, often extreme group (e.g., only the healthiest people always refuse treatment), you can restrict your analysis to the population where positivity holds. The cost is that your conclusion is no longer generalizable to the excluded group. You would state, \"Among patients with characteristics X, Y, and Z, the treatment has a causal effect of…\"\n2. **Weight Truncation (or Trimming)**: This is a common pragmatic solution. You set an artificial ceiling on the weights. For example, you might decide to cap all weights at the 99th percentile. Any weight that is calculated to be higher than, say, 20, is manually set to 20. This introduces a small amount of bias (because you are altering the weights) but can drastically reduce variance and make your final estimate more stable. It's a classic bias-variance trade-off.\n\n## When Consistency Fails (Ambiguous Treatment)\n\nThis is a conceptual problem that requires you to go back to the study design and data dictionary.\n\n**The Problem**: The treatment variable in your dataset ($A=1$) does not correspond to a single, well-defined intervention.\n\n**What to Do**:\n\n1. **Specify the Intervention**: The best solution is to be more precise. The causal question should be refined. Instead of asking about the effect of \"physical therapy,\" which could mean many things, you might have to limit your analysis to the effect of \"one weekly 60-minute session with a licensed physical therapist following Protocol X.\"\n2. **Acknowledge Ambiguity**: If the different versions of the treatment cannot be disentangled in the data, you must be transparent about this in your interpretation. You are not estimating the effect of one specific intervention, but rather the effect of a *policy* or *strategy* where different interventions are grouped under one label. Your conclusion becomes, \"We estimated the effect of a policy of prescribing 'high dose' therapy, which may have included different specific treatments across individuals.\"\n\nAddressing these violations is what makes causal inference a thoughtful blend of statistical modeling and scientific reasoning.\n\n# R Lab: Diagnosing and Handling Assumption Violations\n\n## 1. Checking Sequential Exchangeability (No Unmeasured Confounding)\n\nThis first assumption is not checked with code, but with your brain and subject-matter expertise.\n\n  - **The Question You Must Ask**: \"What are the key factors a doctor would consider when deciding to start a patient on AZT at each visit?\"\n  - **Our Simulated World**: In our `hiv_data` simulation, the decision to start AZT (`A0_azt`, `A1_azt`) depended only on the patient's past AZT use and their CD4 counts (`L0_cd4`, `L1_cd4`).\n  - **The Check**: As long as we have measured past AZT use and CD4 count, the assumption holds *in our simulated world*. In a real project, you would need to consult with clinicians to ensure you've measured all the important factors (e.g., viral load, opportunistic infections, patient-reported symptoms) that guide this decision. This check happens *before* you run the models.\n\n## 2. Checking Positivity (Anything Can Happen)\n\nThis is a practical check we perform *after* calculating the weights. The main tool is to inspect the distribution of the stabilized weights. Extreme weights are a tell-tale sign of a positivity problem.\n\n**Step 1: Visualize the Weight Distribution**\n\nA simple histogram is the best place to start.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the data and code from the previous lab if you haven't already\n# (Code to generate hiv_wide and the 'sw' column)\nset.seed(123)\nn_lab <- 500\nid <- 1:n_lab\ncd4_0 <- rnorm(n_lab, 500, 50)\nazt_0_prob <- plogis(-8 + (cd4_0 / 50))\nazt_0 <- rbinom(n_lab, 1, azt_0_prob)\ncd4_1 <- 0.8 * cd4_0 + 20 * azt_0 + rnorm(n_lab, 50, 10)\nazt_1_prob <- plogis(-8 + (cd4_1 / 50) + 0.5 * azt_0)\nazt_1 <- rbinom(n_lab, 1, azt_1_prob)\ncd4_final <- 0.7 * cd4_1 + 40 * azt_1 + 30 * azt_0 + rnorm(n_lab, 100, 20)\nhiv_wide <- data.frame(\n  id,\n  L0_cd4 = cd4_0,\n  A0_azt = azt_0,\n  L1_cd4 = cd4_1,\n  A1_azt = azt_1,\n  Y_cd4 = cd4_final\n)\nden_mod_A0_lab <- glm(A0_azt ~ L0_cd4, data = hiv_wide, family = binomial)\nden_mod_A1_lab <- glm(\n  A1_azt ~ A0_azt + L0_cd4 + L1_cd4,\n  data = hiv_wide,\n  family = binomial\n)\nnum_mod_A0_lab <- glm(A0_azt ~ 1, data = hiv_wide, family = binomial)\nnum_mod_A1_lab <- glm(A1_azt ~ A0_azt, data = hiv_wide, family = binomial)\nhiv_wide$pd0 <- predict(den_mod_A0_lab, type = \"response\")\nhiv_wide$pd1 <- predict(den_mod_A1_lab, type = \"response\")\nhiv_wide$pn0 <- predict(num_mod_A0_lab, type = \"response\")\nhiv_wide$pn1 <- predict(num_mod_A1_lab, type = \"response\")\nhiv_wide$sw0 <- ifelse(\n  hiv_wide$A0_azt == 1,\n  hiv_wide$pn0 / hiv_wide$pd0,\n  (1 - hiv_wide$pn0) / (1 - hiv_wide$pd0)\n)\nhiv_wide$sw1 <- ifelse(\n  hiv_wide$A1_azt == 1,\n  hiv_wide$pn1 / hiv_wide$pd1,\n  (1 - hiv_wide$pn1) / (1 - hiv_wide$pd1)\n)\nhiv_wide$sw <- hiv_wide$sw0 * hiv_wide$sw1\n\n# Now, let's do the check\nhist(\n  hiv_wide$sw,\n  breaks = 50,\n  main = \"Distribution of Stabilized Weights\",\n  xlab = \"Weight Value\",\n  col = \"skyblue\"\n)\n```\n\n::: {.cell-output-display}\n![Distribution of stabilized weights. Note the long right tail indicating some very large weights.](week-06_IP_weighting_MSM-rev3_files/figure-pdf/lab-check-positivity-hist-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Interpretation**: The histogram shows that most weights are clustered between 0 and 5, which is good. However, there's a long \"tail\" to the right, with a few weights stretching out to 20 or more. These extreme values can give a handful of individuals undue influence over our final result. This is a classic sign of a **practical positivity violation**.\n\n**Step 2: Investigate the Extreme Weights**\n\nLet's look at the patients with the largest weights to understand why they are so \"surprising.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get a summary of the weights\nsummary(hiv_wide$sw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.1090  0.8186  0.9046  1.0010  1.0455  7.5413 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Look at the top 5 highest weights\nhiv_wide |>\n  arrange(desc(sw)) |>\n  dplyr::select(id, sw, A0_azt, L0_cd4, A1_azt, L1_cd4) |>\n  head(5)\n```\n\n::: {.cell-output-display}\n\n|  id|       sw| A0_azt|   L0_cd4| A1_azt|   L1_cd4|\n|---:|--------:|------:|--------:|------:|--------:|\n| 461| 7.541282|      0| 543.5982|      0| 486.8970|\n|  97| 5.830924|      0| 609.3666|      1| 531.0576|\n| 196| 4.478538|      1| 599.8607|      0| 550.9249|\n| 456| 3.164712|      1| 366.9539|      1| 374.5297|\n| 493| 2.609303|      0| 564.7042|      1| 516.0066|\n\n:::\n:::\n\n\n**Interpretation**: Look at patient 419. Their weight is 7.54! This person had a very low CD4 count at baseline (`L0_cd4`), yet they were *not* treated with AZT (`A0_azt = 0`). This was a very unlikely event. The model for treatment probability assigned them a very small probability in the denominator, which, when inverted, created a massive weight.\n\n**Step 3: Address the Violation with Weight Truncation**\n\nThe most common solution is to \"truncate\" or \"trim\" the weights. We set a ceiling, and any weight that exceeds this ceiling is brought down to the maximum allowed value. A common practice is to truncate at the 1st and 99th percentiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the 99th percentile of the weights\npercentile_99 <- quantile(hiv_wide$sw, 0.99)\nprint(paste(\"99th percentile for truncation is:\", round(percentile_99, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"99th percentile for truncation is: 2.61\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a new, truncated weight variable\nhiv_wide$sw_trunc <- ifelse(\n  hiv_wide$sw > percentile_99,\n  percentile_99,\n  hiv_wide$sw\n)\n\n# Plot the new distribution\nhist(\n  hiv_wide$sw_trunc,\n  breaks = 50,\n  main = \"Distribution of Truncated Stabilized Weights\",\n  xlab = \"Truncated Weight Value\",\n  col = \"lightgreen\"\n)\n```\n\n::: {.cell-output-display}\n![](week-06_IP_weighting_MSM-rev3_files/figure-pdf/lab-check-positivity-truncate-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Interpretation**: Notice how the new histogram has no extreme tail. We have removed the influence of those few highly unusual individuals. This will make our final model more stable.\n\n**Step 4: Rerun the MSM with the Truncated Weights**\n\nNow we refit our final model, but we use the new `sw_trunc` variable in the `weights` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(geepack) # Make sure geeglm is available\n\nmsm_lab_fit_truncated <- geeglm(\n  Y_cd4 ~ A0_azt + A1_azt,\n  data = hiv_wide,\n  id = id,\n  weights = sw_trunc, # Using the truncated weights\n  corstr = \"independence\"\n)\n\nsummary(msm_lab_fit_truncated)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ngeeglm(formula = Y_cd4 ~ A0_azt + A1_azt, data = hiv_wide, weights = sw_trunc, \n    id = id, corstr = \"independence\")\n\n Coefficients:\n            Estimate Std.err    Wald Pr(>|W|)    \n(Intercept)  409.957   5.427 5706.10   <2e-16 ***\nA0_azt        46.617   5.601   69.28   <2e-16 ***\nA1_azt        45.194   4.657   94.16   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation structure = independence \nEstimated Scale Parameters:\n\n            Estimate Std.err\n(Intercept)     1135   82.51\nNumber of clusters:   500  Maximum cluster size: 1 \n```\n\n\n:::\n:::\n\n\n**The Takeaway**: Compare these results to the ones from the original model. The coefficient estimates may change slightly—this is the bias we introduce by trimming—but the standard errors will often be smaller, reflecting a more stable and precise estimate. This is the **bias-variance trade-off** in action.\n\n## 3. Checking Consistency (Unambiguous Treatment)\n\nLike exchangeability, this is a conceptual check.\n\n  - **The Question You Must Ask**: \"Does `A0_azt = 1` mean the same thing for everyone?\"\n  - **The Check**: This requires you to understand the study protocol. If `A0_azt = 1` could mean a 50mg dose for some patients and a 100mg dose for others, or if some also received adherence counseling, then the consistency assumption is violated. Your analysis should be limited to the specific, well-defined treatment that you are interested in.\n\nBy systematically walking through these checks, you can build confidence in the validity of your Marginal Structural Model and produce more robust and defensible causal estimates.\n\n# Appendix\n\nLet's break down the rationale and math behind stabilized weights in detail. The core idea is to fix a major practical problem with the simpler, unstabilized weights: their potential for extreme instability.\n\n## The Rationale: Why \"Stabilize\" in the First Place?\n\nThe simpler, \"unstabilized\" weight for a person is calculated as $W_i = 1 / \\Prob{\\text{treatment} | \\text{full history}}$. This weight does its job of creating a pseudo-population where confounding is removed. However, it can suffer from a serious statistical problem: **high variance**.\n\n**The Problem of Extreme Weights**\n\nImagine a patient who is very healthy, and for healthy patients, the probability of receiving a risky experimental drug is extremely low, say 1 in 1000 ($\\Prob{A=1 | \\text{history}} = 0.001$). If this patient, against all odds, *does* receive the drug, their unstabilized weight would be:\n\n$W_i = 1 / 0.001 = 1000$\n\nThis means that in our analysis, this single individual has the same influence as 1000 other people. If their outcome is unusual, they alone could dramatically swing the entire study's conclusion. This makes our results highly **unstable** and sensitive to a few rare individuals. Our estimate might be unbiased on average, but its variance would be huge, leading to very wide and unreliable confidence intervals.\n\n**The Goal of Stabilization**: The goal is to create a new set of weights that still correctly adjusts for confounding but doesn't have this extreme variance. We want to rein in these massive weights without losing the crucial adjustment they provide.\n\n## The Intuition: How the Numerator Fixes the Problem\n\nThe stabilized weight formula accomplishes this with a clever tweak:\n\n$$\nSW_i = \\prod_{k=0}^{K} \\frac{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}} \\text{ (The Numerator)}}{\\Prob{A_k=A_{i,k} \\mid \\bar{A}_{i, k-1}, \\bar{L}_{i,k}} \\text{ (The Denominator)}}\n$$\n\nLet's focus on the role of the new numerator.\n\n- **The Denominator** is the probability of treatment for someone with a *specific* history (e.g., a 62-year-old male with low blood pressure). This can be very small.\n- **The Numerator** is the probability of treatment based *only* on past treatments, averaged over all possible confounder values. It represents the overall proportion of people who received that treatment at that time. This probability is generally not extreme.\n\nThe stabilized weight, therefore, compares the **patient-specific probability** (denominator) to the **overall average probability** (numerator).\n\nThe numerator acts as a **moderating factor**. Instead of just inverting the denominator (which can lead to an explosion), we are scaling it relative to a more stable, average probability. This keeps the weights in a much more reasonable range, reducing their variance and making our final estimate more stable and precise.\n\n## Simple Numerical Example: Unstabilized vs. Stabilized\n\nLet's make this concrete with a simple, one-time treatment study.\n\n**Scenario**: We're testing a new drug ($A=1$) against a placebo ($A=0$). The key confounder ($L$) is the severity of the disease: `Mild` ($L=0$) or `Severe` ($L=1$). Doctors are more likely to give the drug to severe patients.\n\n**Our Observed Data (200 Patients Total):**\n\n| Severity (L) | Treatment (A) | Number of Patients |\n|:---|:---|:---|\n| Mild ($L=0$) | Placebo ($A=0$) | 90 |\n| Mild ($L=0$) | Drug ($A=1$) | 10 |\n| Severe ($L=1$) | Placebo ($A=0$) | 20 |\n| Severe ($L=1$) | Drug ($A=1$) | 80 |\n\nLet's focus on one specific person: **A mild patient who received the drug.** This is a \"surprising\" event.\n\n### Step 1: Calculate the Unstabilized Weight ($W_i$)\n\nThe formula is $W_i = 1 / \\Prob{A=1 \\mid L=0}$.\n\n- $\\Prob{A=1 \\mid L=0} = \\frac{\\text{Mild patients who got Drug}}{\\text{All Mild patients}} = \\frac{10}{90 + 10} = 0.10$\n- $W_i = 1 / 0.10 = \\mathbf{10}$\n\nThis person has the weight of 10 people in the analysis.\n\n### Step 2: Calculate the Stabilized Weight ($SW_i$)\n\nThe formula is $SW_i = \\Prob{A=1} / \\Prob{A=1 \\mid L=0}$.\n\n- **Denominator**: We already have this: $\\Prob{A=1 \\mid L=0} = \\mathbf{0.10}$.\n- **Numerator**: We need the overall probability of getting the drug, regardless of severity.\n    - $\\Prob{A=1} = \\frac{\\text{Total patients who got Drug}}{\\text{All patients}} = \\frac{10 + 80}{90 + 10 + 20 + 80} = \\frac{90}{200} = \\mathbf{0.45}$\n- **Calculate the weight**:\n    - $SW_i = \\frac{\\text{Numerator}}{\\text{Denominator}} = \\frac{0.45}{0.10} = \\mathbf{4.5}$\n\n### The Comparison\n\n| Weight Type | Calculation | Result |\n|:---|:---|:---|\n| Unstabilized | $1 / 0.10$ | **10** |\n| Stabilized | $0.45 / 0.10$ | **4.5** |\n\nBoth weights correctly identify this person as being \"surprising\" and give them more influence. But the stabilized weight is much less extreme. It has been moderated by the fact that getting the drug wasn't *that* rare overall (45% of all patients got it). The weight is pulled back from 10 to a more stable 4.5.\n\nBy applying this logic to every person, we get a full set of stabilized weights that successfully adjust for confounding while having much lower variance, leading to more precise and reliable causal effect estimates.\n\n## More Insight\n\n## 1) Intuition: what the Numerator is Doing (and why it helps)\n\n- **Unstabilized weights** upweight people who received a treatment that was **unlikely given their full history** (past treatments + covariates). That breaks the dependence between covariates and treatment, but the weights can explode when those probabilities are tiny.\n- **Stabilized weights** add a numerator that is the **simpler** probability of the observed treatment given **only past treatment**. This:\n  - **Cancels the worst denominators** just enough to shrink extreme weights.\n  - **Preserves** the **marginal** (over covariates) distribution of treatment *given past treatment*, which keeps the weighted sample looking like the original sample in terms of how often each treatment was used.\n  - **Keeps the same causal target.** The numerator does **not** reintroduce confounding; it’s “harmless” for identification but **helpful** for variance.\n\nRule of thumb: the numerator reintroduces the right amount of randomness we had in treatment **before** we looked at covariates, so weights stay near 1 instead of going wild.\n\n---\n\n## 2) Definitions (one time point First, then many)\n\n### One time point (for clarity)\n\n- **Unstabilized weight** for person $i$:\n\n$$\nW_i \\;=\\; \\frac{1}{\\Pr(A_i=a_i \\mid L_i)}\n$$\n\n- **Stabilized weight** for person $i$:\n\n$$\nSW_i \\;=\\; \\frac{\\Pr(A_i=a_i)}{\\Pr(A_i=a_i \\mid L_i)}\n$$\n\nHere $A$ is treatment, $L$ are confounders.\n\n### Multiple time Points $k=0,\\dots,K$\n\n- **Unstabilized**:\n\n$$\nW_i \\;=\\; \\prod_{k=0}^{K} \\frac{1}{\\Pr(A_{ik}=a_{ik}\\mid \\bar A_{i,k-1}, \\bar L_{ik})}\n$$\n\n- **Stabilized** (your formula):\n\n$$\nSW_i \\;=\\; \\prod_{k=0}^{K} \n  \\frac{ \\Pr(A_{ik}=a_{ik} \\mid \\bar A_{i,k-1}) }\n       { \\Pr(A_{ik}=a_{ik} \\mid \\bar A_{i,k-1}, \\bar L_{ik}) }\n$$\n\nThe **denominator** is the same as before (the “hard” assignment model that depends on confounders). The **numerator** is a “reduced” model (ignores $L$).\n\n---\n\n## 3) Why Stabilized Weights Keep the Target and Reduce variance (a Clean factorization)\n\nLet the observed data density factorize by time as usual:\n\n$$\nf(\\text{data}) \\;=\\; f(L_0)\\;\n\n \\prod_{k=0}^{K} f(A_k \\mid \\bar A_{k-1}, \\bar L_k)\\, f(L_{k+1}\\mid \\bar A_k, \\bar L_k).\n$$\n\nIf we **reweight** each record by\n\n$$\nSW \\;=\\; \\prod_{k=0}^{K} \\frac{ f(A_k \\mid \\bar A_{k-1}) }{ f(A_k \\mid \\bar A_{k-1}, \\bar L_k) },\n$$\n\nthe **weighted** (pseudo-)density is proportional to\n\n$$\nSW \\cdot f(\\text{data}) \\;\\propto\\; f(L_0)\\; \\prod_{k=0}^{K}\n\n\\underbrace{f(A_k \\mid \\bar A_{k-1})}_{\\text{depends on past }A\\text{ only}}\n\n\\; f(L_{k+1}\\mid \\bar A_k, \\bar L_k).\n$$\n\n**Two key consequences:**\n\n1. In the pseudo-population, **treatment no longer depends on $\\bar L_k$** at time $k$ given $\\bar A_{k-1}$. That’s exactly the “as-if randomized given past $A$” property we need.\n2. The **marginal distribution of treatment given past treatment** is preserved (because those $f(A_k\\mid \\bar A_{k-1})$ are now the treatment factors in the pseudo-density). This stabilization is what keeps weights moderate and the sample “familiar.”\n\nBy contrast, **unstabilized** weights replace the treatment factor with a constant (intuitively, “flat” assignment), which can make the weighted sample look very unlike the original and push weights to extremes.\n\nA related perspective: **unstabilized** IPTW is a Horvitz–Thompson–type estimator (unbiased but high variance); **stabilized** IPTW acts like a Hájek normalization (same target, usually **smaller variance**, and weights closer to 1).\n\n---\n\n## 4) A Napkin-size Numeric Example (one time point)\n\nSuppose 1,000 patients:\n\n- 800 have **low BP** ($L=0$), 200 have **high BP** ($L=1$).\n- Doctors treat **20%** of low-BP, **80%** of high-BP.\n\nSo:\n\n- $\\Pr(A=1\\mid L=0)=0.20$, $\\Pr(A=1\\mid L=1)=0.80$.\n- Overall $\\Pr(A=1)= (160+160)/1000 = 0.32$, $\\Pr(A=0)=0.68$.\n\n## Unstabilized Weights\n\n- Treated low-BP: weight $=1/0.20=5$ (big)\n- Treated high-BP: weight $=1/0.80=1.25$\n- Untreated low-BP: weight $=1/0.80=1.25$\n- Untreated high-BP: weight $=1/0.20=5$ (big)\n\n**Problem:** Those 5’s are heavy. Any analysis becomes noisy and sensitive to a few people.\n\n## Stabilized Weights\n\n- Treated low-BP: $SW = 0.32/0.20 = 1.60$\n- Treated high-BP: $SW = 0.32/0.80 = 0.40$\n- Untreated low-BP: $SW = 0.68/0.80 = 0.85$\n- Untreated high-BP: $SW = 0.68/0.20 = 3.40$\n\n**Now the largest weight is 3.4, not 5**, and most weights are near 1. You still erase the BP→Treatment link in the weighted data, but with **less variance**.\n\n(You can check: after weighting, the treated fraction in low-BP and high-BP groups both become 0.32—i.e., treatment is independent of BP in the pseudo-population.)\n\n# 5) What to Remember in Practice\n\n- **Same target, better stability.** Stabilized weights identify the same MSM parameters but usually with smaller variance.\n- **Mean near 1.** With correctly specified models, $\\mathbb{E}(SW)\\approx 1$. Analysts often also **normalize** weights to have mean 1 in the sample (a separate, harmless step).\n- **Numerator model is simple by design.** It conditions only on **past treatments**; do **not** include covariates affected by prior treatment there.\n- **Still need overlap.** If some histories virtually never get a particular treatment (positivity violation), even stabilized weights can be large—consider truncation, coarsening, or redefining the estimand/support.\n\n# 6) Two-time Extension (quick peek)\n\nAt $k=0,1$,\n\n$$\nSW_i \\;=\\; \n\n\\frac{\\Pr(A_{i0}\\mid \\emptyset)}{\\Pr(A_{i0}\\mid L_{i0})}\n\n\\;\\times\\;\n\n\\frac{\\Pr(A_{i1}\\mid A_{i0})}{\\Pr(A_{i1}\\mid A_{i0}, L_{i0}, L_{i1})}.\n$$\n\n- The first factor stabilizes baseline treatment.\n- The second factor stabilizes the follow-up decision.\nIn the weighted world, **each** decision behaves as if randomized **given past treatment**, so you can fit a **marginal** model of the outcome on the treatment history (your MSM) without conditioning on the time-varying confounders that are also mediators.\n\n## One-line Recap\n\nStabilized weights keep the **identification** benefits of IPTW but **temper** extreme weights by reintroducing the right marginal treatment probabilities—so your pseudo-population looks randomized **and** your estimates are more stable.\n\n# Link to Horvitz–Thompson and Hájek Estimators\n\n## Big Idea\n\n- **Unstabilized IPTW** estimates a (counterfactual) mean by **adding up outcomes with inverse probabilities** and then dividing by **N**. That’s the **Horvitz–Thompson (HT)** style: unbiased if the treatment model is correct, but can be **high variance** when some probabilities are small (huge weights).\n- **Stabilized IPTW** (or **Hájek** style) estimates the same mean by **ratio**: add up “weighted outcomes” and **divide by the sum of weights** (not by N). This **self-normalizes** the weights, yielding **smaller variance** (typically) with at most tiny finite-sample bias; it’s consistent for the same target.\n\nThink of **HT** as “plain importance sampling” and **Hájek** (or stabilized) as “self-normalized importance sampling.”\n\n---\n\n# One-time-point Setup (to Anchor intuition)\n\nWe want the mean outcome **if everyone were treated**, $\\mu(1)=\\mathbb{E}[Y^{1}]$.\n\nLet $A\\in\\{0,1\\}$ be treatment, $e(X)=\\Pr(A=1\\mid X)$ the (true) propensity, and we only observe $Y$ when $A=1$.\n\n## Unstabilized IPTW (Horvitz–Thompson)\n\n$$\n\\widehat{\\mu}_{\\text{HT}}(1)=\\frac{1}{N}\\sum_{i=1}^N \\frac{\\mathbb{I}(A_i=1)\\,Y_i}{e(X_i)}.\n$$\n\n- **Unbiased** (if $e(\\cdot)$ is correct).\n- But if some $e(X_i)$ are small, terms $1/e(X_i)$ are huge → **high variance**.\n\n## Hájek (ratio) Form\n\n$$\n\\widehat{\\mu}_{\\text{H}}(1)=\n\\frac{\\sum_{i=1}^N \\frac{\\mathbb{I}(A_i=1)\\,Y_i}{e(X_i)}}\n     {\\sum_{i=1}^N \\frac{\\mathbb{I}(A_i=1)}{e(X_i)}}.\n$$\n\n- Same target; **weights are self-normalized** by $\\sum 1/e$.\n- Typically **smaller variance**; slight finite-sample bias that vanishes as $N\\to\\infty$.\n\n## “Stabilized” Weights Viewpoint\n\nDefine **stabilized weights** for treated units as\n\n$$\nSW_i=\\frac{\\Pr(A=1)}{e(X_i)} \\quad \\text{if } A_i=1,\\quad (0 \\text{ otherwise}).\n$$\n\nThen the **ratio estimator with stabilized weights** is\n\n$$\n\\frac{\\sum SW_i Y_i}{\\sum SW_i}\n=\\frac{\\Pr(A=1)\\sum \\tfrac{\\mathbb{I}(A_i=1)Y_i}{e(X_i)}}\n       {\\Pr(A=1)\\sum \\tfrac{\\mathbb{I}(A_i=1)}{e(X_i)}}\n=\\widehat{\\mu}_{\\text{H}}(1).\n$$\n\nSo, **stabilized IPTW + divide by sum of weights = Hájek**.\n\n(Using unstabilized weights but dividing by their sum gives the same ratio.)\n\n---\n\n# Tiny Numeric Example (you Can Do by hand)\n\nSuppose $N=6$. Three treated, three untreated.\n\n| i | $A_i$ | $Y_i$ (only if $A_i=1$) | $e(X_i)=\\Pr(A=1\\mid X_i)$ |\n|--:|:-------:|:----------------------------:|:----------------------------:|\n| 1 | 1       | 2                            | 0.90                         |\n| 2 | 1       | 1                            | 0.80                         |\n| 3 | 1       | 3                            | 0.20                         |\n| 4 | 0       | —                            | 0.90                         |\n| 5 | 0       | —                            | 0.50                         |\n| 6 | 0       | —                            | 0.10                         |\n\nOverall treated fraction $\\Pr(A=1)=3/6=0.5$.\n\n**HT (unstabilized)**\n\n$$\n\\widehat{\\mu}_{\\text{HT}}(1)=\\frac{1}{6}\\Big(\\frac{2}{0.9}+\\frac{1}{0.8}+\\frac{3}{0.2}\\Big)\n=\\frac{1}{6}(2.2222+1.25+15)=3.0787.\n$$\n\nNote the huge impact of the rare treated with $e=0.2$ (weight $=5$).\n\n**Hájek (ratio)**\n\n$$\n\\widehat{\\mu}_{\\text{H}}(1)=\n\\frac{2/0.9+1/0.8+3/0.2}{1/0.9+1/0.8+1/0.2}\n=\\frac{18.4722}{7.3611}=2.509.\n$$\n\nSame target, much **more stable** (the large weight is tempered by the denominator).\n\n**Stabilized IPTW (same as Hájek)**\nUse $SW_i=0.5/e(X_i)$ for treated:\n- Numerator: $0.5\\,(2/0.9+1/0.8+3/0.2)=9.2361$\n- Denominator: $0.5\\,(1/0.9+1/0.8+1/0.2)=3.6806$\n- Ratio $=9.2361/3.6806=2.509$ (identical to Hájek).\n\n**Takeaway:** HT is “unbiased but jumpy”; Hájek/stabilized is “same target, usually smaller variance.”\n\n---\n\n# Why variance Shrinks (plain English)\n\n- HT’s total weight $\\sum w_i$ can fluctuate wildly sample-to-sample (especially when some $e(X)$ are tiny), amplifying noise.\n- Hájek (or stabilized) **pins down the total weight** (by dividing by $\\sum w_i$), removing one big source of randomness. That’s the same benefit you get from self-normalized importance sampling.\n\n---\n\n# Many time Points (longitudinal)\n\nAt visits $k=0,\\dots,K$:\n\n- **Unstabilized IPTW (HT-like):**\n\n$$\nW_i=\\prod_{k=0}^K \\frac{1}{\\Pr(A_{ik}=a_{ik}\\mid \\bar A_{i,k-1},\\bar L_{ik})}.\n$$\n\n- **Stabilized IPTW (Hájek-like):**\n\n$$\nSW_{i}= \\prod_{k=0}^{K} \\frac{\\Pr(A_{ik} = a_{ik}\\mid \\bar A_{i,k-1})}{\\Pr(A_{ik} = a_{ik}\\mid \\bar A_{i,k-1},\\bar{L}_{ik})}.\n$$\n\nYou then estimate means or fit an MSM via **weighted regression**. The numerator factors preserve the **marginal** treatment process (given past $A$) and act like a built-in normalization → **weights closer to 1** and **smaller variance**.\n\n---\n\n# Practical Tips\n\n- When estimating **means**: prefer the **ratio form** (divide by $\\sum w_i$); with stabilized weights this happens automatically.\n- When fitting **MSMs**: use stabilized weights, robust (sandwich) SEs, and check the **weight distribution** (truncate extremes if needed).\n- Always assess **overlap (positivity)**—no weighting trick can recover information the data don’t contain.\n\n**Rule of thumb:**\nHT = “pure IPW, unbiased but noisy.”\nHájek/stabilized = “self-normalized IPW, same target, usually tighter.”\n\n## The Bridge: From Logistic Regression (Log-Odds) to IPW (Probabilities)\n\nOur goal is to calculate the stabilized weight, which requires the probability of treatment, $\\Prob{A=1 \\mid \\text{History}}$. But how do we get a number for that probability for each person? We need to model it.\n\nThe most common tool for modeling a binary outcome (like treatment vs. no treatment) is **logistic regression**.\n\n### Step 1: The Logistic Model and Its Native Language (Log-Odds)\n\nA logistic regression model does not predict probability directly. Instead, it models the **logarithm of the odds** (the \"logit\") as a linear function of the predictors.\n\nWhen we fit a model for our treatment $A$ based on confounders $L$:\n\n`glm(A ~ L1 + L2, family = binomial)`\n\nThe underlying equation R is solving is:\n\n$\\ln\\left(\\frac{\\Prob{A=1 \\mid L}}{1 - \\Prob{A=1 \\mid L}}\\right) = \\beta_0 + \\beta_1 L_1 + \\beta_2 L_2$\n\nNotice the left side is the **log-odds**. This is the native language of a logistic model.\n\n### Step 2: Translating from Log-Odds to the Probability We Need\n\nFor our IPW formula, we don't want log-odds or odds; we need the clean probability, $p$. So, we must translate the model's output back into the language of probability. This is a two-step algebraic conversion:\n\n1. **From Log-Odds to Odds**: We exponentiate both sides to undo the natural log ($\\ln$).\n    $\\text{Odds} = e^{(\\beta_0 + \\beta_1 L_1 + \\beta_2 L_2)}$\n\n2. **From Odds to Probability**: We use the standard conversion formula.\n    $\\text{Probability (p)} = \\frac{\\text{Odds}}{1 + \\text{Odds}}$\n\nThis final probability is exactly what we plug into our weight formula.\n\n### Step 3: Putting It Together in R\n\nFortunately, R's `predict()` function handles this translation for us automatically. When you use `predict()` on a `glm` object, you can specify the `type` of output you want.\n\nLet's use our `den_mod_A0_lab` model from the lab, which predicted AZT at time 0 based on the baseline CD4 count (`L0_cd4`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We need to run the code from the previous lab to have the model object\nset.seed(123)\nn_lab <- 500\nid <- 1:n_lab\ncd4_0 <- rnorm(n_lab, 500, 50)\nazt_0_prob <- plogis(-8 + (cd4_0 / 50))\nazt_0 <- rbinom(n_lab, 1, azt_0_prob)\nhiv_wide_demo <- data.frame(id, L0_cd4 = cd4_0, A0_azt = azt_0)\nden_mod_A0_lab <- glm(A0_azt ~ L0_cd4, data = hiv_wide_demo, family = binomial)\n\n# Predict the LOG-ODDS (the model's native output)\nlog_odds <- predict(den_mod_A0_lab, type = \"link\")\n\n# Predict the PROBABILITY (what we need for IPW)\nprobability <- predict(den_mod_A0_lab, type = \"response\")\n\n# Let's look at the first 5 predictions\ndata.frame(\n  Log_Odds = head(log_odds),\n  Probability = head(probability)\n)\n```\n\n::: {.cell-output-display}\n\n| Log_Odds| Probability|\n|--------:|-----------:|\n|    1.663|      0.8406|\n|    1.966|      0.8772|\n|    3.608|      0.9736|\n|    2.242|      0.9040|\n|    2.296|      0.9086|\n|    3.752|      0.9771|\n\n:::\n\n```{.r .cell-code}\n# You can prove they are the same by converting the log-odds manually\nmanual_probability <- exp(log_odds) / (1 + exp(log_odds))\nall.equal(probability, manual_probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n**The Workflow in Practice:**\n\n1. You build a logistic model for the denominator (`glm(A ~ L, …)`).\n2. You build another logistic model for the numerator (`glm(A ~ …)`).\n3. You use `predict(…, type = \"response\")` on both models to get the estimated probabilities for every person.\n4. You plug these predicted probabilities directly into the stabilized weight formula: `sw = (p_numerator) / (p_denominator)`.\n\nSo, your intuition about odds was spot-on—they are working under the hood inside the `glm` function. But for the IPW calculation itself, we use the final translated probability.\n\n## G-Computation vs. MSMs (IPW): A Tale of Two Models\n\nInstead of re-weighting the population, G-computation works by **simulating** the outcomes for the entire population under different, specific treatment strategies.\n\nThe most fundamental difference between these two methods is the model they rely on.\n\n| Feature            | **MSM (via IPW)**                                                             | **G-Computation**                                                                           |\n| :----------------- | :---------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------ |\n| **Core Idea**      | **Weighting:** Create a pseudo-population where confounding is broken.        | **Simulation:** Predict the outcome for everyone under different treatment rules.           |\n| **Required Model** | A model for the **treatment** assignment: $\\Prob{A \\mid L}$                   | A model for the **outcome**: $\\E{Y \\mid A, L}$                                              |\n| **Key Strength**   | Doesn't require correctly modeling complex interactions in the outcome model. | More stable when you have positivity problems (i.e., near-zero probabilities of treatment). |\n| **Key Weakness**   | Very sensitive to positivity violations (can result in extreme weights).      | Very sensitive to getting the outcome model wrong, especially with many confounders.        |\n\n## The G-Computation Recipe 🍳\n\nG-computation follows a simple and intuitive three-step process to directly estimate the mean potential outcome, $\\E{Y^a}$.\n\n### Step 1: Fit a Model for the Outcome\n\nFirst, we ignore the weights entirely. We fit one, rich regression model that predicts the final outcome using both the treatments and the full confounder history as predictors. This is often called the \"Q-model\".\n\n`Outcome ~ Treatment_Time_0 + Treatment_Time_1 + Confounder_Time_0 + Confounder_Time_1 …`\n\nIt's crucial that this model is specified correctly. Any important interactions between the treatments and confounders must be included.\n\n### Step 2: Simulate Potential Outcomes under Intervention\n\nThis is the \"simulation\" or \"g-formula\" step. We use our model to play God with the dataset.\n\n1. **Copy your dataset twice.**\n2. In **Copy A**, you manually set the treatment variables for *every single person* to the first strategy. For example, to find the outcome if everyone had been treated at both time points, you would set `A0 = 1` and `A1 = 1` for all rows.\n3. In **Copy B**, you set the treatment variables for *every single person* to the comparison strategy (e.g., `A0 = 0` and `A1 = 0`).\n4. Use the model from Step 1 to **predict the outcome** for all rows in both of these modified datasets. The predictions from Copy A are the estimated potential outcomes $\\hat{Y}^{\\bar{a}=(1,1)}$, and the predictions from Copy B are $\\hat{Y}^{\\bar{a}=(0,0)}$.\n\n### Step 3: Average and Compare\n\nThe final step is straightforward:\n\n1. Calculate the **average** of all the predicted outcomes in Copy A. This is your estimate of the mean outcome if everyone had followed the \"always treat\" strategy, $\\Ehat{Y^{\\bar{a}=(1,1)}}$.\n2. Calculate the **average** of all the predicted outcomes in Copy B. This is your estimate of the mean outcome if everyone had followed the \"never treat\" strategy, $\\Ehat{Y^{\\bar{a}=(0,0)}}$.\n3. The causal effect is the difference between these two averages.\n\n## G-Computation in R\n\nLet's implement this recipe using our `hiv_wide` dataset. Our goal is to estimate the effect of the strategy \"always take AZT\" (`A0_azt=1`, `A1_azt=1`) versus \"never take AZT\" (`A0_azt=0`, `A1_azt=0`).\n\n### Step 1: Fit the Outcome Model (the \"Q-model\")\n\nWe regress the final CD4 count on the full treatment and confounder history.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We are using the hiv_wide data from the previous examples\nq_model <- lm(Y_cd4 ~ A0_azt + A1_azt + L0_cd4 + L1_cd4, data = hiv_wide)\n\nsummary(q_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y_cd4 ~ A0_azt + A1_azt + L0_cd4 + L1_cd4, data = hiv_wide)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-63.01 -13.27  -0.55  15.93  62.73 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 107.9458    10.6071   10.18   <2e-16 ***\nA0_azt       30.4781     3.3586    9.07   <2e-16 ***\nA1_azt       39.1182     2.5901   15.10   <2e-16 ***\nL0_cd4       -0.1361     0.0753   -1.81    0.071 .  \nL1_cd4        0.8318     0.0913    9.11   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.5 on 495 degrees of freedom\nMultiple R-squared:  0.806,\tAdjusted R-squared:  0.805 \nF-statistic:  515 on 4 and 495 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\n### Step 2: Create Intervened-Upon Datasets and Predict\n\nWe create two copies and manually set the treatment variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Copy the dataset for the \"Always Treat\" scenario\nd_always_treat <- hiv_wide\nd_always_treat$A0_azt <- 1\nd_always_treat$A1_azt <- 1\n\n# Copy the dataset for the \"Never Treat\" scenario\nd_never_treat <- hiv_wide\nd_never_treat$A0_azt <- 0\nd_never_treat$A1_azt <- 0\n\n# Predict potential outcomes for everyone under both scenarios\nhiv_wide$y_potential_always <- predict(q_model, newdata = d_always_treat)\nhiv_wide$y_potential_never <- predict(q_model, newdata = d_never_treat)\n\n# Look at the results for a few patients\nhiv_wide |>\n  dplyr::select(id, Y_cd4, y_potential_always, y_potential_never) |>\n  head()\n```\n\n::: {.cell-output-display}\n\n| id| Y_cd4| y_potential_always| y_potential_never|\n|--:|-----:|------------------:|-----------------:|\n|  1| 437.7|              498.4|             428.8|\n|  2| 485.6|              493.4|             423.8|\n|  3| 528.2|              545.9|             476.4|\n|  4| 515.0|              504.1|             434.5|\n|  5| 523.7|              502.3|             432.7|\n|  6| 588.7|              544.8|             475.2|\n\n:::\n:::\n\n\n### Step 3: Average and Compare\n\nNow we just take the mean of those two new potential outcome columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate the mean potential outcome under \"Always Treat\"\nmean_y_always <- mean(hiv_wide$y_potential_always)\nprint(paste(\"E[Y | Always Treat] =\", round(mean_y_always, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"E[Y | Always Treat] = 499.45\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Estimate the mean potential outcome under \"Never Treat\"\nmean_y_never <- mean(hiv_wide$y_potential_never)\nprint(paste(\"E[Y | Never Treat] =\", round(mean_y_never, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"E[Y | Never Treat] = 429.85\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Estimate the Average Causal Effect (ACE)\nace_gcomp <- mean_y_always - mean_y_never\nprint(paste(\"Average Causal Effect (ACE) =\", round(ace_gcomp, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Average Causal Effect (ACE) = 69.6\"\n```\n\n\n:::\n:::\n\n\nThe estimated average causal effect of this treatment strategy is an increase of 69.6 CD4 points, which is very close to the answer we got with the MSM/IPW approach.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}