{
  "hash": "a45af3588b8b55c32c8429300c623de1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Instrumental Variables (IV) Estimation\"\n---\n\n## Overview\n\nInstrumental Variables (IV) represents one of the most powerful yet challenging methods in causal inference. When we cannot conduct a randomized experiment and face the dreaded problem of **unobserved confounding**, IV offers a potential path forward by exploiting \"natural experiments\" in observational data. This module introduces the theoretical foundations, assumptions, estimation methods, and practical implementation of instrumental variables, with particular emphasis on understanding what IV can and cannot identify.\n\n## Learning Objectives\n\nBy the end of this module, students will be able to:\n\n1. **Explain** the three core assumptions of instrumental variables (relevance, exclusion restriction, exchangeability) in both technical and intuitive terms\n2. **Identify** plausible instrumental variables in real-world research scenarios and critically evaluate their validity\n3. **Implement** IV estimation using both manual calculations and R packages (`ivreg`, `dagitty`, `ggdag`)\n4. **Interpret** IV estimates as Local Average Treatment Effects (LATE) rather than population average treatment effects (ATE)\n5. **Diagnose** common IV problems including weak instruments, exclusion restriction violations, and heterogeneous treatment effects\n6. **Compare** IV results with OLS estimates and explain why they differ in the presence of unobserved confounding\n7. **Apply** IV methods to simulated and real datasets with appropriate caveats about external validity\n\n## R Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  \"dagitty\",\n  \"ggplot2\",\n  \"ggdag\",\n  \"tidyverse\",\n  \"ggpubr\",\n  \"ivreg\",\n  \"stargazer\",\n  \"gridExtra\",\n  \"AER\"\n)\n\nggplot2::theme_set(ggpubr::theme_pubr())\n```\n:::\n\n\n## 1 Comprehensive Topic Explanation\n\n### The Fundamental Problem of Unobserved Confounding\n\nIn many real-world scenarios, we cannot assume that all confounders have been measured and controlled for. Traditional methods like regression adjustment, matching, or weighting fail when important confounders remain unobserved because they cannot block all backdoor paths between treatment and outcome [@hernan2020causalwhatif].\n\nConsider these classic examples where unobserved confounding is likely:\n\n- **Education and earnings**: Unmeasured ability affects both schooling decisions and future income\n- **Hospital quality and patient outcomes**: Sicker patients may systematically choose certain hospitals\n- **Treatment adherence and health**: Patient motivation influences both medication compliance and health behaviors\n\n### Formal Definition of Instrumental Variables\n\nAn **instrumental variable** $Z$ is a variable that enables causal identification of the effect of treatment $A$ on outcome $Y$ by satisfying three fundamental assumptions [@neal2020introduction]:\n\n::: {.callout-important}\n### The Three IV Assumptions\n\n1. **Relevance**: $Z$ is statistically associated with treatment $A$\n\n$$\n\\text{Cov}(Z, A) \\neq 0\n$$\n\n2. **Exclusion Restriction**: $Z$ affects outcome $Y$ only through its effect on treatment $A$\n\n$$\nZ \\indep Y | A, U\n$$\n\nwhere $U$ represents unmeasured confounders\n\n3. **Exchangeability**: $Z$ is independent of all unmeasured confounders $U$\n\n$$\nZ \\indep U\n$$\n:::\n\n### The IV Identification Strategy\n\nThe instrumental variables approach works by exploiting exogenous variation in treatment induced by the instrument. Rather than using all variation in treatment (which may be confounded), IV uses only the \"clean\" variation that comes from the instrument [@cunningham2021causalmixtape].\n\nThe IV estimator in the simplest case (binary instrument, binary treatment) is the Wald estimator:\n\n$$\n\\hat{\\beta}_1^{IV} = \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[A|Z=1] - E[A|Z=0]}\n$$\n\nThis represents the ratio of the instrument's effect on the outcome (reduced form) to the instrument's effect on treatment (first stage).\n\n### What IV Identifies: Local Average Treatment Effect (LATE)\n\nA crucial insight in IV analysis is that it typically identifies the **Local Average Treatment Effect** (LATE) rather than the population Average Treatment Effect (ATE) [@imbens1994identification]. The LATE is the average treatment effect for the subpopulation of \"compliers\" - those whose treatment status is affected by the instrument.\n\n## 2 Intuitive Clarifications of Challenging Ideas\n\n### The \"Nudge\" Metaphor for Instruments\n\n::: {.callout-tip}\n### Think of an Instrument as a \"Nudge\"\nAn ideal instrument is like a gentle nudge that pushes some people toward treatment and others away from treatment, but has no other effects on their lives. It's as if nature randomly assigned some people to receive encouragement for treatment, creating a partial experiment within observational data.\n:::\n\n### The Complier Concept Through Medical Analogy\n\nImagine a study using copayment levels as an instrument for medication adherence:\n\n- **Always-takers**: Patients who take medication regardless of copayment (wealthy, highly motivated)\n- **Never-takers**: Patients who never take medication regardless of copayment (skeptical, non-adherent)\n- **Compliers**: Patients whose medication adherence depends on copayment (price-sensitive)\n- **Defiers**: Patients who do the opposite of what cost suggests (rare, usually assumed away)\n\nIV tells us about treatment effects only for the \"compliers\" - those whose behavior changes with the nudge.\n\n### Why LATE ≠ ATE: The Restaurant Menu Analogy\n\n::: {.callout-example}\n### Restaurant Menu Selection\nSuppose we want to know the effect of spicy food (treatment) on satisfaction (outcome), using \"chef's special\" designation as an instrument:\n\n- **Spice lovers** (always-takers): Order spicy food regardless of designation\n- **Spice avoiders** (never-takers): Never order spicy food regardless\n- **Marginal customers** (compliers): Order spicy food only if it's the chef's special\n\nThe effect of spicy food for marginal customers may differ from the average effect across all customers. Spice lovers might have higher tolerance and thus different satisfaction responses.\n:::\n\n### The Exclusion Restriction as \"No Side Effects\"\n\nThe exclusion restriction requires that the instrument affects the outcome only through the treatment, not through any other pathways. This is like requiring that a medical instrument has no side effects - it only works by influencing the treatment decision.\n\n## 3 Simple, Hand-Calculation Numerical Example\n\n::: {.callout-example}\n### College Education and Earnings\n\nLet's study the effect of college completion on annual earnings using quarter of birth as an instrument.\n\n**Setting**:\n\n- $Z$: Born in Q4 (1) vs. other quarters (0)\n- $A$: College degree (1) vs. no degree (0)\n- $Y$: Annual earnings (in thousands of dollars)\n\n**Observed Data Summary** (n = 1,000):\n\n| Birth Quarter | College Rate | Avg Earnings | Sample Size |\n|---------------|--------------|--------------|-------------|\n| Q1-Q3 (Z=0)   | 40%          | $45k         | 750         |\n| Q4 (Z=1)      | 50%          | $48k         | 250         |\n\n:::\n\n### Step-by-Step Hand Calculation\n\n**Step 1: Calculate the First Stage**\nThe first stage measures how much the instrument affects treatment probability:\n\n$$\n\\text{First Stage} = P(A=1|Z=1) - P(A=1|Z=0) = 0.50 - 0.40 = 0.10\n$$\n\n**Step 2: Calculate the Reduced Form**\nThe reduced form measures the instrument's total effect on the outcome:\n\n$$\n\\text{Reduced Form} = E[Y|Z=1] - E[Y|Z=0] = 48 - 45 = 3\n$$\n\n**Step 3: Calculate the IV Estimate**\nThe IV estimate is the ratio of reduced form to first stage:\n\n$$\n\\hat{\\beta}_1^{IV} = \\frac{\\text{Reduced Form}}{\\text{First Stage}} = \\frac{3}{0.10} = 30\n$$\n\n**Interpretation**: Among individuals whose college attendance was influenced by their birth quarter, completing college increases annual earnings by $30,000 on average.\n\n### Understanding the Complier Population\n\nLet's further analyze what proportion of the population are compliers:\n\n- Overall college rate: $(750 \\times 0.40 + 250 \\times 0.50)/1000 = 42.5\\%$\n- If Q4 birth increases college attendance by 10 percentage points, then compliers represent about 10% of the population\n- The $30,000 effect applies to this 10% of the population, not necessarily to all college graduates\n\n## 4 R Code Examples & Interpretation\n\n### Simulation Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set Seed for Reproducibility\nset.seed(123)\nn <- 1000\n\n# Generate Binary Instrument (quarter of birth)\nZ <- rbinom(n, 1, 0.25) # 25% born in Q4\n\n# Generate Unobserved Confounder (ability/motivation)\nU <- rnorm(n, mean = 0, sd = 1)\n\n# Generate Treatment (college completion)\nlinear_index <- -0.5 + 0.4 * Z + 0.6 * U\nA <- rbinom(n, 1, plogis(linear_index))\n\n# Generate Outcome (earnings in thousands)\nY <- 35 + 25 * A + 10 * U + rnorm(n, mean = 0, sd = 8)\n\n# Create Data Frame\ndata <- data.frame(Y = Y, A = A, Z = Z, U = U)\n```\n:::\n\n\n### DAG Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create IV DAG\niv_dag <- dagitty(\n  'dag {\n  Z [pos=\"0,0\"]\n  A [pos=\"1,0\"] \n  Y [pos=\"2,0\"]\n  U [pos=\"1,1\"]\n  \n  Z -> A\n  A -> Y\n  U -> A\n  U -> Y\n}'\n)\n\n# Plot Using Ggdag\nggdag(iv_dag) +\n  theme_dag()\n```\n\n::: {.cell-output-display}\n![Directed Acyclic Graph for IV Setting](week-08_instrumental_variable-rev3_files/figure-pdf/fig-dag-1.pdf){#fig-dag fig-pos='H'}\n:::\n:::\n\n\n### Manual IV Calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manual Calculation of IV Estimate\nfirst_stage <- mean(data$A[data$Z == 1]) - mean(data$A[data$Z == 0])\nreduced_form <- mean(data$Y[data$Z == 1]) - mean(data$Y[data$Z == 0])\niv_estimate <- reduced_form / first_stage\n\ncat(\"First Stage:\", round(first_stage, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst Stage: 0.093 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reduced Form:\", round(reduced_form, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReduced Form: 2.492 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Manual IV Estimate:\", round(iv_estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nManual IV Estimate: 26.798 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare with True Effect and OLS\ntrue_effect <- 25\nols_estimate <- coef(lm(Y ~ A, data = data))[\"A\"]\n\ncat(\"True Causal Effect:\", true_effect, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue Causal Effect: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"OLS Estimate (biased):\", round(ols_estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS Estimate (biased): 31.189 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IV Estimate:\", round(iv_estimate, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIV Estimate: 26.798 \n```\n\n\n:::\n:::\n\n\n### Formal IV Estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using Ivreg Package for IV Estimation\niv_model <- ivreg(Y ~ A | Z, data = data)\nsummary(iv_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nivreg(formula = Y ~ A | Z, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-38.0331  -8.9414  -0.1814   8.5961  45.1099 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   34.200      4.214   8.116  1.4e-15 ***\nA             26.798      9.940   2.696  0.00714 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.62 on 998 degrees of freedom\nMultiple R-Squared: 0.5939,\tAdjusted R-squared: 0.5935 \nWald test: 7.268 on 1 and 998 DF,  p-value: 0.007136 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare with OLS\nols_model <- lm(Y ~ A, data = data)\n\n# Create Comparison Table\nstargazer(\n  ols_model,\n  iv_model,\n  type = \"text\",\n  column.labels = c(\"OLS (Biased)\", \"IV (Causal)\"),\n  omit.stat = c(\"adj.rsq\", \"f\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n===========================================================\n                                   Dependent variable:     \n                               ----------------------------\n                                            Y              \n                                    OLS       instrumental \n                                                variable   \n                                OLS (Biased)   IV (Causal) \n                                    (1)            (2)     \n-----------------------------------------------------------\nA                                31.189***      26.798***  \n                                  (0.796)        (9.940)   \n                                                           \nConstant                         32.347***      34.200***  \n                                  (0.517)        (4.214)   \n                                                           \n-----------------------------------------------------------\nObservations                       1,000          1,000    \nR2                                 0.606          0.594    \nResidual Std. Error (df = 998)     12.436        12.624    \n===========================================================\nNote:                           *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n### Instrument Strength Check\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check First Stage Strength\nfirst_stage_reg <- lm(A ~ Z, data = data)\nfirst_stage_f <- summary(first_stage_reg)$fstatistic[1]\n\ncat(\"First Stage F-statistic:\", round(first_stage_f, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst Stage F-statistic: 6.64 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Strong instrument?\", first_stage_f > 10, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStrong instrument? FALSE \n```\n\n\n:::\n:::\n\n\n## 5 Hands-On R Lab\n\n### Lab Objectives\n\nIn this lab, you will:\n1. Simulate data with unobserved confounding and estimate treatment effects using IV\n2. Practice implementing IV estimation manually and with built-in functions\n3. Diagnose instrument strength and understand its importance\n4. Explore how different instruments identify different LATEs\n5. Reflect on the external validity of IV estimates\n\n### Pre-Lab Reading Warm-up\n\nBefore starting this lab, review:\n- Chapter 16 of @hernan2020causalwhatif on instrumental variables\n- The three core IV assumptions and their intuitive meaning\n- The difference between LATE and ATE\n\n### Data Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate Data for Lab Exercises\nset.seed(579)\nn_lab <- 1500\n\n# Instrument 1: Distance to College (miles)\ndistance <- runif(n_lab, 0, 50)\n\n# Instrument 2: Tuition Subsidy Eligibility (binary)\nsubsidy <- rbinom(n_lab, 1, 0.3)\n\n# Unobserved Ability\nability <- rnorm(n_lab, 0, 2)\n\n# Education (affected by Instruments and ability)\neducation <- 12 +\n  (-0.05) * distance +\n  0.8 * subsidy +\n  0.7 * ability +\n  rnorm(n_lab, 0, 1.5)\neducation <- pmax(education, 8) # Minimum 8 years\n\n# Earnings (affected by Education and ability)\nearnings <- 2.2 + 0.07 * education + 0.15 * ability + rnorm(n_lab, 0, 0.4)\n\nlab_data <- data.frame(\n  log_earnings = earnings,\n  education = education,\n  distance = distance,\n  subsidy = subsidy,\n  ability = ability # Note: in real data, we wouldn't observe this\n)\n```\n:::\n\n\n### Lab Tasks\n\n**Task 1: Exploratory Analysis**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Task 1: Examine the Relationships between Variables\n# 1.1 Check the Correlation between Distance and Education\ncor(lab_data$distance, lab_data$education)\n\n# 1.2 Check the Correlation between Subsidy and Education\ncor(lab_data$subsidy, lab_data$education)\n\n# 1.3 Create Scatter Plots of Education Vs Earnings, and Distance Vs Education\n# YOUR CODE HERE\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solution for Task 1\ncat(\n  \"Correlation between distance and education:\",\n  round(cor(lab_data$distance, lab_data$education), 3),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation between distance and education: -0.321 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"Correlation between subsidy and education:\",\n  round(cor(lab_data$subsidy, lab_data$education), 3),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation between subsidy and education: 0.158 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Scatter Plots\np1 <- ggplot(lab_data, aes(x = education, y = log_earnings)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  labs(\n    title = \"Education vs Earnings\",\n    x = \"Years of Education\",\n    y = \"Log Earnings\"\n  )\n\np2 <- ggplot(lab_data, aes(x = distance, y = education)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  labs(\n    title = \"Distance vs Education\",\n    x = \"Distance to College (miles)\",\n    y = \"Years of Education\"\n  )\n\ngrid.arrange(p1, p2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](week-08_instrumental_variable-rev3_files/figure-pdf/task-1-solution-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Task 2: OLS Estimation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Task 2: Estimate the Education Effect Using OLS\n# 2.1 Run OLS Regression of Earnings on Education\n# ols_model <- YOUR CODE HERE\n\n# 2.2 Interpret the Coefficient on Education\n# The OLS Estimate Suggests That...\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solution for Task 2\nols_model <- lm(log_earnings ~ education, data = lab_data)\nsummary(ols_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_earnings ~ education, data = lab_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.46922 -0.31279 -0.00106  0.32954  1.56016 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.159182   0.066444   17.45   <2e-16 ***\neducation   0.165524   0.005881   28.14   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4676 on 1498 degrees of freedom\nMultiple R-squared:  0.3459,\tAdjusted R-squared:  0.3454 \nF-statistic: 792.1 on 1 and 1498 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"OLS estimate of education effect:\",\n  round(coef(ols_model)[\"education\"], 4),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimate of education effect: 0.1655 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"Interpretation: Each additional year of education is associated with a\",\n  round(exp(coef(ols_model)[\"education\"]) - 1, 4) * 100,\n  \"% increase in earnings, but this may be biased by unobserved ability.\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: Each additional year of education is associated with a 18 % increase in earnings, but this may be biased by unobserved ability.\n```\n\n\n:::\n:::\n\n\n**Task 3: IV Estimation with Distance Instrument**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Task 3: Use Distance as an Instrument for Education\n# 3.1 Estimate First Stage Regression\n# first_stage_distance <- YOUR CODE HERE\n\n# 3.2 Check Instrument Strength (F-statistic)\n# F-statistic =\n\n# 3.3 Estimate IV Regression Using Distance Instrument\n# iv_distance <- YOUR CODE HERE\n\n# 3.4 Compare with OLS Estimate\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solution for Task 3\nfirst_stage_distance <- lm(education ~ distance, data = lab_data)\nf_stat_distance <- summary(first_stage_distance)$fstatistic[1]\n\niv_distance <- ivreg(log_earnings ~ education | distance, data = lab_data)\n\ncat(\"First stage F-statistic:\", round(f_stat_distance, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst stage F-statistic: 172.29 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Strong instrument?\", f_stat_distance > 10, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStrong instrument? TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"IV estimate using distance:\",\n  round(coef(iv_distance)[\"education\"], 4),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIV estimate using distance: 0.0537 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"OLS estimate:\", round(coef(ols_model)[\"education\"], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimate: 0.1655 \n```\n\n\n:::\n:::\n\n\n**Task 4: IV Estimation with Subsidy Instrument**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Task 4: Use Subsidy as an Instrument for Education\n# 4.1 Estimate First Stage with Subsidy\n# first_stage_subsidy <- YOUR CODE HERE\n\n# 4.2 Check Instrument Strength\n# F-statistic =\n\n# 4.3 Estimate IV Regression Using Subsidy\n# iv_subsidy <- YOUR CODE HERE\n\n# 4.4 Compare with Distance Instrument Results\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solution for Task 4\nfirst_stage_subsidy <- lm(education ~ subsidy, data = lab_data)\nf_stat_subsidy <- summary(first_stage_subsidy)$fstatistic[1]\n\niv_subsidy <- ivreg(log_earnings ~ education | subsidy, data = lab_data)\n\ncat(\"First stage F-statistic (subsidy):\", round(f_stat_subsidy, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst stage F-statistic (subsidy): 38.28 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Strong instrument?\", f_stat_subsidy > 10, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStrong instrument? TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IV estimate using subsidy:\", round(coef(iv_subsidy)[\"education\"], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIV estimate using subsidy: 0.0676 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"IV estimate using distance:\",\n  round(coef(iv_distance)[\"education\"], 4),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIV estimate using distance: 0.0537 \n```\n\n\n:::\n:::\n\n\n**Task 5: Multiple Instruments**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Task 5: Use both Instruments together\n# 5.1 Estimate IV with both Instruments\n# iv_both <- YOUR CODE HERE\n\n# 5.2 Perform Overidentification Test\n# YOUR CODE HERE\n\n# 5.3 Interpret the Results\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solution for Task 5\niv_both <- ivreg(log_earnings ~ education | distance + subsidy, data = lab_data)\n\n# Overidentification Test\nlibrary(AER)\noverid_test <- summary(iv_both, diagnostics = TRUE)\ncat(\n  \"Overidentification test p-value:\",\n  round(overid_test$diagnostics[\"Sargan\", \"p-value\"], 4),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOveridentification test p-value: 0.7655 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"IV estimate with both instruments:\",\n  round(coef(iv_both)[\"education\"], 4),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIV estimate with both instruments: 0.0565 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"Do instruments identify the same parameter?\",\n  overid_test$diagnostics[\"Sargan\", \"p-value\"] > 0.05,\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDo instruments identify the same parameter? TRUE \n```\n\n\n:::\n:::\n\n\n### Lab Reflection Questions\n\n1. **Retrieval Quiz**: What are the three core assumptions of instrumental variables, and why is each important?\n2. **Critical Thinking**: Why did the two different instruments give slightly different estimates? What does this tell us about the complier populations?\n3. **Application**: If you were designing a policy to increase educational attainment, which IV estimate would be more relevant and why?\n4. **Limitations**: What are the main threats to the validity of each instrument in this example?\n\n## 6 Common Pitfalls & Checks\n\n::: {.callout-warning}\n### Weak Instruments\nWeak instruments (first stage F-statistic < 10) can cause:\n- Substantial bias in IV estimates, often in the direction of OLS bias\n- Inflated Type I error rates\n- Unreliable inference\n\n**Solution**: Always report first stage F-statistic and consider weak instrument robust methods.\n:::\n\n::: {.callout-warning}\n### Exclusion Restriction Violations\nIf the instrument affects the outcome through pathways other than the treatment, IV estimates are biased. Common violations include:\n- Direct effects of the instrument on the outcome\n- Effects through mediating variables not captured by the treatment\n\n**Solution**: Use domain knowledge to argue for exclusion, test with multiple instruments.\n:::\n\n::: {.callout-warning}\n### Interpretation as LATE Vs ATE\nIV typically identifies the Local Average Treatment Effect (LATE) for compliers, not the population Average Treatment Effect (ATE).\n\n**Solution**: Clearly describe the complier population and discuss external validity limitations.\n:::\n\n::: {.callout-important}\n### Essential Diagnostic Checks\n1. **First stage strength**: F-statistic > 10\n2. **Overidentification tests**: With multiple instruments, check if they identify the same parameter\n3. **Comparison with OLS**: Large differences may indicate substantial selection bias\n4. **Sensitivity analysis**: Test robustness to exclusion restriction violations\n:::\n\n## 7 Advanced Teaching Activities & Interactivity\n\n### Think-Pair-Share: Instrument Validity\n\n**Prompt**: \"Consider using rainfall as an instrument for agricultural productivity in a study of how economic conditions affect civil conflict. Pair up and discuss: (1) Is rainfall a relevant instrument? (2) Does it satisfy the exclusion restriction? (3) Is it exogenous? Be prepared to share your reasoning.\"\n\n### Flipped Classroom Exercise\n\n**Pre-class assignment**: Read @angrist1991does on using quarter of birth as an instrument for education. Come to class prepared to discuss: \"What population does this instrument identify effects for, and how might this limit the policy relevance of the findings?\"\n\n### Problem-Based Case Study\n\n**Scenario**: A hospital wants to evaluate the effect of a new surgical technique on patient outcomes. They're considering using surgeon preference as an instrument, since some surgeons adopted the technique earlier than others.\n\n**Tasks**:\n1. Design the IV analysis plan\n2. Identify potential threats to each assumption\n3. Propose sensitivity analyses\n4. Discuss how you would communicate results to hospital administrators\n\n### Spaced Retrieval Quiz\n\n1. **Week 1**: What are the three core IV assumptions?\n2. **Week 3**: How do we calculate the first stage F-statistic and what does it tell us?\n3. **Week 6**: What is the difference between LATE and ATE, and why does it matter?\n4. **Week 8**: How can multiple instruments help test the exclusion restriction?\n\n### Self-Explanation Task\n\n\"Explain in your own words why IV estimates can be more biased than OLS when instruments are weak. Use the formula for the IV estimator in terms of the first stage to structure your explanation.\"\n\n## 8 Appendix: Advanced Theory & Derivations\n\n### Potential Outcomes Framework for IV\n\nLet $Y_i(a,z)$ be the potential outcome for individual $i$ under treatment $a$ and instrument $z$, and $A_i(z)$ be the potential treatment under instrument $z$.\n\nThe observed data are:\n- $Z_i$: Instrument\n- $A_i = A_i(Z_i)$: Observed treatment\n- $Y_i = Y_i(A_i(Z_i), Z_i)$: Observed outcome\n\n### Principal Stratification\n\nBased on potential treatment responses $(A_i(0), A_i(1))$, individuals fall into four principal strata:\n\n1. **Compliers**: $A_i(0) = 0$, $A_i(1) = 1$\n2. **Always-takers**: $A_i(0) = 1$, $A_i(1) = 1$\n3. **Never-takers**: $A_i(0) = 0$, $A_i(1) = 0$\n4. **Defiers**: $A_i(0) = 1$, $A_i(1) = 0$ (ruled out by monotonicity)\n\n### LATE Theorem\n\nUnder the IV assumptions plus monotonicity, the Wald estimator identifies:\n\n$$\n\\frac{E[Y|Z=1] - E[Y|Z=0]}{E[A|Z=1] - E[A|Z=0]} = E[Y(1) - Y(0) | \\text{Complier}]\n$$\n\nThis is the Local Average Treatment Effect for compliers [@imbens1994identification].\n\n### Efficiency Bounds\n\nThe semiparametric efficiency bound for IV estimation under homoskedasticity is:\n\n$$\nV = \\frac{\\sigma^2}{n \\cdot \\text{Var}(Z) \\cdot R^2_{A|Z}}\n$$\n\nwhere $R^2_{A|Z}$ is the first stage R-squared. This shows why weak instruments lead to imprecise estimates.\n\n## References\n",
    "supporting": [
      "week-08_instrumental_variable-rev3_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}