{
  "hash": "b24a2ba37c66a702c122cc9a9c83adad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Instrumental Variables (IV) Estimation\"\n---\n\n## Overview\n\nThis lecture introduces the fundamental concepts that form the bedrock of modern causal inference. We will move beyond the common refrain that \"correlation is not causation\" to build a formal language for defining, identifying, and estimating causal effects. The core of this framework is the **potential outcomes** model, often attributed to Neyman and Rubin. This model provides a precise way to define a causal effect for a single individual, even though we can never directly observe it. This leads us to the **Fundamental Problem of Causal Inference**, a central challenge we will spend the semester learning to address. We'll also define critical assumptions like the **Stable Unit-Treatment-Value Assumption (SUTVA)** and discuss the role of the **assignment mechanism** in our ability to learn about causal effects from data.\n\n## Learning Objectives\n\nBy the end of this session and the associated lab, you will be able to:\n\n1. **Define** and differentiate between units, treatments, potential outcomes, and observed outcomes using formal notation.\n2. **Articulate** the Fundamental Problem of Causal Inference and explain why it makes unit-level causal effects unobservable.\n3. **Explain** the two components of the Stable Unit-Treatment-Value Assumption (SUTVA) -- consistency and no interference -- and provide examples of scenarios where each might be violated.\n4. **Calculate** a true population-level Average Causal Effect (ACE) from a hypothetical table of potential outcomes.\n5. **Distinguish** between a true causal effect and a naive associational difference in means, and use a Directed Acyclic Graph (DAG) to represent the confounding that leads to this difference.\n\n## R Packages\n\nWe'll use the following packages for this lecture and lab. The `pacman` package will automatically install any missing packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(\n  tidyverse, # For data manipulation and plotting\n  dagitty,   # For creating and analyzing DAGs\n  ggdag,     # For plotting DAGs with ggplot2\n  knitr,     # For creating nice tables\n  patchwork  # For combining plots\n)\n\n# Set a consistent theme for ggplot2\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\n## Comprehensive Topic Explanation\n\n### The Potential Outcomes Framework\n\nTo rigorously define a causal effect, we need a formal framework. The most common one in statistics and epidemiology is the **potential outcomes** framework, also known as the Neyman-Rubin Causal Model (@hernan2020causalwhatif).\n\n  - **Unit**: The entity upon which a treatment acts. This could be a person, a patient, a school, a country, or even the same person at two different points in time. Let's index our units by $i=1, \\dots, N$.\n  - **Treatment**: An intervention or exposure whose effect we want to assess. We'll start with a simple binary treatment, denoted by $A$. For each unit $i$, $A_i=1$ if they receive the treatment and $A_i=0$ if they receive the control (e.g., no treatment or a placebo).\n  - **Potential Outcomes**: For each unit $i$, there are two **potential outcomes** corresponding to the two possible treatment levels.\n\t  - $Y_i^1$: The outcome that *would be observed* for unit $i$ if they were to receive the treatment ($A_i=1$).\n\t  - $Y_i^0$: The outcome that *would be observed* for unit $i$ if they were to receive the control ($A_i=0$).\n\t\tThese outcomes are \"potential\" because, for any given unit, we can only ever observe one of them.\n\n### Defining Causal Effects\n\nWith this notation, we can define a causal effect at the most fundamental level: the individual.\n\n  - **Unit-Level Causal Effect**: For unit $i$, the causal effect of treatment $A$ on outcome $Y$ is the difference between their two potential outcomes:\n\n$$\n \\tau_i = Y_i^1 - Y_i^0 \n$$\n\n    This is the difference between what would have happened to unit $i$ under treatment versus what would have happened to unit $i$ under control, at the same moment in time.\n\nThis definition is powerful because it is precise. The causal effect is not about a change over time but about a comparison between two parallel, \"counterfactual\" worlds.\n\n### The Fundamental Problem of Causal Inference\n\nThe definition of the unit-level causal effect immediately reveals a profound challenge. For any given unit $i$, we can only observe *one* of their potential outcomes. If unit $i$ received the treatment ($A_i=1$), we observe $Y_i^{obs} = Y_i^1$ but $Y_i^0$ is unobserved (counterfactual). If they received the control ($A_i=0$), we observe $Y_i^{obs} = Y_i^0$ but $Y_i^1$ is counterfactual.\n\n> **The Fundamental Problem of Causal Inference**: It is impossible to observe both potential outcomes for the same unit at the same time. Therefore, the unit-level causal effect $\\tau_i$ is fundamentally unobservable (@hernan2020causalwhatif, Chapter 1).\n\nBecause we cannot calculate individual causal effects, we shift our goal to estimating **population-level causal effects**, such as the Average Causal Effect (ACE), also called the Average Treatment Effect (ATE).\n\n  - **Average Causal Effect (ACE)**: The average of the unit-level causal effects across all units in the population.\n\n$$\n ACE = E[\\tau_i] = E[Y^1 - Y^0] \n$$\n\n    In a finite sample of $N$ units, the sample ACE is $\\frac{1}{N} \\sum_{i=1}^{N} (Y_i^1 - Y_i^0)$.\n\n### The Stable Unit-Treatment-Value Assumption (SUTVA)\n\nTo make progress, we need to make some assumptions about how units, treatments, and outcomes behave. The **Stable Unit-Treatment-Value Assumption (SUTVA)** is a critical one and has two parts (@neal2020introduction):\n\n1. **Consistency**: A unit's observed outcome under a specific treatment is precisely their potential outcome under that same treatment. Formally, if $A_i = a$, then $Y_i^{obs} = Y_i(a)$. This seems obvious, but it implies that there are no hidden versions of the treatment. For example, \"aspirin\" must be the same pill with the same dosage for everyone who takes it. If some people get a high dose and others a low dose, but we just call it \"aspirin,\" consistency is violated.\n2. **No Interference**: The potential outcomes of one unit are not affected by the treatment assignment of any other unit. Formally, $Y_i(a)$ does not depend on the value of $A_j$ for any $j \\neq i$. This assumption is often violated in settings with social interaction or competition. For example, the effectiveness of a vaccine for one person ($Y_i^1$) absolutely depends on whether other people are also vaccinated ($A_j=1$ for $j \\neq i$).\n\nSUTVA allows us to write the potential outcomes for unit $i$ as $Y_i^1$ and $Y_i^0$, without having to worry about which other units received treatment.\n\n### The Assignment Mechanism\n\nThe final piece of the puzzle is the **assignment mechanism**—the rule or process that determines which units receive the treatment and which receive the control. This mechanism is the key to whether we can estimate the ACE. In an ideal **randomized controlled trial (RCT)**, the assignment mechanism is a coin flip for each unit, which, as we will see, allows for unbiased estimation of the ACE. In observational studies, the assignment mechanism is often unknown and convoluted, leading to major challenges like confounding.\n\n## Intuitive Clarifications of Challenging Ideas\n\n### The \"Sliding Doors\" Analogy for the Fundamental Problem\n\nThink of the movie *Sliding Doors*. The main character's life splits into two parallel timelines based on one tiny event: whether she catches a train or not.\n\n  - **Timeline 1 (Catches Train)**: She gets home early, finds her boyfriend cheating, and her life goes one way. This is her $Y^1$.\n  - **Timeline 2 (Misses Train)**: She gets home late, the scene has passed, and her life proceeds very differently. This is her $Y^0$.\n\nThe **causal effect** of catching the train is the difference in her life outcomes between these two timelines. The **Fundamental Problem of Causal Inference** is that in reality, we only get to live in one timeline. We can't see both. Causal inference is the set of tools we use to try to learn about the unseen timeline using data from a population of people, each of whom lived out only one of their own possible timelines.\n\n### SUTVA: \"No Surprises, No Spillovers\"\n\nSUTVA can feel abstract. Let's break it down with an analogy. Imagine a study on a new fertilizer.\n\n1. **Consistency (\"No Surprises\")**: When we say a farmer used the \"new fertilizer\" ($A=1$), we assume it's the *exact same formula* for every farmer. If Farmer Joe got \"Fertilizer v1.1\" and Farmer Sue got \"Fertilizer v1.2 with extra nitrogen,\" we can't cleanly write their outcome as $Y^1$. There are hidden versions of the treatment, violating consistency.\n2. **No Interference (\"No Spillovers\")**: We assume the fertilizer on Farmer Joe's plot doesn't affect the crop yield on his neighbor Farmer Sue's plot. This might be a bad assumption\\! What if the fertilizer seeps through the soil (a spillover effect)? Sue didn't get the treatment ($A_{Sue}=0$), but her outcome is affected by Joe's treatment ($A_{Joe}=1$). This violates the \"no interference\" assumption.\n\n## 3\\. Simple, Hand-Calculation Numerical Example\n\nLet's imagine a tiny study with 4 people to investigate whether a new medication ($A=1$) reduces blood pressure compared to a placebo ($A=0$). The outcome $Y$ is systolic blood pressure (SBP).\n\nCritically, we will take a \"God's-eye view\" and assume we can see *both* potential outcomes for all 4 people. In the real world, this is impossible.\n\n| Unit (i) | $Y_i^1$  (SBP with Med) | $Y_i^0$  (SBP with Placebo) | $\\tau_i = Y_i^1 - Y_i^0$  (Unit-level Effect) |\n| :------: | :----------------------------: | :--------------------------------: | :---------------------------------------------------: |\n|    1     |              130               |                140                 |                          -10                          |\n|    2     |              125               |                130                 |                          -5                           |\n|    3     |              150               |                165                 |                          -15                          |\n|    4     |              135               |                145                 |                          -10                          |\n\n> [!NOTE] God's-eye view\n> A \"God's-eye view\" refers to a perspective that assumes an all-knowing viewpoint, often used in literature, film, or philosophy to describe a situation where the observer has complete knowledge of events and characters that others do not. It can also relate to a filmmaking technique that captures scenes from an overhead angle, providing a broader view of the action.\n\n#### Step 1: Calculate the True Average Causal Effect (ACE)\n\nThe true ACE is the average of the individual, unobservable causal effects ($\\tau_i$).\n\n$$\nACE = \\frac{1}{N} \\sum_{i=1}^{N} \\tau_i = \\frac{(-10) + (-5) + (-15) + (-10)}{4} = \\frac{-40}{4} = -10\n$$\n\nThe **true average causal effect** of the medication is a 10-point reduction in systolic blood pressure.\n\n#### Step 2: Introduce the \"Veil of Ignorance\"\n\nNow, let's step back from our God's-eye view and see what a researcher would see. Suppose units 1 and 3 were (somehow) assigned to the treatment ($A=1$) and units 2 and 4 were assigned to the control ($A=0$).\n\nThe researcher only sees the **observed outcomes** ($Y^{obs}$):\n\n| Unit (i) | Treatment ($A_i$) | $Y_i^{obs}$ |\n| :------: | :---------------: | :---------: |\n|    1     |         1         |     130     |\n|    2     |         0         |     130     |\n|    3     |         1         |     150     |\n|    4     |         0         |     145     |\n\n> [!NOTE] Veil of Ignorance\n> The \"Veil of Ignorance\" is a philosophical concept introduced by John Rawls, which suggests that individuals should design a society without knowing their own personal circumstances, such as their gender, race, or social status. This thought experiment aims to promote fairness and impartiality in creating social contracts and principles of justice.\n\n#### Step 3: Calculate the Naive Associational Difference\n\nA naive researcher might just compare the average outcome in the treated group to the average outcome in the control group.\n\n- Average SBP for the Treated: $E[Y^{obs} | A=1] = \\frac{130 + 150}{2} = 140$\n- Average SBP for the Control: $E[Y^{obs} | A=0] = \\frac{130 + 145}{2} = 137.5$\n\nThe naive difference of means is $140 - 137.5 = 2.5$.\n\n#### Step 4: Interpret the Disaster\n\nThe naive estimate suggests the drug *increases* blood pressure by 2.5 points, while the true causal effect was a *decrease* of 10 points\\!\n\n**Why did this happen?** This is **selection bias**. The people who received the treatment (units 1 and 3) were different from the people who received the control (units 2 and 4) *before the study even began*. Specifically, the treated group had a higher average baseline SBP under placebo ($E[Y^0|A=1] = (140+165)/2 = 152.5$) than the control group ($E[Y^0|A=0] = (130+145)/2 = 137.5$). They were sicker to begin with. This pre-existing difference is called **confounding**.\n\n## 4\\. R Code Examples & Interpretation\n\n### Visualizing Causal Structures with DAGs\n\nDirected Acyclic Graphs (DAGs) are powerful tools for visualizing our causal assumptions (@pearl2009causality).\n\nA randomized controlled trial (RCT) has a very simple causal structure. Treatment ($A$) causes the Outcome ($Y$). There are no other arrows pointing into $A$, representing the fact that assignment was random and not influenced by any other factor.\n\n```tikz\n\\begin{tikzpicture}\n\\node (A) at (0,0) {$A$};\n\\node (Y) at (2,0) {$Y$};\n\\draw[->, thick] (A) -- (Y);\n\\end{tikzpicture}\n```\n\nIn our disastrous hand-calculation example, there was a **confounder** ($L$)—the baseline sickness of the patient. This confounder affects both who gets the treatment (sicker people might be more likely to seek treatment) and the final outcome (sicker people will have higher blood pressure regardless of treatment).\n\n```tikz\n\\begin{tikzpicture}\n\\node (A) at (0,0) {$A$};\n\\node (Y) at (2,0) {$Y$};\n\\node (L) at (1,1) {$L$};\n\\draw[->, thick] (A) -- (Y);\n\\draw[->, thick, red] (L) -- (A);\n\\draw[->, thick, red] (L) -- (Y);\n\\end{tikzpicture}\n```\n\nThe red arrows represent the confounding path $L \\rightarrow A \\rightarrow Y \\leftarrow L$, which creates a non-causal association between $A$ and $Y$.\n\n#### Using `dagitty` and `ggdag` in R\n\nWe can create the same DAGs programmatically in R. This is highly recommended as `dagitty` can also be used to analyze the graph for confounding, selection bias, etc.\n\n\n::: {#fig-dags .cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\n# DAG for a Randomized Trial\ndag_rct <- dagify(\nY ~ A,\nexposure = \"A\",\noutcome = \"Y\"\n)\n\np_rct <- ggdag(dag_rct, text_col = \"white\", stylized = TRUE) +\ntheme_dag()\n\n# DAG for a Confounded Study\ndag_confounded <- dagify(\nY ~ A + L,\nA ~ L,\nexposure = \"A\",\noutcome = \"Y\",\ncoords = list(x = c(A = 1, Y = 3, L = 2),\ny = c(A = 1, Y = 1, L = 2))\n)\n\np_confounded <- ggdag_confounder_path(dag_confounded, from = \"A\", to = \"Y\") +\ntheme_dag(base_size = 14)\n\n# Plot Side-by-side\np_rct\np_confounded\n```\n\nCausal DAGs for a Randomized Trial vs. a Confounded Observational Study\n:::\n\n\nThe plot on the left shows the ideal world of an RCT. The arrow from A to Y represents the causal effect we want to estimate. The plot on the right shows the observational study. The path $A \\rightarrow Y$ is the direct causal effect. The \"backdoor path\" $A \\leftarrow L \\rightarrow Y$ is a confounding path that creates a spurious association between A and Y. To estimate the causal effect, we must \"block\" this backdoor path, typically by conditioning on (adjusting for) $L$.\n\n### Simulating Confounding in R\n\nLet's replicate our hand-calculation example with a simulation to see confounding in action.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # for reproducibility\nn <- 1000     # number of units\n\n# 1. Create a Confounder L (e.g., Baseline Health, from 0 to 10)\nl <- rnorm(n, mean = 5, sd = 2)\n\n# 2. Assign Treatment A Based on the Confounder L\n# People with Worse Health (higher L) Are More Likely to Get Treatment\nprob_a <- plogis(-2 + 0.8 * l) # Use logistic function for probability\na <- rbinom(n, 1, prob_a)\n\n# 3. Define Potential Outcomes\n# The True Causal Effect is -10\n# The Confounder L also Affects the Outcome\ny0 <- 140 + 5 * l + rnorm(n, 0, 5)\ny1 <- y0 - 10 # True causal effect is a reduction of 10\n\n# 4. Create the Observed Data\n# The \"fundamental problem\" in Action\ny_obs <- ifelse(a == 1, y1, y0)\n\nsim_data <- tibble(L = l, A = a, Y_obs = y_obs, Y0 = y0, Y1 = y1)\n\n# Look at the First Few Rows\nknitr::kable(head(sim_data), digits = 2, caption = \"Simulated Data (with Unobservable Potential Outcomes)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Simulated Data (with Unobservable Potential Outcomes)\n\n|    L|  A|  Y_obs|     Y0|     Y1|\n|----:|--:|------:|------:|------:|\n| 3.88|  1| 145.29| 155.29| 145.29|\n| 4.54|  1| 151.16| 161.16| 151.16|\n| 8.12|  1| 166.08| 176.08| 166.08|\n| 5.14|  1| 158.84| 168.84| 158.84|\n| 5.26|  1| 161.89| 171.89| 161.89|\n| 8.43|  1| 182.79| 192.79| 182.79|\n\n\n:::\n:::\n\n\nNow, let's calculate the true ACE and the naive difference-in-means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the TRUE Average Causal Effect (from the Potential outcomes)\ntrue_ace <- mean(sim_data$Y1 - sim_data$Y0)\n\n# Calculate the NAIVE Association (from the Observed data)\nnaive_assoc <- sim_data |>\ngroup_by(A) |>\nsummarise(mean_Y = mean(Y_obs)) |>\nspread(A, mean_Y) |>\nmutate(diff = `1` - `0`) |>\npull(diff)\n\ncat(\n\"True Average Causal Effect:\", round(true_ace, 2), \"\\n\",\n\"Naive Difference-in-Means:\", round(naive_assoc, 2), \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue Average Causal Effect: -10 \n Naive Difference-in-Means: 0.71 \n```\n\n\n:::\n:::\n\n\n**Interpretation**: The simulation shows exactly what we saw in the hand calculation. The **true causal effect** we built into the data was -10. However, the simple comparison of group means gives us an estimate of -0.76, which is heavily biased towards zero. This is because sicker people (higher L) were more likely to be treated, and sicker people also have worse outcomes. The confounding from L masks the true beneficial effect of the treatment.\n\n## 5\\. Hands-On R Lab\n\n### Lab Objectives\n\n- **Practice** defining a causal question using potential outcomes.\n- **Calculate** the true ATE in a simulated dataset where you have access to the potential outcomes.\n- **Calculate** the associational difference-in-means from the \"observed\" data.\n- **Reflect** on why the ATE and the associational difference are not the same in this dataset.\n\n### Warm-Up & Reading\n\nPlease read Chapter 1 and 2 of *Causal Inference: What If* by Hernán and Robins. Pay close attention to the definitions of potential outcomes, individual causal effects, and SUTVA.\n\n### 1\\. Load Data\n\nFor this lab, we will use a simulated dataset about a job training program.\n\n- `A`: Treatment (1 = received job training, 0 = did not).\n- `Y_obs`: Observed outcome (annual income in thousands of dollars).\n- `motivation`: A pre-treatment characteristic of each individual (scale 1-10).\n- `Y1`, `Y0`: The (usually unobservable) potential outcomes for income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Skeleton Code for Students\nset.seed(42)\nn_lab <- 500\nmotivation <- runif(n_lab, 1, 10)\nprob_a_lab <- plogis(-3 + 0.6 * motivation)\na_lab <- rbinom(n_lab, 1, prob_a_lab)\n\ny0_lab <- 30 + 3 * motivation + rnorm(n_lab, 0, 4)\ny1_lab <- y0_lab + 5 # True effect of training is $5k\n\ny_obs_lab <- ifelse(a_lab == 1, y1_lab, y0_lab)\n\nlab_data <- tibble(\nmotivation = motivation,\nA = a_lab,\nY_obs = y_obs_lab,\nY1 = y1_lab,\nY0 = y0_lab\n)\n\n# --- Students Should Run This Code to Create the lab_data Tibble ---\n```\n:::\n\n\n### 2\\. The \"God's-Eye\" View: Calculate the True ATE\n\nImagine you are an omniscient being and can see both `Y1` and `Y0` for every person. Calculate the true Average Treatment Effect (ATE) of the job training program.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Skeleton Code ---\n# To Calculate the True ATE, You Need to First Find the Individual\n# Causal Effect for Each Person, then Find the Average.\n# Add a New Column 'tau' to lab_data for the Individual Effect.\nlab_data_with_tau <- lab_data |>\nmutate(tau = Y1 - Y0) # Your code here!\n\n# Now, Calculate the Mean of the 'tau' Column\ntrue_ate_lab <- mean(lab_data_with_tau$tau) # Your code here!\n\n# Print the Result\n# print(true_ate_lab) # Your Code Here!\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Solution ---\n# To Calculate the True ATE, You Need to First Find the Individual\n# Causal Effect for Each Person, then Find the Average.\n# Add a New Column &#39;tau&#39; to lab_data for the Individual Effect.\nlab_data_with_tau &lt;- lab_data |&gt;\nmutate(tau = Y1 - Y0)\n\n# Now, Calculate the Mean of the 'tau' Column\n\ntrue_ate_lab \\<- mean(lab_data_with_tau$tau)\n\n# Print the Result\n\nprint(true_ate_lab)\n```\n:::\n\n\nThe true ATE is exactly 5, as we designed in the simulation. This means the job training program, on average, increases annual income by $5,000.\n\n### 3. The Researcher's View: Calculate the Naive Association\n\nNow, put on your researcher hat. You can't see `Y1` and `Y0`. You can only see who got the training (`A`) and what their final income was (`Y_obs`). Calculate the simple difference in mean income between the group that received training and the group that did not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Skeleton Code ---\n# Group the Data by the Treatment Variable 'A'\n# And Calculate the Mean of the Observed Outcome 'Y_obs' for Each Group.\n# Then, Calculate the Difference.\nnaive_estimate <- lab_data |>\ngroup_by(A) |>\nsummarize(mean_income = mean(Y_obs)) # Your code here!\n\n# print(naive_estimate) # Your Code Here!\n\n# You Can also Use the spread() and mutate() Trick from the Lecture\n# To Get the Difference Directly.\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# \\--- Solution ---\n\nnaive_estimate \\<- lab_data |>\ngroup_by(A) |>\nsummarize(mean_income = mean(Y_obs))\n\nprint(naive_estimate)\n\n# Difference is 54.4 - 45.4 = 9.0\n\n# Or Using the spread() Trick:\n\nnaive_diff \\<- lab_data |>\ngroup_by(A) |>\nsummarise(mean_Y = mean(Y_obs)) |>\nspread(A, mean_Y) |>\nmutate(diff = `1` - `0`) |>\npull(diff)\n\nprint(paste(\"The naive difference is:\", round(naive_diff, 2)))\n```\n:::\n\n\nThe naive estimate is about $9,000. This is much larger than the true causal effect of $5,000!\n\n### 4. Retrieval & Reflection\n\nAnswer the following questions to solidify your understanding.\n\n1. **Retrieval Quiz:**\n- What are the two components of SUTVA?\n- Why can we not calculate the unit-level causal effect for an individual?\n- What is the term for a pre-treatment variable that affects both treatment assignment and the outcome?\n\n2. **Reflection Prompt:**\n- In our lab simulation, the naive estimate ($9k) was much larger than the true ATE ($5k). Why did this happen? Look at the code that generated the data, specifically how treatment `A` was assigned. What real-world story does this data simulation tell?\n\n<details>\n<summary>Click for Answers</summary>\n\n1. **Quiz Answers:**\n- SUTVA has two components: **consistency** (no hidden versions of treatment) and **no interference** (no spillovers between units).\n- The **Fundamental Problem of Causal Inference**: we can only observe one potential outcome for each person (the one corresponding to the treatment they actually received).\n- This variable is a **confounder**.\n\n2. **Reflection Answer:**\n- The naive estimate is biased because of confounding by `motivation`. The simulation was set up so that more motivated individuals were more likely to sign up for the job training program (`prob_a_lab <- plogis(-3 + 0.6 * motivation)`). At the same time, more motivated individuals were going to have higher incomes anyway, regardless of the training (`y0_lab <- 30 + 3 * motivation + …`). The naive analysis incorrectly attributes the extra income that comes from motivation to the training program. This is a classic example of **selection bias**.\n\n</details>\n\n---\n\n## 6. Common Pitfalls & Checks\n\n::: {.callout-warning}\n\n## Confounding Association with Causation\n\nThe most fundamental error is to compute a simple difference in means between a treated and control group from observational data and interpret it as a causal effect. As our examples show, this difference is a mix of the true causal effect and bias from confounding. **Association is not causation!**\n\n:::\n\n::: {.callout-important}\n\n## SUTVA is a Strong, Untestable Assumption\n\nSUTVA is a foundational assumption that we must make to even write down potential outcomes in the simple $Y^1, Y^0$ form. It is often violated in the real world. You cannot test SUTVA with your data; you must justify it based on domain knowledge of the problem. Always ask yourself: \"Could there be interference? Are there hidden versions of the treatment?\"\n\n:::\n\n::: {.callout-tip}\n\n## Define Your Causal Question First\n\nBefore you touch any data, clearly define your causal question.\n\n1. What are the **units**?\n2. What is the **treatment** ($A=1$) and **control** ($A=0$)?\n3. What is the **outcome** ($Y$)?\n4. What are the potential outcomes $Y^1$ and $Y^0$?\n\nThis process, called specifying the \"causal estimand,\" helps clarify your thinking and prevents you from simply mining the data for associations.\n\n:::\n\n::: {.callout-question}\n\n## Check Your Understanding\n\n**Question:** A city implements a new \"after-school tutoring\" program ($A=1$) to improve student test scores ($Y$). Students must sign up to participate. At the end of the year, the average test score for students in the program is 85, while the average for students not in the program is 75. A city official declares \"The tutoring program caused a 10-point increase in test scores!\"\n\nWhat is wrong with this conclusion? What is a likely confounder?\n\n**Answer:** The official is confusing association with causation. This is observational data. A likely confounder is **student motivation** or **parental involvement**. Highly motivated students are more likely to sign up for tutoring *and* more likely to get good grades anyway. The 10-point difference is likely a mix of the true (and probably smaller) effect of tutoring and this selection bias.\n:::\n\n---\n\n## 7. Advanced Teaching Activities & Interactivity\n\n- **Think-Pair-Share:** Turn to a partner and brainstorm two real-world scenarios. In the first, the **no interference** part of SUTVA is likely violated. In the second, the **consistency** part of SUTVA is likely violated. Be prepared to share with the class.\n- *Example for interference: A study on the effect of a new teaching method in one classroom on student test scores. Students might talk to friends in other classrooms, causing spillovers.*\n- *Example for consistency: A study on the effect of \"exercise\" on weight loss. \"Exercise\" could mean running, swimming, or weightlifting; it's not a well-defined treatment.*\n- **Flipped Classroom Prompt:** Before the next class, watch [this video on the paradox of Simpson's Paradox](https://www.youtube.com/watch?v=vs_Z-3zI6sI). Come to class prepared to draw the DAG that explains how the paradox occurs.\n- **Problem-Based Learning Case:** A pharmaceutical company has just completed a Phase III randomized controlled trial for a new heart disease drug. However, 20% of the patients assigned to the treatment group stopped taking the drug due to side effects (non-compliance). How does this complicate the definition of the causal effect? What are we trying to estimate anymore? The effect of *being assigned* the drug (Intention-to-Treat) or the effect of *actually taking* the drug (Per-Protocol)? This introduces the concepts of ITT vs. PP analysis and the role of compliance as a post-treatment variable.\n\n---\n\n## References\n\n::: {#refs}\n\n:::\n\n---\n\n## 8. Appendix: Advanced Theory & Derivations\n\n### Why Randomization Works: The Math\n\nThe \"magic\" of a randomized controlled trial (RCT) is that it allows us to equate the naive difference in means with the Average Causal Effect (ACE). Let's see why.\n\nThe quantity we can estimate from data is the associational difference:\n\n$$\n \\Delta_{assoc} = E[Y^{obs} | A=1] - E[Y^{obs} | A=0] \n$$\n\nThe quantity we want is the causal effect:\n\n$$\n ACE = E[Y^1] - E[Y^0] \n$$\n\nLet's expand the first term of the associational difference using the consistency assumption ($Y^{obs} = Y^1$ when $A=1$):\n\n$$\n E[Y^{obs} | A=1] = E[Y^1 | A=1] \n$$\n\nSimilarly, $E[Y^{obs} | A=0] = E[Y^0 | A=0]$.\n\nSo, the associational difference is really:\n\n$$\n \\Delta_{assoc} = E[Y^1 | A=1] - E[Y^0 | A=0]\n$$\n\nThis does **not** equal the ACE, $E[Y^1] - E[Y^0]$. The problem is the conditioning on $A$. $E[Y^1 | A=1]$ is the average outcome under treatment *for those who chose to be treated*. This might be very different from the average outcome under treatment for the whole population, $E[Y^1]$.\n\nThis is where randomization comes in. In an ideal RCT, the treatment $A$ is assigned completely at random (e.g., by a coin flip). This means that the assignment $A$ is statistically independent of any and all characteristics of the units, including their potential outcomes. Formally, randomization implies:\n\n$$\n A \\perp (Y^1, Y^0) \n$$\n\nwhere $\\perp$ means \"is independent of\".\n\nIf this independence holds, then:\n\n$$\n E[Y^1 | A=1] = E[Y^1] \n$$\n\nand\n\n$$\n E[Y^0 | A=0] = E[Y^0] \n$$\n\n**In English:** The average potential outcome under treatment, $Y^1$, is the same for the group that happened to get the treatment as it is for the overall population, because getting the treatment was a matter of pure chance, unrelated to their potential outcome.\n\nBy substituting these back into the equation for the associational difference, we get:\n\n$$\n \\Delta_{assoc}^{RCT} = E[Y^1] - E[Y^0] = ACE \n$$\n\nThis proves that under randomization, the simple, observable difference in means is an unbiased estimator for the unobservable Average Causal Effect. This is the primary reason why RCTs are considered the \"gold standard\" for causal inference.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}