{
  "hash": "cc14edbf4e35b66511914b4e76145f2d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Propensity Score Methods\"\n---\n\n## Overview\n\nWelcome to Week 5. We have established that to estimate causal effects from observational data, we must control for confounding by conditioning on a sufficient set of pre-treatment covariates, $L$, that block all backdoor paths. While methods like stratification and regression are conceptually straightforward, they buckle under the **curse of dimensionality**---the practical impossibility of adjusting for many or continuous confounders simultaneously.\n\nThis week, we introduce the **propensity score**, a revolutionary concept that provides an elegant solution to this problem. The propensity score is a single number, the estimated probability of receiving treatment, that can summarize all confounding information from a vast set of covariates. By using this score, we can design observational studies that powerfully mimic randomized experiments [@hernan2020causalwhatif].\n\nWe will first build a deep theoretical understanding of the propensity score. Then, we will master its three principal applications: **matching**, **stratification**, and **Inverse Probability of Treatment Weighting (IPTW)**. Our guiding principle will be that propensity score analysis is a two-stage process: first, we focus *only* on the covariates to achieve balance, creating a pseudo-experiment. Only after we are satisfied with the balance do we introduce the outcome to estimate the causal effect.\n\n## Learning Objectives\n\nBy the end of this week's module and lab, you will be able to:\n\n1. **Define** the propensity score, $e(L) = P(A=1|L)$, and articulate its theoretical role as a \"balancing score\" that solves the curse of dimensionality.\n2. **Explain** the assumptions of conditional exchangeability and positivity in the context of propensity score analysis and diagnose potential violations.\n3. **Estimate** propensity scores using logistic regression in R and critically assess the resulting score distributions for sufficient overlap.\n4. **Implement** propensity score matching (PSM) and inverse probability of treatment weighting (IPTW) to estimate the Average Treatment Effect (ATE).\n5. **Master** the use of covariate balance diagnostics, including Love plots and standardized mean differences (SMDs), to verify that the propensity score model has successfully created a pseudo-randomized experiment.\n\n## R Packages\n\nWe will use a suite of packages that are staples in the causal inference toolkit. The `pacman` package will install any you are missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) {\n  install.packages(\"pacman\")\n}\npacman::p_load(\n  tidyverse, # For data wrangling and plotting\n  dagitty, # For DAG logic\n  ggdag, # For plotting DAGs\n  MatchIt, # The premier package for propensity score matching\n  WeightIt, # For a wide array of weighting methods, including IPTW\n  cobalt, # Essential for checking covariate balance\n  broom, # For tidying model outputs\n  knitr # For professional-looking tables\n)\n\n# Set a consistent theme for our plots\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\n# Comprehensive Topic Explanation\n\n## The Challenge: The Curse of Dimensionality\n\nIn previous weeks, we established that to achieve **conditional exchangeability** ($Y^a \\indep A | L$), we must condition on a sufficient set of confounders, $L$.\n\n  - **Stratification:** This involves comparing treated and untreated individuals within fine strata of $L$. If $L$ contains just two binary confounders, we need four strata. If it contains ten binary confounders, we need $2^{10} = 1024$ strata. With continuous confounders like age or blood pressure, the number of potential strata is infinite. We quickly run out of data. This is the **curse of dimensionality**.\n  - **Outcome Regression:** We can include $L$ as predictors in a regression model for the outcome, e.g., $E[Y | A, L] = \\beta_0 + \\beta_1 A + \\boldsymbol{\\beta_2'L}$. However, this approach requires that the model is **correctly specified**. We are forced to make strong assumptions about functional forms (e.g., linearity, no interactions) that are rarely known to be true. A misspecified outcome model leads to **residual confounding** and biased estimates.\n\n## The Solution: The Propensity Score\n\nThe propensity score, formally introduced by @rosenbaum1983central, is a radical and powerful idea. It collapses all the information from a potentially high-dimensional vector of confounders $L$ into a single scalar value.\n\n::: {.callout-important}\n\n# Definition: The Propensity Score\n\nThe propensity score, $e(L)$, is the conditional probability of an individual receiving the treatment of interest ($A=1$), given their vector of observed pre-treatment covariates $L$.\n\n$$\ne(L) \\equiv \\pr(A=1 | L)\n$$\n\n:::\n\n**Rationale in Plain English:** The propensity score doesn't predict the outcome. It predicts the *treatment*. It answers the question: \"For a person with these specific characteristics (age, sex, health status, etc.), what was the probability that they would receive this treatment?\" This simple-sounding probability has profound properties.\n\n## The \"Balancing Score\" Property\n\nThe magic of the propensity score lies in its property as a **balancing score**. This means that if we take any two individuals, one treated ($A=1$) and one untreated ($A=0$), who have the **exact same propensity score**, then the distribution of their full set of covariates, $L$, must be identical on average.\n\n**Mathematical Formulation:**\n\n$$\nA \\indep L \\mid e(L)\n$$\n\n**Explanation:** This formula says that treatment assignment ($A$) is independent of the set of confounders ($L$) *conditional on the propensity score* $e(L)$. By conditioning on this single value, we break the link between the confounders and the treatment, effectively blocking all backdoor paths from $L$ to $A$. This allows us to achieve exchangeability by conditioning on $e(L)$ alone, provided the initial set of covariates $L$ was sufficient.\n\n:::{#fig-propensity-dag}\n\n```{.tikz}\n\\begin{figure}[h!]\n\\centering\n\\begin{tikzpicture}[\n    node distance=3cm,\n    main/.style={draw, circle, fill=white, minimum size=1cm, font=\\small},\n    anno/.style={font=\\small\\sffamily}\n]\n    % Nodes \n    \\node[main] (A) {$A$};\n    \\node[main] (Y) [right of=A, xshift=4cm] {$Y$};\n    \\node[main] (L) [above of=A, xshift=3cm] {$L$};\n    \\node[main, fill=blue!5] (eL) [below of=L, yshift=1.2cm] {$e(L)$};\n    \n    % Paths\n    \\draw[->, very thick, red!70] (L) edge[bend right=20] node[above, anno, red!70] {confounding} (A);\n    \\draw[->, very thick, red!70] (L) edge[bend left=20] (Y);\n    \\draw[->, very thick, blue!70] (A) edge node[above, anno, blue!70] {causal} (Y);\n    \n    % Propensity Score Path  \n    \\draw[->, thick, dashed, gray!70] (L) to (eL);\n    \n    % Box around propensity score\n    \\node[draw=blue!60, thick, rounded corners, fit=(eL), inner sep=4pt] {};\n    \\node[blue!60, anno, above=1pt of eL] {condition on this};\n\n\\end{tikzpicture}\n\\end{figure}\n```\nDAG showing how propensity score conditioning blocks confounding paths. Conditioning on the propensity score $e(L)$ blocks the confounding backdoor path $A \\leftarrow L \\rightarrow Y$, isolating the causal effect of $A$ on $Y$\n:::\n\n## The Two Core Assumptions Revisited\n\nFor propensity score methods to yield a valid causal estimate, two familiar assumptions must hold:\n\n1. **Conditional Exchangeability (Ignorability):** We must have measured a sufficient set of covariates $L$ to ensure that, within strata of $L$, treatment assignment is independent of the potential outcomes. This is the untestable assumption that there are **no unmeasured confounders**.\n2. **Positivity (Overlap):** For every combination of covariates $L$, there must be a non-zero probability of being both treated and untreated. $0 < P(A=1 \\mid L) < 1$. This means our propensity scores should not be exactly 0 or 1 for anyone. We need **common support**---regions where the propensity score distributions for the treated and untreated groups overlap.\n\n## The Three Main Propensity Score Methods\n\nOnce we have estimated the propensity score for every individual, we can use it in several ways to estimate a causal effect.\n\n1. **Propensity Score Matching (PSM):** This is the most intuitive method. The goal is to create a new dataset composed of treated and untreated individuals who are as similar as possible on their propensity scores. For each treated individual, we find one or more untreated \"twins\" with nearly identical propensity scores. All non-twins are discarded. The result is a balanced dataset where a simple comparison of outcomes is much less confounded.\n2. **Stratification (or Blocking):** We divide the sample into strata (e.g., 5 quintiles) based on the propensity score. Within each stratum, individuals have roughly the same probability of treatment, so the covariates are balanced. We calculate the treatment effect within each stratum and then compute a weighted average across strata to get the overall effect.\n3. **Inverse Probability of Treatment Weighting (IPTW):** This powerful method uses the propensity score to create weights that generate a \"pseudo-population.\"\n\t  - Individuals in the treated group get a weight of $w = 1 / e(L)$.\n\t  - Individuals in the untreated group get a weight of $w = 1 / (1 - e(L))$.\n\n    **Rationale:** A treated person who had a very low probability of treatment ($e(L)$ is small) must have been unusual. They are therefore weighted heavily to represent all the other similar people who (as expected) were not treated. Conversely, a treated person who was very likely to be treated ($e(L)$ is large) is weighted lightly. This re-weighting creates a new, synthetic population where the covariates $L$ no longer predict treatment $A$, just as in a randomized trial.\n\n# Intuitive Clarifications of Challenging Ideas\n\n## Analogy: The Expert Doctor's Dilemma\n\nImagine an expert doctor deciding whether to prescribe a risky new drug ($A=1$) or a standard therapy ($A=0$) to patients with a complex illness. The doctor's decision is based on a huge number of factors ($L$): age, weight, disease severity, lab results, comorbidities, etc.\n\n  - **The Problem:** Patients who receive the new drug are likely sicker than those who receive the standard therapy. A simple comparison of their outcomes would be deeply confounded.\n  - **The Propensity Score:** We can build a statistical model that *learns the doctor's decision-making policy*. This model, given all the patient factors $L$, predicts the probability that the doctor would have prescribed the new drug. This prediction is the propensity score.\n  - **Creating a Fair Comparison (Matching):** Now, we find a patient who got the new drug. Our model says their propensity score was 80%. This means, given their chart, there was an 80% chance the doctor would prescribe the drug. To make a fair comparison, we must find another patient who got the *standard therapy*, but whose chart was so severe that our model *also* gives them an 80% propensity score. These two patients, despite receiving different treatments, looked identical from the doctor's perspective. Comparing their outcomes is a fair, de-confounded comparison.\n\n## Misconception: The Propensity Score Model is the Causal Model\n\nThis is a critical point that is often misunderstood.\n\n| Propensity Score Model                             | Outcome Model (for Regression Adjustment)            |\n| -------------------------------------------------- | ---------------------------------------------------- |\n| **Formula:** `A ~ L`                               | **Formula:** `Y ~ A + L`                             |\n| **Goal:** Predict *treatment* assignment.          | **Goal:** Predict the *outcome*.                     |\n| **Metric of Success:** Covariate Balance.          | **Metric of Success:** Good model fit (e.g., R², AIC). |\n| **Role of Outcome:** The outcome `Y` is **NOT** used. | **Role of Outcome:** `Y` is the dependent variable.  |\n\n::: {.callout-tip}\n\n# The Two-Stage Process\n\nThink of propensity score analysis as two entirely separate steps:\n\n1. **Design Stage:** Forget the outcome exists. Your only job is to specify the best possible propensity score model to achieve balance on the covariates $L$ between the treatment groups. Use diagnostics like Love plots. This is like designing the experiment.\n2. **Analysis Stage:** Once you are satisfied with the balance, and only then, you introduce the outcome variable $Y$ to the balanced dataset (either matched or weighted) to estimate the treatment effect. This is like analyzing the results of the experiment.\n:::\n\n-----\n\n# Simple, Hand-Calculation Numerical Example(s)\n\n## Scaffolding Example: Calculating Weights for IPTW\n\nLet's use our 8-patient dataset from the previous example, now with their calculated propensity scores. Our goal is to calculate the IPTW weights and the weighted average outcome for each group.\n\n| Pt. | Age(L) | Drug(A) | Rec.(Y) | Prop. Score $e(L)$ |\n|:---:|:------:|:-------:|:-------:|:------------------:|\n| 1   | 65     | 1       | 1       | 0.56               |\n| 2   | 70     | 1       | 0       | 0.62               |\n| 3   | 50     | 1       | 1       | 0.38               |\n| 4   | 55     | 1       | 1       | 0.44               |\n| 5   | 75     | 0       | 0       | 0.68               |\n| 6   | 60     | 0       | 1       | 0.50               |\n| 7   | 45     | 0       | 1       | 0.32               |\n| 8   | 40     | 0       | 1       | 0.27               |\n\n**Step 1: Calculate the IPTW Weight for Each Patient**\nThe formula is:\n\n- If Treated (A=1), weight $w = 1 / e(L)$\n- If Untreated (A=0), weight $w = 1 / (1 - e(L))$\n\n| Pt. | A | $e(L)$ | Weight Calculation | Weight (w) |\n|:---:|:-:|:------:|:------------------:|:----------:|\n| 1   | 1 | 0.56   | $1 / 0.56$         | 1.79       |\n| 2   | 1 | 0.62   | $1 / 0.62$         | 1.61       |\n| 3   | 1 | 0.38   | $1 / 0.38$         | 2.63       |\n| 4   | 1 | 0.44   | $1 / 0.44$         | 2.27       |\n| 5   | 0 | 0.68   | $1 / (1-0.68)$     | 3.13       |\n| 6   | 0 | 0.50   | $1 / (1-0.50)$     | 2.00       |\n| 7   | 0 | 0.32   | $1 / (1-0.32)$     | 1.47       |\n| 8   | 0 | 0.27   | $1 / (1-0.27)$     | 1.37       |\n\n**Step 2: Calculate the Weighted Mean Outcome in the Treated Group**\nWe use the formula for a weighted mean: $\\frac{\\sum(w_i \\times Y_i)}{\\sum w_i}$ for all patients with $A=1$.\n\n- Numerator: $(1.79 \\times 1) + (1.61 \\times 0) + (2.63 \\times 1) + (2.27 \\times 1) = 6.69$\n- Denominator (Sum of weights for A=1): $1.79 + 1.61 + 2.63 + 2.27 = 8.30$\n- Weighted Mean Recovery (A=1): $6.69 / 8.30 = 0.806$\n\n**Step 3: Calculate the Weighted Mean Outcome in the Untreated Group**\nWe do the same for all patients with $A=0$.\n\n- Numerator: $(3.13 \\times 0) + (2.00 \\times 1) + (1.47 \\times 1) + (1.37 \\times 1) = 4.84$\n- Denominator (Sum of weights for A=0): $3.13 + 2.00 + 1.47 + 1.37 = 8.00$\n- Weighted Mean Recovery (A=0): $4.84 / 8.00 = 0.605$\n\n**Step 4: Calculate the ATE**\nThe Average Treatment Effect (ATE) is the difference between these two weighted means.\n\nATE = $0.806 - 0.605 = 0.201$\n\n**Conclusion:** After using IPTW to adjust for confounding by age, we estimate that the drug increases the probability of recovery by about 20.1 percentage points. Notice how this is different from the crude estimate, which was $(3/4) - (3/4) = 0$.\n\n# R Code Examples & Interpretation\n\nWe will use a simulated dataset where treatment `A` (1/0) has a known causal effect on outcome `Y`, confounded by a continuous variable `L1` and a binary variable `L2`.\n\n## Step 1: Simulate the Confounded Data and Check for Bias\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 2000\n# L1 (continuous) and L2 (binary) are confounders\nL1 <- rnorm(n, mean = 50, sd = 10)\nL2 <- rbinom(n, 1, 0.4)\n\n# Treatment assignment (A) depends heavily on L1 and L2\n# This creates the confounding we need to solve\nA_prob <- plogis(-4 + 0.06 * L1 + 1.1 * L2)\nA <- rbinom(n, 1, A_prob)\n\n# The outcome (Y) depends on A, L1, and L2\n# The TRUE Average Treatment Effect (ATE) of A is 5\nY <- 100 + 5 * A + 0.8 * L1 - 10 * L2 + rnorm(n, 0, 10)\n\ndf <- tibble(A = factor(A), Y, L1, L2 = factor(L2))\n```\n:::\n\n\n\n::: {#tbl-naive-regression-expanded .cell tbl-cap='Naive regression estimate of the effect of A on Y, ignoring confounding.'}\n\n```{.r .cell-code}\n# First, let's run the naive, biased regression\nbiased_model <- lm(Y ~ A, data = df)\n\nsummary(biased_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ A, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-45.907  -9.102  -0.108   9.387  44.500 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 135.9827     0.3822 355.752   <2e-16 ***\nA1            5.9884     0.6305   9.497   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.6 on 1998 degrees of freedom\nMultiple R-squared:  0.04319,\tAdjusted R-squared:  0.04272 \nF-statistic:  90.2 on 1 and 1998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The naive model estimates the effect of `A` to be 5.988 , which is more than double the true effect of 5. This massive bias is caused by the fact that individuals with higher `L1` and `L2` values are both more likely to receive the treatment and have different outcomes.\n\n## Step 2: Estimate Propensity Scores and Check Overlap\n\nThe first step in any PS analysis is to model the treatment.\n\n\n::: {.cell .column-margin}\n\n```{.r .cell-code}\n# Model treatment assignment using logistic regression\nps_model <- glm(A ~ L1 + L2, data = df, family = binomial(link = \"logit\"))\n\n# Add the predicted probabilities (propensity scores) to our data frame\ndf$pscore <- predict(ps_model, type = \"response\")\n\n# df1 <- broom::augment(ps_model, newdata = df)\n# Visualize the overlap of propensity scores. This is a critical diagnostic.\nggplot(df, aes(x = pscore, fill = A)) +\n  geom_density(alpha = 0.7) +\n  scale_fill_viridis_d(end = 0.7) +\n  labs(\n    # title = \"Propensity Score Overlap\",\n    # subtitle = \"Checking the positivity/common support assumption\",\n    x = \"Estimated Propensity Score\",\n    fill = \"Treatment (A)\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of propensity scores by treatment group. Good overlap is visible.](week-05_propensity_score-rev-1_files/figure-pdf/fig-ps-model-expanded-1.pdf){#fig-ps-model-expanded fig-pos='H'}\n:::\n:::\n\n\n**Interpretation:** The density plot shows the distribution of propensity scores for the treated ($A=1$) and untreated ($A=0$) groups. There is a good region of **common support**, meaning that for most propensity score values, there are both treated and untreated individuals. This gives us confidence that the positivity assumption holds and we can proceed.\n\n## Step 3: Method 1 - Propensity Score Matching (PSM)\n\nWe use the `MatchIt` package to find 1-to-1 \"propensity score twins.\"\n\n\n::: {#tbl-match-matching-expanded .cell tbl-cap='Covariate balance before and after matching. Balance is achieved after matching.'}\n\n```{.r .cell-code}\n# Use the matchit function to perform 1:1 nearest neighbor matching on the logit of the PS\n# Using the logit (the default) often works better than matching on the raw score\nmatch_obj <- MatchIt::matchit(\n  A ~ L1 + L2,\n  data = df,\n  method = \"nearest\",\n  distance = \"logit\"\n)\n\n# The match_obj contains information about the matching process\nsummary(match_obj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nMatchIt::matchit(formula = A ~ L1 + L2, data = df, method = \"nearest\", \n    distance = \"logit\")\n\nSummary of Balance for All Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.4495        0.3199          0.7354     1.3270    0.2105\nL1             53.5838       48.3809          0.5258     1.0699    0.1492\nL20             0.4517        0.7020         -0.5029          .    0.2503\nL21             0.5483        0.2980          0.5029          .    0.2503\n         eCDF Max\ndistance   0.3069\nL1         0.2272\nL20        0.2503\nL21        0.2503\n\nSummary of Balance for Matched Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.4495        0.4036          0.2602     1.5172    0.0544\nL1             53.5838       51.9545          0.1647     1.1635    0.0462\nL20             0.4517        0.5333         -0.1640          .    0.0816\nL21             0.5483        0.4667          0.1640          .    0.0816\n         eCDF Max Std. Pair Dist.\ndistance   0.1782          0.2606\nL1         0.0816          0.7813\nL20        0.0816          0.6179\nL21        0.0816          0.6179\n\nSample Sizes:\n          Control Treated\nAll          1265     735\nMatched       735     735\nUnmatched     530       0\nDiscarded       0       0\n```\n\n\n:::\n:::\n\n\n\n#### The R Code Explained\n\nLet's start by understanding the function call that produced this output.\n\n```r\nmatchit(formula = A ~ L1 + L2, data = df, method = \"nearest\", distance = \"logit\")\n```\n\n  - **`matchit(...)`**: This is the main function from the `MatchIt` package used to perform matching.\n  - **`formula = A ~ L1 + L2`**: This is the most critical part. It specifies the **propensity score model**.\n      - `A` (on the left of the `~`) is the **treatment (exposure) variable**. It should be a binary variable (`0/1` or `TRUE/FALSE`) indicating who received the treatment.\n      - `L1 + L2` (on the right) are the **confounders**. The formula tells `matchit` to build a model that predicts the probability of receiving treatment `A` based on the covariates `L1` and `L2`. This predicted probability is the propensity score.\n  - **`data = df`**: This specifies the data frame containing the variables `A`, `L1`, and `L2`.\n  - **`method = \"nearest\"`**: This specifies the matching algorithm. \"Nearest neighbor\" matching is one of the most common methods. For each unit in the treated group, it finds the unit in the control group with the closest propensity score.\n  - **`distance = \"logit\"`**: This tells the algorithm to perform matching based on the **logit** of the propensity score rather than the raw score itself. This is often recommended as it can better separate units with different scores, especially near 0 and 1.\n\n#### Interpreting the Output: A Step-by-Step Guide\n\nThe `matchit` output is structured into four key sections, which we will interpret one by one.\n\n#### Section 1: The \"Before\" Picture - `Summary of Balance for All Data`\n\nThis section is our baseline. It shows the state of confounding in the **original, unmatched dataset**. It tells us *why* we needed to perform matching in the first place.\n\n```r\nSummary of Balance for All Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.3972        0.2608          0.7811     1.3492    0.2273\nL1             53.1466       49.0583          0.4099     1.0427    0.1209\nL20             0.3808        0.7092         -0.6762          .    0.3284\nL21             0.6192        0.2908          0.6762          .    0.3284\n```\n\n  - **`Means Treated` / `Means Control`**: These columns show the average value of each variable for the treated and control groups, respectively. We can see large differences. For example, the mean of `L1` is 53.15 for the treated but only 49.06 for the controls.\n  - **`Std. Mean Diff.` (Standardized Mean Difference - SMD)**: 🩺 **This is the most important column for assessing balance.** It represents the difference in means between the two groups, divided by a pooled standard deviation.\n      - **Rule of Thumb:** An SMD greater than **0.1** (or sometimes 0.2) is considered indicative of a meaningful imbalance.\n      - **Interpretation:** Before matching, the SMD for `L1` is **0.41** and for `L2` is **0.68**. These are very large values, confirming that our data suffered from severe confounding. The groups were not comparable. The `distance` variable (the propensity score itself) is also highly imbalanced (SMD = 0.78), as expected.\n  - **`Var. Ratio`**: The ratio of the variance of a variable in the treated group to the control group. A value far from 1 suggests the spread of the variable is different between groups. Here, the ratios are reasonably close to 1.\n  - **`eCDF Mean` / `eCDF Max`**: These relate to the Empirical Cumulative Distribution Function. They provide a more global measure of the difference between the entire distributions of a variable, not just the mean. Large values indicate distributional imbalance.\n\n**Conclusion for Section 1:** The \"All Data\" summary clearly shows that the treated and control groups were systematically different before matching. A naive comparison of outcomes would be highly biased.\n\n#### Section 2: The \"After\" Picture - `Summary of Balance for Matched Data`\n\nThis section is the \"money shot.\" It shows the balance on the exact same covariates but for the **newly created matched dataset**. This is how we judge the success of our matching procedure.\n\n```r\nSummary of Balance for Matched Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.3972        0.3738          0.1342     1.2687    0.0247\nL1             53.1466       51.9153          0.1234     1.0797    0.0457\nL20             0.3808        0.4056         -0.0511          .    0.0248\nL21             0.6192        0.5944          0.0511          .    0.0248\n```\n\n  - **`Std. Mean Diff.`**: ✅ Look here first!\n      - For `L1`, the SMD has dropped from 0.41 to **0.12**. This is a massive improvement, though still slightly above the 0.1 threshold.\n      - For `L2`, the SMD has dropped from 0.68 to an excellent **0.05**.\n      - For the propensity score (`distance`), the SMD dropped from 0.78 to **0.13**.\n  - **`Means Treated` / `Means Control`**: Notice how the means are now much closer. The mean of `L1` is now 53.15 for the treated vs. 51.92 for the controls—a much smaller gap than before. For `L2`, the proportions are now very close (e.g., 61.9% vs 59.4%).\n  - **`Std. Pair Dist.`**: This new column shows the average standardized distance between the members of each matched pair. Smaller values are better.\n\n**Conclusion for Section 2:** The matching was highly effective. It dramatically reduced the imbalance for all covariates, bringing the SMDs much closer to zero. We have successfully created a new dataset where the treated and control groups are now highly comparable on the observed confounders `L1` and `L2`.\n\n#### Section 3: Understanding the Trade-Off - `Sample Sizes`\n\nMatching achieves balance by discarding control units that are not good \"twins\" for any treated units. This section quantifies that trade-off.\n\n```r\nSample Sizes:\n          Control Treated\nAll          1396     604\nMatched       604     604\nUnmatched     792       0\nDiscarded       0       0\n```\n\n  - **`All`**: The original dataset contained **604** treated individuals and **1396** control individuals.\n  - **`Matched`**: The new, matched dataset contains **604** treated individuals and **604** control individuals. Since we did 1-to-1 matching, every treated unit found a match.\n  - **`Unmatched`**: This is the cost of matching. **792** individuals from the control group could not be matched and were **discarded from the analysis**. No treated units were discarded.\n\n**Interpretation:** We achieved excellent covariate balance, but at the cost of losing over half of our original control group (`792 / 1396`). This has two important implications:\n\n1. **Statistical Power:** Our final analysis will have a smaller sample size, which reduces statistical power.\n2. **Estimand:** Because we kept all the treated units and found controls to match them, the causal effect we can now estimate is the **Average Treatment Effect on the Treated (ATT)**, not the Average Treatment Effect (ATE) for the whole population. Our conclusion will be about the effect of the treatment *for the kinds of people who actually received it*.\n\n## Crucial Diagnostic: Checking Covariate Balance with `cobalt`\n\nThe single most important step after any propensity score adjustment is to check if it worked. The `cobalt` package and its `love.plot` are the industry standard.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The `love.plot` is our best friend for balance checking.\nlove.plot(\n  match_obj,\n  binary = \"std\", # Standardize differences for binary covariates\n  thresholds = c(m = 0.1), # Add a vertical line for the balance threshold\n  stars = \"raw\",\n  title = \"Covariate Balance Before and After Matching\"\n) +\n  labs(\n    subtitle = \"Standardized Mean Differences (SMD) should be < 0.1 after matching\"\n  )\n```\n\n::: {.cell-output-display}\n![A Love plot showing standardized mean differences before and after matching. Balance is achieved.](week-05_propensity_score-rev-1_files/figure-pdf/fig-love-plot-expanded-1.pdf){#fig-love-plot-expanded fig-pos='H'}\n:::\n:::\n\n\n**Interpretation:** The Love plot is the primary output of our design stage.\n\n  - **Before Matching (Red):** The SMDs are very large, confirming severe confounding.\n  - **After Matching (Blue):** The SMDs are now both well below the conventional 0.1 threshold. This is our evidence that the matching has successfully created two groups that are balanced on the observed confounders $L$. We have successfully designed our \"pseudo-experiment.\"\n\n\n### The Love Plot - Your Essential Diagnostic for Causal Inference\n\nIn propensity score analysis, our first and most important job is to check whether our method—be it matching or weighting—was successful in creating balanced groups. We must do this *before* we even look at the outcome. The **Love plot** is the canonical, indispensable tool for this diagnostic task. If you are doing a propensity score analysis, you **must** produce and interpret a Love plot.\n\nThis tutorial will break down what a Love plot is, how to read it, and what to conclude from it.\n\n### 1. What is a Love Plot?\n\nA Love plot is a visualization that displays covariate balance before and after adjustment (e.g., matching or weighting). Its primary purpose is to allow you to quickly assess whether your attempt to control for confounding was successful. It's named after its creator, Dr. Thomas Love.\n\nThe plot's central metric is the **Standardized Mean Difference (SMD)**, which quantifies the difference in the average value of a covariate between the treated and control groups.\n\n### 2. The R Code Explained\n\nLet's break down the code used to generate a typical Love plot.\n\n```r\n# The `love.plot` is our best friend for balance checking.\nlove.plot(\n  match_obj,\n  binary = \"std\", # Standardize differences for binary covariates\n  thresholds = c(m = 0.1), # Add a vertical line for the balance threshold\n  stars = \"raw\",\n  title = \"Covariate Balance Before and After Matching\"\n) +\n  labs(\n    subtitle = \"Standardized Mean Differences (SMD) should be < 0.1 after matching\"\n  )\n```\n\n  - **`love.plot(match_obj, ...)`**: The function is from the `cobalt` package. Its first argument is the output object from a package like `MatchIt` or `WeightIt` (here, `match_obj`). This object contains all the information about the data before and after adjustment.\n  - **`binary = \"std\"`**: This argument specifies how to handle binary (0/1) covariates. `\"std\"` tells the function to calculate a standardized difference, which is generally recommended, making them comparable to continuous variables.\n  - **`thresholds = c(m = 0.1)`**: 🎯 **This is a key feature.** It draws a vertical dashed line on the plot at an SMD value of 0.1. This line serves as a visual **balance threshold**. Our goal is to get all the adjusted SMDs to the left of this line.\n  - **`stars = \"raw\"`**: This is a formatting choice that tells the plot to display raw (unadjusted) differences as well, which is helpful for context.\n  - **`title = \"...\"` and `labs(subtitle = \"...\")`**: These are standard `ggplot2` commands to add a title and subtitle, making the plot easier to understand.\n\n### 3. How to Interpret the Love Plot: A Visual Guide\n\nA Love plot tells a story in two parts: \"before\" and \"after.\"\n\n#### Key Visual Elements:\n\n1. **The Y-Axis (Covariates):** Each variable listed on the y-axis is a potential confounder that we tried to balance. This includes our original covariates (`L1`, `L2`) and the propensity score itself (`distance`).\n2. **The X-Axis (Standardized Mean Difference):** This is the core metric.\n      - An SMD of **0** means the average of the covariate is **identical** between the treated and control groups (perfect balance).\n      - Values **far from 0** indicate **imbalance**.\n      - The **absolute value** is what matters (e.g., -0.5 and 0.5 are equally imbalanced).\n3. **The Points (Dots):**\n      - 🔴 **Red Dots (`Unadjusted`):** These represent the SMDs in your **original, raw dataset**. This is your baseline measure of confounding.\n      - 🔵 **Blue Dots (`Adjusted`):** These represent the SMDs in your **new, matched (or weighted) dataset**. This shows the result of your adjustment.\n4. **The Dashed Line (Balance Threshold):**\n      - This is the finish line. A common rule of thumb, proposed by researchers like Rubin, is that an SMD **below 0.1** indicates a negligible, unimportant imbalance.\n\n### 4. A Step-by-Step Guide to Interpretation\n\nTo read a Love plot, you tell a simple story:\n\n**Step 1: Look at the Red Dots (The \"Before\" Story).**\n\n  - **Question:** Are the red dots far from the zero line?\n  - **Interpretation:** In almost every observational study, the answer is yes. This confirms that your original data was confounded, and the treated and control groups were not comparable. Seeing large red SMDs validates the need for your analysis.\n\n**Step 2: Look at the Blue Dots (The \"After\" Story).**\n\n  - **Question:** Are all the blue dots to the left of the dashed threshold line (i.e., absolute SMD < 0.1)?\n  - **Interpretation:**\n      - **If YES:** ✅ **Success!** Your matching/weighting procedure worked. You have successfully minimized the differences in the observed covariates, creating a \"pseudo-experiment.\" You can now proceed with confidence to the next stage: analyzing the outcome.\n      - **If NO:** 🛑 **Problem.** If one or more blue dots remain to the right of the threshold, your adjustment was not fully successful. That specific covariate is still imbalanced. You should **not** proceed to analyze the outcome. Instead, you must go back, improve your propensity score model (e.g., by adding interactions or polynomial terms), and re-run the matching until the Love plot shows good balance.\n\n**Step 3: Tell the Full Story.**\nA complete interpretation synthesizes both steps into a clear narrative. For example:\n\n> *\"The Love plot shows that prior to matching (red dots), there was severe confounding, with standardized mean differences for both L1 and L2 well above the 0.1 threshold. After performing nearest neighbor matching, the balance improved dramatically (blue dots). The SMDs for all covariates in the matched sample are now closer to the 0.1 threshold, indicating that we have managed to create more comparable groups. We may now proceed to estimate the causal effect in this more balanced sample.\"*\n\n**The Love plot is your license to proceed.** It provides the evidence and justification that your causal analysis is built on a solid foundation. Without a good Love plot, any subsequent effect estimate is suspect.\n\n## Estimate the Causal Effect on the Matched Data\n\nNow, and only now, do we analyze the outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# `match.data()` extracts the new dataset containing only the matched individuals\nmatched_data <- match.data(match_obj)\n\n# Run a simple regression on the matched data, using the weights provided by MatchIt\n# These weights account for how individuals were matched (e.g., 1 control matched to multiple treated)\nmatched_effect_model <- lm(Y ~ A, data = matched_data, weights = weights)\ntidy(matched_effect_model) |>\n  filter(term == \"A1\") |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|term | estimate| std.error| statistic| p.value|\n|:----|--------:|---------:|---------:|-------:|\n|A1   |     4.31|      0.72|      6.01|       0|\n\n\n:::\n:::\n\n\n**Interpretation:** The ATE estimate in the matched sample is 5.25. This is extremely close to the true effect of 5.0. By first achieving covariate balance, we have eliminated the confounding bias and recovered the correct causal effect.\n\n## Step 4: Method 2 - Inverse Probability of Treatment Weighting (IPTW)\n\n`WeightIt` provides a unified interface for many weighting methods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate the IPTW weights for the ATE\nweight_obj <- weightit(A ~ L1 + L2, data = df, estimand = \"ATE\")\n\n# Again, the first step is always to check balance\nlove.plot(\n  weight_obj,\n  thresholds = c(m = 0.1),\n  stars = \"raw\",\n  title = \"Covariate Balance After IPTW\"\n)\n```\n\n::: {.cell-output-display}\n![](week-05_propensity_score-rev-1_files/figure-pdf/weighting-expanded-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Run a simple regression on the original dataset, but with weights\nweighted_model <- lm(Y ~ A, data = df, weights = weight_obj$weights)\ntidy(weighted_model) |>\n  filter(term == \"A1\") |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|term | estimate| std.error| statistic| p.value|\n|:----|--------:|---------:|---------:|-------:|\n|A1   |      4.4|       0.6|      7.32|       0|\n\n\n:::\n:::\n\n\n**Interpretation:** The `love.plot` confirms that weighting also achieved excellent balance. The final estimate for the ATE from the weighted model is 4.95, again extremely close to the true value of 5. This demonstrates that IPTW is another powerful and valid method for removing confounding bias.\n\n# Hands-On R Lab\n\n## Lab: Evaluating a \"Get Out the Vote\" Campaign 🗳️\n\n**Purpose:** This lab will guide you through a complete propensity score analysis workflow. You will model treatment assignment, diagnose model performance with balance checks, and estimate a policy-relevant causal effect using both matching and weighting.\n\n**Lab Objectives:**\n\n1. Quantify the degree of confounding in an observational dataset.\n2. Estimate propensity scores and use them to assess the positivity assumption.\n3. Implement propensity score matching, critically evaluate the resulting balance, and estimate the ATE.\n4. Implement IPTW, evaluate balance, and estimate the ATE.\n5. Compare and contrast the results from the naive, matched, and weighted analyses.\n\n**Scenario:**\nYou are an analyst for a non-profit that ran a \"Get Out the Vote\" (GOTV) campaign. The intervention was a personalized letter sent to some households (`letter=1`) while others received no letter (`letter=0`). Your goal is to estimate the causal effect of this letter on voter turnout (`voted=1`). The campaign, however, did not randomize. They targeted households they believed were \"on the fence,\" using data on household income (`income`, in thousands) and the number of political signs in their yard (`signs`). You suspect these targeting variables are also direct causes of voting, making them confounders.\n\n## Task 1: Load and Explore the Data\n\nLet's generate the data and quantify the naive (confounded) association.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate confounded data for the lab\nset.seed(42)\nn_lab <- 3000\nincome <- rnorm(n_lab, 60, 20)\nsigns <- rpois(n_lab, 1.5)\nletter_prob <- plogis(-2 + 0.02 * income + 0.4 * signs)\nletter <- rbinom(n_lab, 1, letter_prob)\n\n# The true causal effect of the letter is an 8 percentage point increase in turnout\nturnout_prob <- plogis(-1.5 + 0.35 * letter + 0.015 * income + 0.5 * signs)\nvoted <- rbinom(n_lab, 1, turnout_prob)\n\ngotv_df <- tibble(voted, letter, income, signs)\n```\n:::\n\n\n**Instructions:**\n\n1. Calculate the raw difference in voting rates between the letter and no-letter groups.\n2. Use `bal.tab()` from the `cobalt` package to examine the initial state of confounding before any adjustment.\n\n```r\n#| label: student-lab-naive-expanded\n#| eval: false\n\n# TODO: Calculate the simple difference-in-means\ngotv_df |>\n  group_by(letter) |>\n  summarise(voting_rate = mean(voted))\n\n# TODO: Use bal.tab to see the initial imbalance\ncobalt::bal.tab(...)\n```\n\n### Solution to Task 1\n\n\n::: {.cell tbl-cap='Initial Covariate Imbalance'}\n\n```{.r .cell-code}\ngotv_df |>\n  group_by(letter) |>\n  summarise(voting_rate = mean(voted)) |>\n  spread(letter, voting_rate) |>\n  mutate(raw_difference = `1` - `0`)\n```\n\n::: {.cell-output-display}\n\n|         0|         1| raw_difference|\n|---------:|---------:|--------------:|\n| 0.4724939| 0.6561584|      0.1836645|\n\n:::\n\n```{.r .cell-code}\n# Use bal.tab to get a detailed table of imbalance\n\ncobalt::bal.tab(\n  letter ~ income + signs,\n  data = gotv_df,\n  un = TRUE,\n  binary = \"std\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n          Type Diff.Un\nincome Contin.   0.395\nsigns  Contin.   0.438\n\nSample sizes\n    Control Treated\nAll    1636    1364\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The raw difference in voting rates is over 17 percentage points. However, the balance table shows that the groups are severely imbalanced. The standardized mean difference for both `income` and `signs` is very large, confirming our suspicion of confounding. The \"naive\" estimate is likely very biased.\n\n\n-----\n\n## Task 2: Propensity Score Matching Workflow\n\n**Instructions:**\n\n1. Use `MatchIt` to perform 1:1 nearest neighbor matching based on `income` and `signs`.\n2. Create a Love plot to verify that balance is achieved (SMDs < 0.1).\n3. Estimate the Average Treatment Effect on the Treated (ATT) by calculating the difference-in-means on the matched dataset.\n\n```r\n#| label: student-lab-match-expanded\n#| eval: false\n\n# TODO: Perform matching, storing the result in an object\ngotv_match_obj <- matchit(...)\n\n# TODO: Create the Love Plot using the matchit object\nlove.plot(...)\n\n# TODO: Extract the matched data\ngotv_matched_data <- match.data(...)\n\n# TODO: Calculate the effect in the matched sample\ngotv_matched_data |>\n  group_by(letter) |>\n  summarise(voting_rate = mean(voted))\n```\n\n### Solution to Task 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Perform matching\n\ngotv_match_obj <- matchit(\n  letter ~ income + signs,\n  data = gotv_df,\n  method = \"nearest\"\n)\n\n# 2. Check balance\n\nlove.plot(gotv_match_obj, binary = \"std\", thresholds = c(m = 0.1))\n```\n\n::: {.cell-output-display}\n![Covariate balance for GOTV data after matching](week-05_propensity_score-rev-1_files/figure-pdf/solution-lab-match-expanded-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# 3. Estimate effect on matched data\n\ngotv_matched_data <- match.data(gotv_match_obj)\n\neffect_matched <- gotv_matched_data |>\n  group_by(letter) |>\n  summarise(voting_rate = mean(voted)) |>\n  spread(letter, voting_rate) |>\n  mutate(ATT_estimate = `1` - `0`)\n\nknitr::kable(effect_matched, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|     0|     1| ATT_estimate|\n|-----:|-----:|------------:|\n| 0.508| 0.656|        0.148|\n\n\n\nCovariate balance for GOTV data after matching\n:::\n:::\n\n\n**Interpretation:** The Love plot shows that matching did an excellent job; the blue dots are very close to zero. In the balanced matched sample, the estimated effect (the ATT) is \\~8.5 percentage points. This is much lower than the naive estimate and very close to our simulated true effect of 8!\n\n## Task 3: IPTW Workflow\n\n**Instructions:**\n\n1. Use `WeightIt` to calculate IPTW weights for the ATE.\n2. Use `bal.tab()` this time to check the balance in the weighted sample.\n3. Run a weighted regression (`glm`) to estimate the ATE.\n\n```r\n#| label: student-lab-iptw\n#| eval: false\n\n# TODO: Calculate weights\ngotv_weight_obj <- weightit(...)\n\n# TODO: Check balance on the weighted data\nbal.tab(gotv_weight_obj)\n\n# TODO: Fit a weighted logistic regression model\nweighted_glm <- glm(voted ~ letter,\n                    data = ...,\n                    weights = ...,\n                    family = quasibinomial()) # Quasibinomial is often better for weighted logistic regression\n\n# TODO: Get the average marginal effect (our risk difference)\n# This requires the `margins` package\n# install.packages(\"margins\")\nmargins::margins(weighted_glm, variables = \"letter\")\n```\n\n### Solution to Task 3\n\n```r\n#| label: solution-lab-iptw\n#| message: false\n# 1. Calculate weights\ngotv_weight_obj &lt;- weightit(letter ~ income + signs, data = gotv_df, estimand = &quot;ATE&quot;)\n\n# 2. Check balance\n\nbal.tab(gotv_weight_obj)\n\n# 3. Fit weighted model. We can use lm() for a difference in means.\n\nweighted_lm <- lm(voted ~ letter, data = gotv_df, weights = gotv_weight_obj$weights)\n\ntidy(weighted_lm) |>\nfilter(term == \"letter1\") |>\nkable(digits=3)\n\n```\n\n**Interpretation:** The balance table for the weighted data should also show excellent balance. The final regression, which accounts for the weights, estimates an ATE of about 0.081, or an 8.1 percentage point increase in voting. This result confirms the finding from our matching analysis.\n\n## Task 4: Final Reflection\n\n1. **Synthesize:** We started with a naive estimate of >17 percentage points. Our two rigorous propensity score methods both produced estimates around 8-8.5 percentage points. How would you explain this discrepancy to the campaign manager in plain, non-technical language?\n2. **Compare:** What are the conceptual differences between matching and weighting? (Hint: Think about the final sample used for analysis and the estimand).\n3. **Retrieval Quiz:**\n\t  - What is the primary purpose of a Love plot?\n\t  - What assumption are we checking when we look at the overlap of propensity score distributions?\n\t  - True or False: The coefficients in the propensity score model itself (e.g., the effect of `income` on `letter`) have a causal interpretation.\n\n# Common Pitfalls & Checks\n\n::: {.callout-warning}\n\n# The Kitchen Sink Is a Bad Propensity Score Model\n\nDo not include every available pre-treatment variable in your propensity score model. You should only include variables that you believe are **confounders** (causes of both treatment and outcome).\n\n  - Including variables related *only* to the treatment (instrumental variables) will increase the variance of your estimates.\n  - Including variables related *only* to the outcome will not reduce bias but may increase variance.\n\tYour DAG is your best guide for selecting covariates for the propensity score model.\n:::\n\n::: {.callout-important}\n\n## Balance, Balance, Balance\n\nThe credibility of your entire analysis rests on achieving good covariate balance. **Do not proceed to the outcome analysis stage if your covariates are not balanced.** If you fail to achieve balance:\n\n1. **Re-specify your propensity score model.** Try adding interactions between confounders or polynomial terms (e.g., `age + I(age^2)`).\n2. **Try a different method.** Sometimes machine learning methods like gradient boosting (available in `WeightIt`) can create better weights than logistic regression.\n3. **Acknowledge positivity violations.** If there is no overlap, you may need to restrict your analysis to a subsample with common support and change your estimand to reflect this.\n:::\n\n::: {.callout-question}\n\n## Check Your Understanding\n\n**Q:** You perform propensity score matching and your Love plot looks perfect. You then run your outcome regression and the p-value for your treatment effect is 0.25. What do you conclude?\n\n**A:** You conclude that, after successfully removing confounding bias, there is no statistical evidence of a treatment effect. The p-value's magnitude is irrelevant to the quality of your causal identification strategy. A high p-value does **not** mean your propensity score model was \"bad.\" The goal of the PS model is to achieve balance, which you did. The outcome analysis is a separate step.\n:::\n\n# Advanced Teaching Activities & Interactivity\n\n1. **Gallery Walk Critique:**\n\n\t  - **Activity:** I will pre-print several different Love plots from a hypothetical analysis. Some will show good balance, some poor balance, some positivity violations (visible from an included overlap plot).\n\t  - **Task:** In small groups, students will rotate through the \"gallery,\" discussing each plot and writing on a sticky note: (1) Their diagnosis of the plot, and (2) What they would recommend as the next step for the analyst.\n\t  - **Goal:** This fosters peer instruction and active learning focused on the most important diagnostic step.\n\n2. **Live Debate: Matching vs. Weighting:**\n\n\t  - **Setup:** Divide the class into two teams: \"Team Matching\" and \"Team Weighting.\"\n\t  - **Prompt:** \"You have a dataset with a rare outcome and some near-positivity violations. Which propensity score method would you advocate for and why?\"\n\t  - **Debate Points:** Team Matching might argue for keeping the original data structure and finding the best possible matches, even if it means reducing the sample size. Team Weighting might argue for keeping the full sample to maximize statistical power, even if it means some individuals get very large, influential weights. This surfaces the practical trade-offs between methods.\n\n3. **Interleaving Retrieval Quiz:**\n\n\t  - Q1: A variable that is a common cause of treatment and outcome is a _________. To deal with it, you should (adjust for it / not adjust for it).\n\t  - Q2: The propensity score is defined as $P(Y=1|L)$. (True/False)\n\t  - Q3: The phenomenon where conditioning on a common effect induces a spurious association is called __________ bias.\n\n# Appendix: Advanced Theory & Derivations\n\n## Derivation of the IPTW Estimator for the ATE\n\nWe aim to show why the inverse-probability weighted mean for the treated, $\\frac{\\sum w_i Y_i I(A_i=1)}{\\sum w_i I(A_i=1)}$, is a consistent estimator for the population potential outcome mean, $E[Y^1]$.\n\nLet $w_i = \\frac{I(A_i=1)}{e(L_i)} + \\frac{I(A_i=0)}{1-e(L_i)}$. The IPTW estimator for $E[Y]$ is $\\frac{1}{N} \\sum_{i=1}^N w_i Y_i$. If we want to estimate $E[Y^1]$, we can think of this as $E[\\frac{A Y}{e(L)}]$. Let's see why this works.\n\nBy the law of iterated expectations:\n\n$$\nE\\left[\\frac{A Y}{e(L)}\\right] = E\\left[E\\left[\\frac{A Y}{e(L)} \\bigg| L\\right]\\right] \n$$\n\nInside the inner expectation, $L$ is fixed, so $e(L)$ is a constant. We can pull it out:\n\n$$\n= E\\left[\\frac{1}{e(L)} E[A Y | L]\\right] \n$$\n\nBy consistency ($Y = Y^A$), we can write $A Y = A Y^1$.\n\n$$\n= E\\left[\\frac{1}{e(L)} E[A Y^1 | L]\\right] \n$$\n\nBecause potential outcomes are fixed for an individual, $Y^1$ is constant with respect to $A$ conditional on $L$.\n\n$$\n= E\\left[\\frac{1}{e(L)} Y^1 E[A | L]\\right] \n$$\n\nBy definition, $E[A|L] = P(A=1|L) = e(L)$.\n\n$$\n= E\\left[\\frac{1}{e(L)} Y^1 e(L)\\right] = E[Y^1] \n$$\n\nThus, the weighted sample mean of the outcome among the treated provides a consistent estimate of the population mean potential outcome under treatment. A symmetric proof shows that the weighted mean among the untreated consistently estimates $E[Y^0]$. The difference between these two is a consistent estimator of the ATE, $E[Y^1] - E[Y^0]$. This proof relies critically on the assumptions of consistency, positivity ($e(L)$ is never zero), and conditional exchangeability (which justifies $E[AY|L] = Y^1E[A|L]$).\n\n## References",
    "supporting": [
      "week-05_propensity_score-rev-1_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}