{
  "hash": "46b7c1d2e1184328b59f761395151310",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 7: Effect Modification\"\nsubtitle: \"Understanding Heterogeneity in Causal Effects\"\n---\n\n## 📋 Overview and Learning Objectives\n\n**Goal:** To distinguish effect modification from confounding and understand its importance in causal inference.\n\nBy the end of this session, you will be able to:\n\n1. Formally define effect modification and distinguish it from confounding\n2. Understand why the scale of measurement matters when assessing heterogeneity\n3. Identify and quantify effect modification using stratification and regression methods\n4. Interpret interaction effects on both additive and multiplicative scales\n\n::: {.callout-tip}\n## Learning Tip\n\nEffect modification is about **heterogeneity in causal effects**—the treatment works differently for different people. This is fundamentally different from confounding, which is about **bias in estimating a single average effect**. Keep this distinction clear as we proceed.\n:::\n\n## 🎯 Defining Effect Modification\n\n### Fundamental Concept\n\n**Effect modification** (also called **effect heterogeneity** or **interaction**) occurs when the causal effect of a treatment $A$ on an outcome $Y$ differs across levels of a third variable $V$.\n\n::: {.callout-important}\n## 📌 Formal Definition\n\nLet $V$ be a variable (the **effect modifier**) that takes values in some set (e.g., $V \\in \\{0, 1\\}$ for binary, or $V \\in \\RR$ for continuous).\n\n**Effect modification is present** when:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V = v} \\neq \\E{Y^{a=1} - Y^{a=0} \\mid V = v'}\n$$\n\nfor some values $v \\neq v'$.\n\nIn words: the average causal effect differs across strata defined by $V$.\n:::\n\n### Effect Modification vs. Confounding\n\nThis distinction is **critical** and often confused:\n\n| Aspect               | Effect Modification                                        | Confounding                                             |\n| :------------------- | :--------------------------------------------------------- | :------------------------------------------------------ |\n| **What it is**       | Heterogeneity in the causal effect across subgroups        | Bias in estimating the average causal effect            |\n| **The question**     | \"Does the effect differ for different people?\"             | \"Is our estimate of the average effect biased?\"         |\n| **Variable role**    | $V$ modifies the effect of $A$ on $Y$                      | $C$ affects both $A$ and $Y$, creating bias             |\n| **Causal structure** | $A \\rightarrow Y$ relationship varies by $V$               | $C \\rightarrow A$ and $C \\rightarrow Y$ (backdoor path) |\n| **Can both exist?**  | Yes! $V$ can be both a confounder AND an effect modifier   | Yes! Same variable can play both roles                  |\n| **Analysis goal**    | Estimate stratum-specific effects $\\E{Y^1 - Y^0 \\mid V=v}$ | Estimate marginal effect $\\E{Y^1 - Y^0}$ without bias   |\n\n::: {.callout-tip}\n## 🧠 Conceptual Analogy\n\nThink of **confounding** as a \"distorted lens\" that makes you see the wrong average effect.\n\nThink of **effect modification** as recognizing that different groups genuinely experience different effects—like how a medication works differently for children vs. adults.\n:::\n\n**Example to illustrate the difference:**\n\nConsider the effect of aspirin ($A$) on heart attack risk ($Y$), with age ($V$) as a third variable.\n\n- **Age as a confounder:** Older people are more likely to take aspirin AND more likely to have heart attacks (regardless of aspirin). If we don't adjust for age, we might wrongly conclude aspirin increases heart attack risk.\n- **Age as an effect modifier:** Even after adjusting for confounding, aspirin might reduce heart attacks more strongly in older adults than in younger adults. The *causal effect itself* differs by age.\n\n### Why Effect Modification Matters\n\nUnderstanding effect modification is crucial for:\n\n1. **Personalized medicine:** Identifying who benefits most (or least) from treatment\n2. **Policy targeting:** Allocating resources to subgroups with largest benefits\n3. **Understanding mechanisms:** Different effects often reveal underlying biology or social processes\n4. **Generalizability:** Effects in one population may not transfer to another\n5. **Equity considerations:** Ensuring treatments don't exacerbate health disparities\n\n## 📏 The Importance of Scale\n\nOne of the most subtle and important aspects of effect modification is that **interaction depends on the scale** of measurement. Two effects can be \"the same\" on one scale but \"different\" on another.\n\n### Additive vs. Multiplicative Scales\n\nWe can measure effects on different scales:\n\n**Additive scale (Risk Difference):**\n\n$$\n\\text{RD}_v = \\E{Y^{a=1} \\mid V=v} - \\E{Y^{a=0} \\mid V=v}\n$$\n\n**Multiplicative scale (Risk Ratio):**\n\n$$\n\\text{RR}_v = \\frac{\\E{Y^{a=1} \\mid V=v}}{\\E{Y^{a=0} \\mid V=v}}\n$$\n\n**Multiplicative scale (Odds Ratio):**\n\n$$\n\\text{OR}_v = \\frac{\\E{Y^{a=1} \\mid V=v} / (1 - \\E{Y^{a=1} \\mid V=v})}{\\E{Y^{a=0} \\mid V=v} / (1 - \\E{Y^{a=0} \\mid V=v})}\n$$\n\n::: {.callout-important}\n## Key Insight: Scale Matters\n\n**Effect modification can be present on one scale but absent on another.**\n\n- No interaction on additive scale: $\\text{RD}_{v=1} = \\text{RD}_{v=0}$\n- No interaction on multiplicative scale: $\\text{RR}_{v=1} = \\text{RR}_{v=0}$\n\nThese conditions are **generally incompatible** unless the effect is exactly zero or in special edge cases.\n:::\n\n### Detailed Numerical Example: Scale Dependency\n\nLet's work through a concrete example to see how the same data can show interaction on one scale but not another.\n\n**Scenario:** We study the effect of a new drug ($A$: 1 = treated, 0 = control) on disease occurrence ($Y$: 1 = disease, 0 = no disease), stratified by sex ($V$: 1 = female, 0 = male).\n\n**Observed data** (under conditional exchangeability):\n\n| Group           | Treatment       | $\\Prob{Y=1 \\mid A, V}$ | Sample size |\n| :-------------- | :-------------- | :--------------------- | :---------- |\n| Males ($V=0$)   | Control ($A=0$) | 0.10                   | 1000        |\n| Males ($V=0$)   | Treated ($A=1$) | 0.05                   | 1000        |\n| Females ($V=1$) | Control ($A=0$) | 0.20                   | 1000        |\n| Females ($V=1$) | Treated ($A=1$) | 0.10                   | 1000        |\n\n**Step 1: Calculate risk differences (additive scale)**\n\nFor males:\n\n$$\n\\text{RD}_{\\text{male}} = 0.05 - 0.10 = -0.05\n$$\n\nFor females:\n\n$$\n\\text{RD}_{\\text{female}} = 0.10 - 0.20 = -0.10\n$$\n\n**Comparison:**\n\n$$\n\\text{RD}_{\\text{female}} - \\text{RD}_{\\text{male}} = -0.10 - (-0.05) = -0.05\n$$\n\nThe risk difference is **twice as large** for females. There IS interaction on the additive scale.\n\n**Step 2: Calculate risk ratios (multiplicative scale)**\n\nFor males:\n\n$$\n\\text{RR}_{\\text{male}} = \\frac{0.05}{0.10} = 0.50\n$$\n\nFor females:\n\n$$\n\\text{RR}_{\\text{female}} = \\frac{0.10}{0.20} = 0.50\n$$\n\n**Comparison:**\n\n$$\n\\text{RR}_{\\text{female}} / \\text{RR}_{\\text{male}} = 0.50 / 0.50 = 1.0\n$$\n\nThe risk ratio is **identical** for both groups. There is NO interaction on the multiplicative scale.\n\n**Step 3: Interpretation**\n\n- **Additive perspective:** The treatment provides 5 percentage points of absolute risk reduction for males but 10 percentage points for females. From a public health perspective (preventing cases), the treatment is more beneficial for females.\n- **Multiplicative perspective:** The treatment cuts risk in half (50% reduction) for both males and females. The relative efficacy is the same.\n\nBoth statements are **simultaneously true**. The choice of scale affects:\n\n- Statistical testing for interaction\n- Communication to patients/policymakers\n- Resource allocation decisions\n\n::: {.callout-warning}\n## Common Pitfall: \"No Interaction\" Depends on Scale\n\nNever say simply \"there is no interaction\" without specifying the scale. A study might report \"no evidence of interaction\" because they tested on the odds ratio scale, while meaningful interaction exists on the risk difference scale (which may be more policy-relevant).\n:::\n\n### Which Scale Should We Use?\n\nThe choice depends on context:\n\n**Additive scale (Risk Difference) preferred when:**\n\n- Making public health decisions about population impact\n- Considering absolute number of cases prevented\n- Allocating limited resources\n- Assessing sufficient-component causes (mechanistic interactions)\n\n**Multiplicative scale (Risk Ratio/Odds Ratio) preferred when:**\n\n- Comparing relative efficacy across different baseline risks\n- Analyzing case-control studies (OR is natural)\n- Effects are thought to act proportionally\n- Traditional in some fields (epidemiology, clinical trials)\n\n::: {.callout-tip}\n## Practical Guidance\n\nIn most public health and policy applications, **additive interaction is more meaningful** because:\n\n1. It directly answers \"how many more cases are prevented?\"\n2. It aligns with cost-effectiveness analyses\n3. It's more interpretable to non-statisticians\n\nHowever, always report both when possible, and be explicit about which scale you're using.\n:::\n\n### Mathematical Relationship Between Scales\n\nTo understand why interaction on one scale implies interaction on another (except in special cases), consider the mathematical relationship.\n\nFor simplicity, let $p_0^v = \\Prob{Y=1 \\mid A=0, V=v}$ (baseline risk) and $p_1^v = \\Prob{Y=1 \\mid A=1, V=v}$ (treated risk).\n\n**No additive interaction means:**\n\n$$\n(p_1^{v=1} - p_0^{v=1}) = (p_1^{v=0} - p_0^{v=0})\n$$\n\n**No multiplicative interaction means:**\n\n$$\n\\frac{p_1^{v=1}}{p_0^{v=1}} = \\frac{p_1^{v=0}}{p_0^{v=0}}\n$$\n\nThese can only both be true simultaneously if:\n\n- The effect is zero: $p_1^v = p_0^v$ for all $v$\n- Special boundary cases (risks near 0 or 1)\n\n**Proof sketch for incompatibility:**\n\nSuppose no multiplicative interaction: $\\frac{p_1^1}{p_0^1} = \\frac{p_1^0}{p_0^0} = \\text{RR}$\n\nThen: $p_1^1 = \\text{RR} \\cdot p_0^1$ and $p_1^0 = \\text{RR} \\cdot p_0^0$\n\nAdditive effects:\n\n$$\n\\text{RD}^1 = p_1^1 - p_0^1 = \\text{RR} \\cdot p_0^1 - p_0^1 = p_0^1(\\text{RR} - 1)\n$$\n\n$$\n\\text{RD}^0 = p_1^0 - p_0^0 = \\text{RR} \\cdot p_0^0 - p_0^0 = p_0^0(\\text{RR} - 1)\n$$\n\nFor no additive interaction: $\\text{RD}^1 = \\text{RD}^0$\n\n$$\np_0^1(\\text{RR} - 1) = p_0^0(\\text{RR} - 1)\n$$\n\nThis requires $p_0^1 = p_0^0$ (same baseline risk) or $\\text{RR} = 1$ (no effect).\n\nThus, except in special cases, **we cannot have both no additive and no multiplicative interaction.**\n\n## 🔍 Assessing Heterogeneity: Statistical Methods\n\n### Stratification Approach\n\nThe most transparent method for assessing effect modification is **stratification**: estimate the treatment effect separately within each level of the potential modifier $V$.\n\n**Algorithm:**\n\n1. Partition the data into strata defined by $V$ (e.g., $V=0$ and $V=1$)\n2. Within each stratum, estimate the causal effect of $A$ on $Y$\n3. Compare effects across strata\n4. Test for statistical significance of differences\n\n**Advantages:**\n\n- Transparent and easy to interpret\n- No parametric assumptions about the form of interaction\n- Shows actual effect estimates in each subgroup\n\n**Disadvantages:**\n\n- Requires sufficient sample size in each stratum\n- Cannot handle continuous modifiers easily\n- Doesn't provide a single test statistic\n\n### Regression with Interaction Terms\n\nAlternatively, we can use **regression models with product terms** to test for and estimate effect modification.\n\n#### Binary Treatment and Binary Modifier\n\n**Model for the outcome:**\n\n$$\n\\E{Y \\mid A, V} = \\beta_0 + \\beta_1 A + \\beta_2 V + \\beta_3 (A \\times V)\n$$\n\n**Interpretation of coefficients:**\n\n- $\\beta_0$: Expected outcome when $A=0$ and $V=0$ (reference group)\n- $\\beta_1$: Effect of treatment when $V=0$ (the \"main effect\" of $A$)\n- $\\beta_2$: Difference in outcome between $V=1$ and $V=0$ when $A=0$\n- $\\beta_3$: **Interaction term** — additional effect of treatment when $V=1$ compared to $V=0$\n\n**Causal effects in each stratum:**\n\nWhen $V=0$:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V=0} = \\beta_1\n$$\n\nWhen $V=1$:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V=1} = \\beta_1 + \\beta_3\n$$\n\n**Test for effect modification:**\n\n- $H_0: \\beta_3 = 0$ (no effect modification)\n- $H_1: \\beta_3 \\neq 0$ (effect modification present)\n\nUse standard t-test or Wald test on $\\beta_3$.\n\n::: {.callout-important}\n### 📌 Key Point: Interactions Are Scale-Dependent\n\nThe regression model above tests for **additive interaction** (on the scale of the outcome). If you use:\n\n- **Linear regression:** Tests additive interaction on the scale of $Y$\n- **Logistic regression:** Tests multiplicative interaction on the **log-odds scale** (not risk ratio or risk difference!)\n- **Log-linear (Poisson) regression:** Tests multiplicative interaction on the log-risk scale\n\nBe very careful about interpretation!\n:::\n\n#### Detailed Numerical Example: Binary-Binary Interaction\n\nLet's use the data from Section 2.2 and fit a linear probability model.\n\n**Data structure:**\n\n| Person | $A$ | $V$ | $Y$ |\n| :----- | :-- | :-- | :-- |\n| 1      | 0   | 0   | 0   |\n| 2      | 0   | 0   | 1   |\n| ...    | ... | ... | ... |\n\nWith group-level summaries:\n\n| $A$ | $V$ | $\\bar{Y}$ | $n$  |\n| :-- | :-- | :-------- | :--- |\n| 0   | 0   | 0.10      | 1000 |\n| 1   | 0   | 0.05      | 1000 |\n| 0   | 1   | 0.20      | 1000 |\n| 1   | 1   | 0.10      | 1000 |\n\n**Step 1: Fit the linear model**\n\n$$\n\\E{Y \\mid A, V} = \\beta_0 + \\beta_1 A + \\beta_2 V + \\beta_3 (A \\times V)\n$$\n\n**Predicted values for each group:**\n\n- $A=0, V=0$: $\\hat{\\E{Y}} = \\beta_0 = 0.10$\n- $A=1, V=0$: $\\hat{\\E{Y}} = \\beta_0 + \\beta_1 = 0.05$\n- $A=0, V=1$: $\\hat{\\E{Y}} = \\beta_0 + \\beta_2 = 0.20$\n- $A=1, V=1$: $\\hat{\\E{Y}} = \\beta_0 + \\beta_1 + \\beta_2 + \\beta_3 = 0.10$\n\n**Step 2: Solve for coefficients**\n\nFrom $A=0, V=0$:\n\n$$\n\\beta_0 = 0.10\n$$\n\nFrom $A=1, V=0$:\n\n$$\n\\beta_1 = 0.05 - 0.10 = -0.05\n$$\n\nFrom $A=0, V=1$:\n\n$$\n\\beta_2 = 0.20 - 0.10 = 0.10\n$$\n\nFrom $A=1, V=1$:\n\n$$\n\\beta_3 = 0.10 - (0.10 + (-0.05) + 0.10) = 0.10 - 0.15 = -0.05\n$$\n\n**Step 3: Interpretation**\n\n- $\\hat{\\beta}_0 = 0.10$: Baseline risk for untreated males\n- $\\hat{\\beta}_1 = -0.05$: Treatment reduces risk by 5 percentage points for males\n- $\\hat{\\beta}_2 = 0.10$: Females have 10 percentage points higher baseline risk\n- $\\hat{\\beta}_3 = -0.05$: Treatment provides an **additional** 5 percentage point reduction for females\n\n**Causal effects:**\n\n- Males: $\\hat{\\beta}_1 = -0.05$\n- Females: $\\hat{\\beta}_1 + \\hat{\\beta}_3 = -0.05 + (-0.05) = -0.10$\n\nThe treatment effect is **twice as large** for females (in absolute terms).\n\n**Statistical test:** Test $H_0: \\beta_3 = 0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R code example with simulated data matching the proportions\nset.seed(123)\nn_per_group <- 1000\n\n# Create data\nA <- rep(c(0, 1, 0, 1), each = n_per_group)\nV <- rep(c(0, 0, 1, 1), each = n_per_group)\n\n# Generate outcomes based on the specified probabilities\nY <- numeric(4 * n_per_group)\nY[A == 0 & V == 0] <- rbinom(n_per_group, 1, prob = 0.10)\nY[A == 1 & V == 0] <- rbinom(n_per_group, 1, prob = 0.05)\nY[A == 0 & V == 1] <- rbinom(n_per_group, 1, prob = 0.20)\nY[A == 1 & V == 1] <- rbinom(n_per_group, 1, prob = 0.10)\n\n# Create data frame\ndata <- data.frame(Y = Y, A = A, V = V)\n\n# Fit linear probability model with interaction\nmodel <- lm(Y ~ A + V + A:V, data = data)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ A + V + A:V, data = data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-0.197 -0.115 -0.092 -0.048  0.952 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.092000   0.009869   9.322  < 2e-16 ***\nA           -0.044000   0.013957  -3.153  0.00163 ** \nV            0.105000   0.013957   7.523 6.57e-14 ***\nA:V         -0.038000   0.019738  -1.925  0.05427 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3121 on 3996 degrees of freedom\nMultiple R-squared:  0.02925,\tAdjusted R-squared:  0.02852 \nF-statistic: 40.13 on 3 and 3996 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# View coefficients\ncoef(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)           A           V         A:V \n      0.092      -0.044       0.105      -0.038 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Test for interaction\n# The interaction term is A:V\nsummary(model)$coefficients[\"A:V\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Estimate  Std. Error     t value    Pr(>|t|) \n-0.03800000  0.01973797 -1.92522300  0.05427236 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate stratum-specific effects\n# Effect in V=0 group (males)\neffect_V0 <- coef(model)[\"A\"]\n\n# Effect in V=1 group (females)\neffect_V1 <- coef(model)[\"A\"] + coef(model)[\"A:V\"]\n\ncat(\"Treatment effect for V=0 (males):\", effect_V0, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment effect for V=0 (males): -0.044 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment effect for V=1 (females):\", effect_V1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment effect for V=1 (females): -0.082 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference in effects:\", coef(model)[\"A:V\"], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference in effects: -0.038 \n```\n\n\n:::\n:::\n\n\n**Expected output interpretation:**\n\n- The coefficient for `A:V` should be close to $-0.05$ (with sampling variability)\n- The p-value tests whether this interaction is statistically significant\n- Confidence intervals quantify uncertainty in the interaction effect\n\n#### Continuous Modifier\n\nWhen $V$ is continuous (e.g., age, BMI), the interaction term represents how the treatment effect changes per unit increase in $V$.\n\n**Model:**\n\n$$\n\\E{Y \\mid A, V} = \\beta_0 + \\beta_1 A + \\beta_2 V + \\beta_3 (A \\times V)\n$$\n\n**Interpretation:**\n\n- $\\beta_3$: Change in treatment effect per 1-unit increase in $V$\n- Treatment effect at specific value $V=v$: $\\beta_1 + \\beta_3 v$\n\n**Example:** Effect of exercise program ($A$) on weight loss ($Y$), modified by baseline BMI ($V$)\n\nIf $\\hat{\\beta}_1 = -2$ kg and $\\hat{\\beta}_3 = -0.1$ kg per BMI unit:\n\n- At BMI = 25: Effect = $-2 + (-0.1)(25) = -4.5$ kg\n- At BMI = 35: Effect = $-2 + (-0.1)(35) = -5.5$ kg\n\nThe program is more effective for people with higher baseline BMI.\n\n### Assumptions and Causal Interpretation\n\nTo interpret estimated effect modification **causally**, we need:\n\n1. **Conditional exchangeability** within strata of $V$:\n\n$$\nY^a \\indep A \\mid V\n$$\n\nNo unmeasured confounding within levels of the modifier.\n\n2. **Positivity** within strata:\n\n$$\n0 < \\Prob{A=a \\mid V=v} < 1 \\text{ for all } v\n$$\n\nBoth treatment levels observed at all modifier levels.\n\n3. **Correct model specification:** The interaction term captures the true heterogeneity.\n\n::: {.callout-warning}\n## ⚠️ Common Pitfall: Confounding of Interaction\n\nIf there are **unmeasured confounders that differ across strata of $V$**, what appears to be effect modification may actually be **confounding of the interaction**.\n\n**Example:** Studying drug effectiveness by hospital. Sicker patients go to specialized hospitals. The drug appears less effective at specialized hospitals, but this could be because those patients are sicker (confounding), not because the drug truly works differently by hospital type (effect modification).\n\n**Solution:** Control for confounders within each stratum of $V$, or use methods like targeted maximum likelihood estimation (TMLE).\n:::\n\n## ✅ Worked Example: Complete Analysis\n\nLet's work through a full analysis of effect modification from start to finish.\n\n### Research Question\n\nDoes the effect of a job training program ($A$: 1 = enrolled, 0 = not enrolled) on earnings one year later ($Y$, in thousands of dollars) differ by participants' baseline education level ($V$: 1 = college degree, 0 = no degree)?\n\n### Dataset\n\nAssume we have an observational study with $n = 1000$ participants. For simplicity, assume conditional exchangeability holds after accounting for baseline covariates (age, previous earnings, etc.), which we'll suppress in this example.\n\n**Summary statistics:**\n\n| Education ($V$) | Training ($A$) | Mean $Y$ | SD $Y$ | $n$ |\n| :-------------- | :------------- | :------- | :----- | :-- |\n| No degree (0)   | No (0)         | 25       | 10     | 300 |\n| No degree (0)   | Yes (1)        | 32       | 12     | 200 |\n| College (1)     | No (0)         | 55       | 15     | 300 |\n| College (1)     | Yes (1)        | 58       | 14     | 200 |\n\n### Step 1: Stratified Analysis\n\n**Estimate effects within each education stratum:**\n\nFor $V=0$ (no college degree):\n\n$$\n\\widehat{\\text{Effect}}_{V=0} = 32 - 25 = 7 \\text{ thousand dollars}\n$$\n\nFor $V=1$ (college degree):\n\n$$\n\\widehat{\\text{Effect}}_{V=1} = 58 - 55 = 3 \\text{ thousand dollars}\n$$\n\n**Difference in effects:**\n\n$$\n7 - 3 = 4 \\text{ thousand dollars}\n$$\n\nThe training program appears to increase earnings more for those without a college degree.\n\n### Step 2: Regression with Interaction\n\n**Fit the model:**\n\n$$\n\\E{Y \\mid A, V} = \\beta_0 + \\beta_1 A + \\beta_2 V + \\beta_3 (A \\times V)\n$$\n\n**Predicted means (solving system of equations):**\n\nFrom $A=0, V=0$: $\\beta_0 = 25$\n\nFrom $A=1, V=0$: $\\beta_0 + \\beta_1 = 32 \\Rightarrow \\beta_1 = 7$\n\nFrom $A=0, V=1$: $\\beta_0 + \\beta_2 = 55 \\Rightarrow \\beta_2 = 30$\n\nFrom $A=1, V=1$: $\\beta_0 + \\beta_1 + \\beta_2 + \\beta_3 = 58$\n\n$$\n25 + 7 + 30 + \\beta_3 = 58 \\Rightarrow \\beta_3 = -4\n$$\n\n**Results:**\n\n- $\\hat{\\beta}_0 = 25$: Average earnings for untreated non-college group\n- $\\hat{\\beta}_1 = 7$: Training effect for non-college group (+$7,000)\n- $\\hat{\\beta}_2 = 30$: College graduates earn $30,000 more at baseline\n- $\\hat{\\beta}_3 = -4$: Interaction term (training effect is $4,000 less for college graduates)\n\n**Causal effects by stratum:**\n\n- Non-college: $\\hat{\\beta}_1 = 7$ thousand\n- College: $\\hat{\\beta}_1 + \\hat{\\beta}_3 = 7 + (-4) = 3$ thousand\n\n### Step 3: Statistical Testing\n\n**Test $H_0: \\beta_3 = 0$ (no effect modification)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate Data Matching the Summary Statistics\nset.seed(456)\n\n# Function to Generate Normal Data with Specified Mean and SD\ngenerate_group <- function(n, mean, sd, A, V) {\n  data.frame(\n    Y = rnorm(n, mean = mean, sd = sd),\n    A = A,\n    V = V\n  )\n}\n\n# Generate Each Group\ndata <- rbind(\n  generate_group(300, mean = 25, sd = 10, A = 0, V = 0),\n  generate_group(200, mean = 32, sd = 12, A = 1, V = 0),\n  generate_group(300, mean = 55, sd = 15, A = 0, V = 1),\n  generate_group(200, mean = 58, sd = 14, A = 1, V = 1)\n)\n\n# Fit Interaction Model\nmodel_int <- lm(Y ~ A + V + A:V, data = data)\nsummary(model_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ A + V + A:V, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-44.446  -8.432  -0.307   8.451  45.874 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  25.3416     0.7295  34.737  < 2e-16 ***\nA             8.9879     1.1535   7.792 1.65e-14 ***\nV            29.6400     1.0317  28.729  < 2e-16 ***\nA:V          -5.4249     1.6313  -3.326 0.000915 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.64 on 996 degrees of freedom\nMultiple R-squared:  0.5569,\tAdjusted R-squared:  0.5556 \nF-statistic: 417.3 on 3 and 996 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract Interaction Coefficient and Test\ninteraction_result <- summary(model_int)$coefficients[\"A:V\", ]\ncat(\"\\nInteraction term (A:V):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nInteraction term (A:V):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Estimate:\", interaction_result[\"Estimate\"], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimate: -5.424883 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Std. Error:\", interaction_result[\"Std. Error\"], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStd. Error: 1.631261 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-value:\", interaction_result[\"t value\"], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-value: -3.325576 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value:\", interaction_result[\"Pr(>|t|)\"], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.0009145714 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Stratum-specific Effects with Confidence Intervals\nlibrary(emmeans)\n\n# Estimate Marginal means\nemm <- emmeans(model_int, ~ A | V)\npairs(emm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nV = 0:\n contrast estimate   SE  df t.ratio p.value\n A0 - A1     -8.99 1.15 996  -7.792  <.0001\n\nV = 1:\n contrast estimate   SE  df t.ratio p.value\n A0 - A1     -3.56 1.15 996  -3.089  0.0021\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or Manually Calculate:\n# Effect in V=0\nbeta_A <- coef(model_int)[\"A\"]\nse_A <- summary(model_int)$coefficients[\"A\", \"Std. Error\"]\n\n# Effect in V=1\nbeta_A_V1 <- coef(model_int)[\"A\"] + coef(model_int)[\"A:V\"]\nse_A_V1 <- sqrt(\n  vcov(model_int)[\"A\", \"A\"] +\n    vcov(model_int)[\"A:V\", \"A:V\"] +\n    2 * vcov(model_int)[\"A\", \"A:V\"]\n)\n\ncat(\"\\n--- Stratum-Specific Effects ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Stratum-Specific Effects ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"V=0 (No College):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nV=0 (No College):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Effect:\", beta_A, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Effect: 8.987925 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  95% CI: [\", beta_A - 1.96 * se_A, \",\", beta_A + 1.96 * se_A, \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CI: [ 6.727112 , 11.24874 ]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nV=1 (College):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nV=1 (College):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Effect:\", beta_A_V1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Effect: 3.563042 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"  95% CI: [\",\n  beta_A_V1 - 1.96 * se_A_V1,\n  \",\",\n  beta_A_V1 + 1.96 * se_A_V1,\n  \"]\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  95% CI: [ 1.302229 , 5.823854 ]\n```\n\n\n:::\n:::\n\n\n### Step 4: Interpretation and Reporting\n\n**Statistical conclusion:**\nIf $p < 0.05$ for $\\beta_3$, we reject the null hypothesis of no effect modification. There is statistically significant evidence that education level modifies the effect of job training on earnings.\n\n**Substantive interpretation:**\nThe job training program increases earnings for both groups, but the benefit is larger (by approximately $4,000) for individuals without a college degree. This suggests:\n\n1. **Targeting:** Programs may be more cost-effective when targeted to non-college populations\n2. **Mechanisms:** College graduates may already have skills that the training provides, leading to smaller marginal benefits\n3. **Policy:** This is evidence of **heterogeneous treatment effects** relevant for resource allocation\n\n**Report format:**\n\n> \"We found significant effect modification by education level (interaction p = 0.XX). Among participants without a college degree, the training program increased earnings by \\$7,000 (95% CI: [X, Y]). Among college graduates, the effect was smaller: \\$3,000 (95% CI: [X, Y]). The difference in effects was statistically significant ($\\beta_3 = -4$, SE = Z, p = 0.XX), indicating that the training program is more beneficial for those without prior college education.\"\n\n## 📊 Visualizing Effect Modification\n\nEffective visualization is crucial for communicating heterogeneous effects.\n\n<!-- ### Forest Plots\n\nShow estimated effects and confidence intervals for each subgroup:\n\n```r\n# Create Data for Forest Plot\nlibrary(ggplot2)\n\nsubgroup_results <- data.frame(\n    Subgroup = c(\"No College Degree\", \"College Degree\"),\n    Effect = c(7, 3),\n    Lower = c(5.5, 1.2), # hypothetical CIs\n    Upper = c(8.5, 4.8)\n)\n\nggplot(subgroup_results, aes(x = Subgroup, y = Effect)) +\n    geom_point(size = 3) +\n    geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0.2) +\n    geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n    coord_flip() +\n    labs(\n        title = \"Job Training Effect on Earnings by Education Level\",\n        y = \"Treatment Effect (thousands of dollars)\",\n        x = \"\"\n    ) +\n    theme_minimal()\n``` \n-->\n\n### Interaction Plots\n\nFor continuous modifiers, plotthe predicted treatment effect as a function of the modifier:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example with Continuous Modifier (e.g., age)\n# Assume We Have Age as a Continuous Variable instead of Education\n\npacman::p_load(ggplot2, dplyr, viridis)\n# Simulate Data with Age as Modifier\nset.seed(789)\nn <- 1000\nage <- runif(n, 18, 65)\nA <- rbinom(n, 1, 0.5)\nY <- 30 + 5 * A - 0.2 * age + 0.15 * A * age + rnorm(n, 0, 10)\n\ndata_age <- data.frame(Y = Y, A = A, age = age)\n\n# Fit Model with Continuous Interaction\nmodel_age <- lm(Y ~ A + age + A:age, data = data_age)\n\n# Create Prediction Data\npred_data <- expand.grid(\n  A = c(0, 1),\n  age = seq(18, 65, by = 1)\n)\n\npred_data$Y_pred <- predict(model_age, newdata = pred_data)\n\n# Plot\nggplot(\n  pred_data,\n  aes(x = age, y = Y_pred, color = factor(A), linetype = factor(A))\n) +\n  geom_line(size = 1) +\n  scale_color_manual(\n    values = c(\"0\" = \"blue\", \"1\" = \"red\"),\n    labels = c(\"Control\", \"Treated\"),\n    name = \"Treatment\"\n  ) +\n  scale_linetype_manual(\n    values = c(\"0\" = \"solid\", \"1\" = \"solid\"),\n    labels = c(\"Control\", \"Treated\"),\n    name = \"Treatment\"\n  ) +\n  labs(\n    title = \"Predicted Outcomes by Treatment and Age\",\n    subtitle = \"Interaction between treatment and age\",\n    x = \"Age (years)\",\n    y = \"Predicted Earnings (thousands)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-09_effect_modification-rev1_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Calculate and Plot Treatment Effect as Function of Age\neffect_data <- data.frame(\n  age = seq(18, 65, by = 1)\n)\neffect_data$effect <- coef(model_age)[\"A\"] +\n  coef(model_age)[\"A:age\"] * effect_data$age\n\nggplot(effect_data, aes(x = age, y = effect)) +\n  geom_line(size = 1, color = \"darkgreen\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Treatment Effect as a Function of Age\",\n    x = \"Age (years)\",\n    y = \"Treatment Effect (thousands)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](week-09_effect_modification-rev1_files/figure-pdf/unnamed-chunk-3-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Heatmaps for Multiple Modifiers\n\nWhen examining multiple potential effect modifiers simultaneously:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example with Two Modifiers: Education and Baseline Income\n# This is for Illustration only\n\nlibrary(viridis)\n\n# Create Hypothetical Effect Estimates across Two Modifiers\neffect_matrix <- expand.grid(\n  education = c(\"No HS\", \"HS\", \"Some College\", \"College+\"),\n  income_quartile = c(\"Q1\", \"Q2\", \"Q3\", \"Q4\")\n)\n\n# Simulate Effect Sizes (for illustration)\nset.seed(101)\neffect_matrix$effect <- rnorm(16, mean = 5, sd = 2)\n\nggplot(effect_matrix, aes(x = education, y = income_quartile, fill = effect)) +\n  geom_tile(color = \"white\") +\n  geom_text(aes(label = round(effect, 1)), color = \"white\", size = 4) +\n  scale_fill_viridis(name = \"Treatment\\nEffect\") +\n  labs(\n    title = \"Treatment Effect by Education and Income\",\n    x = \"Education Level\",\n    y = \"Baseline Income Quartile\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](week-09_effect_modification-rev1_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## 🧮 Mathematical Framework and Derivations\n\n### Formal Definition of Effect Modification\n\nLet's formalize effect modification in the potential outcomes framework.\n\n**Definition (Effect Modification on Additive Scale):**\n\nEffect modification by $V$ is present when there exist values $v, v' \\in \\mathcal{V}$ such that:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V = v} \\neq \\E{Y^{a=1} - Y^{a=0} \\mid V = v'}\n$$\n\nEquivalently:\n\n$$\n\\E{Y^{a=1} \\mid V = v} - \\E{Y^{a=0} \\mid V = v} \\neq \\E{Y^{a=1} \\mid V = v'} - \\E{Y^{a=0} \\mid V = v'}\n$$\n\n**Definition (Effect Modification on Multiplicative Scale):**\n\nEffect modification by $V$ is present on the ratio scale when:\n\n$$\n\\frac{\\E{Y^{a=1} \\mid V = v}}{\\E{Y^{a=0} \\mid V = v}} \\neq \\frac{\\E{Y^{a=1} \\mid V = v'}}{\\E{Y^{a=0} \\mid V = v'}}\n$$\n\n### Identification Under Conditional Exchangeability\n\n**Assumption (Conditional Exchangeability within Strata of $V$):**\n\n$$\nY^a \\indep A \\mid V \\quad \\text{for all } a\n$$\n\n**Theorem (Identification of Stratum-Specific Effects):**\n\nUnder conditional exchangeability and positivity within strata, the stratum-specific average causal effect is identified:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V = v} = \\E{Y \\mid A=1, V=v} - \\E{Y \\mid A=0, V=v}\n$$\n\n**Proof:**\n\nStart with the left-hand side:\n\n$$\n\\E{Y^{a=1} - Y^{a=0} \\mid V = v}\n$$\n\nBy linearity of expectation:\n\n$$\n= \\E{Y^{a=1} \\mid V = v} - \\E{Y^{a=0} \\mid V = v}\n$$\n\nUnder conditional exchangeability ($Y^a \\indep A \\mid V$), we have:\n\n$$\n\\E{Y^a \\mid V = v} = \\E{Y^a \\mid A=a, V = v}\n$$\n\nBy consistency ($Y = Y^A$ when $A=a$ is realized):\n\n$$\n\\E{Y^a \\mid A=a, V = v} = \\E{Y \\mid A=a, V = v}\n$$\n\nTherefore:\n\n$$\n\\E{Y^{a=1} \\mid V = v} - \\E{Y^{a=0} \\mid V = v} = \\E{Y \\mid A=1, V=v} - \\E{Y \\mid A=0, V=v}\n$$\n\nThis shows we can estimate causal effects within strata using observed data. $\\square$\n\n### Variance of Interaction Effects\n\nWhen we estimate $\\beta_3$ in the regression model, understanding its variance is important for inference.\n\n**Linear Model:**\n\n$$\nY_i = \\beta_0 + \\beta_1 A_i + \\beta_2 V_i + \\beta_3 (A_i \\times V_i) + \\epsilon_i\n$$\n\nwhere $\\epsilon_i \\sim N(0, \\sigma^2)$ independently.\n\n**Design matrix** (for $n$ observations):\n\n$$\n\\mathbf{X} =\n\\begin{bmatrix} 1 & A_1 & V_1 & A_1 V_1 \\\\\n1 & A_2 & V_2 & A_2 V_2 \\\\\n\\vdots & \\vdots & \\vdots & \\vdots \\\\\n1 & A_n & V_n & A_n V_n \\end{bmatrix}\n$$\n\n**Variance-covariance matrix of $\\hat{\\boldsymbol{\\beta}}$:**\n\n$$\n\\var{\\hat{\\boldsymbol{\\beta}}} = \\sigma^2 (\\mathbf{X}^\\top \\mathbf{X})^{-1}\n$$\n\nThe variance of the interaction coefficient is the $(4,4)$ element:\n\n$$\n\\var{\\hat{\\beta}_3} = \\sigma^2 [(\\mathbf{X}^\\top \\mathbf{X})^{-1}]_{44}\n$$\n\n::: {.callout-tip}\n### 🧠 Intuition for Interaction Variance\n\nThe variance of $\\hat{\\beta}_3$ depends on:\n\n1. **Sample size:** Larger $n$ reduces variance\n2. **Distribution of $(A, V)$:** Variance is smallest when we have balanced samples across all four combinations $(A=0, V=0)$, $(A=1, V=0)$, $(A=0, V=1)$, $(A=1, V=1)$\n3. **Outcome variance $\\sigma^2$:** More noise in $Y$ increases uncertainty\n4. **Correlation structure:** If $A$ and $V$ are highly correlated, interaction estimation becomes difficult (multicollinearity)\n\n**Practical implication:** Testing for interactions requires larger sample sizes than testing main effects. As a rule of thumb, you need **4 times the sample size** to detect an interaction of the same magnitude as a main effect with the same power.\n:::\n\n### Relationship to Sufficient-Component Causes\n\nIn epidemiology, **sufficient-component cause models** provide a mechanistic interpretation of interaction.\n\n**Framework:**\n- A **sufficient cause** is a set of conditions that inevitably produce the outcome\n- Each sufficient cause consists of multiple **component causes**\n- The outcome occurs when any sufficient cause is completed\n\n**Example:** Disease ($Y=1$) occurs if:\n- Sufficient cause 1: Genetic susceptibility ($G$) AND environmental exposure ($E$)\n- Sufficient cause 2: High viral load ($V$) alone\n\n**Additive interaction** corresponds to **synergism** in the sufficient-component cause framework:\n\nTwo factors $A$ and $V$ show synergism if they work together in at least one sufficient cause.\n\n**Measure of synergism:**\n\nThe **Relative Excess Risk due to Interaction (RERI)**:\n\n$$\n\\text{RERI} = \\text{RR}_{11} - \\text{RR}_{10} - \\text{RR}_{01} + 1\n$$\n\nwhere $\\text{RR}_{av}$ denotes the risk ratio for $A=a, V=v$ relative to $A=0, V=0$.\n\nIf $\\text{RERI} > 0$: **Synergism** (positive additive interaction)\nIf $\\text{RERI} < 0$: **Antagonism** (negative additive interaction)\nIf $\\text{RERI} = 0$: No interaction on additive scale\n\n**Derivation of RERI:**\n\nLet $p_{av} = \\Prob{Y=1 \\mid A=a, V=v}$ and $p_{00} = \\Prob{Y=1 \\mid A=0, V=0}$ be the baseline risk.\n\nRisk ratios:\n\n$$\n\\text{RR}_{11} = \\frac{p_{11}}{p_{00}}, \\quad \\text{RR}_{10} = \\frac{p_{10}}{p_{00}}, \\quad \\text{RR}_{01} = \\frac{p_{01}}{p_{00}}\n$$\n\nRisk differences:\n\n$$\n\\text{RD}_{11} = p_{11} - p_{00}, \\quad \\text{RD}_{10} = p_{10} - p_{00}, \\quad \\text{RD}_{01} = p_{01} - p_{00}\n$$\n\nAdditive interaction is:\n\n$$\n\\text{RD}_{11} - \\text{RD}_{10} - \\text{RD}_{01} = (p_{11} - p_{00}) - (p_{10} - p_{00}) - (p_{01} - p_{00})\n$$\n\n$$\n= p_{11} - p_{10} - p_{01} + p_{00}\n$$\n\nConverting to relative scale by dividing by $p_{00}$:\n\n$$\n\\frac{p_{11} - p_{10} - p_{01} + p_{00}}{p_{00}} = \\frac{p_{11}}{p_{00}} - \\frac{p_{10}}{p_{00}} - \\frac{p_{01}}{p_{00}} + 1\n$$\n\n$$\n= \\text{RR}_{11} - \\text{RR}_{10} - \\text{RR}_{01} + 1 = \\text{RERI}\n$$\n\n**Example calculation:**\n\n| $A$ | $V$ | $p_{av}$ | $\\text{RR}_{av}$ |\n| :-- | :-- | :------- | :--------------- |\n| 0   | 0   | 0.01     | 1.00             |\n| 1   | 0   | 0.03     | 3.00             |\n| 0   | 1   | 0.02     | 2.00             |\n| 1   | 1   | 0.08     | 8.00             |\n\n$$\n\\text{RERI} = 8.00 - 3.00 - 2.00 + 1 = 4.00\n$$\n\nInterpretation: 4 times as many cases occur due to the joint action of $A$ and $V$ than would be expected from their independent effects. This indicates strong synergism.\n\n## ⚠️ Common Pitfalls and Misconceptions\n\n### Confusing Statistical and Biological Interaction\n\n::: {.callout-warning}\n### ⚠️ Pitfall: Interaction Terminology\n\nThe term \"interaction\" is used differently across disciplines:\n\n- **Statistical interaction:** Departure from additivity in a statistical model (scale-dependent)\n- **Biological interaction:** Joint action of causes in producing disease (mechanistic)\n- **Pharmacological interaction:** When drugs affect each other's mechanisms\n\nThese are related but distinct concepts. Statistical interaction doesn't necessarily imply a biological mechanism, and vice versa.\n:::\n\n### Multiple Testing Problem\n\nWhen examining many potential effect modifiers, false positives become likely.\n\n**Problem:** If you test 20 subgroup effects at $\\alpha = 0.05$, you expect 1 false positive even if no true effect modification exists.\n\n**Solutions:**\n\n1. **Pre-specification:** Declare effect modifiers of interest a priori based on theory\n2. **Multiple testing correction:** Use Bonferroni, FDR, or hierarchical testing procedures\n3. **Replication:** Confirm findings in independent datasets\n4. **Effect size consideration:** Don't rely solely on p-values; consider magnitude and clinical relevance\n\n::: {.callout-tip}\n### 🧠 Best Practice\n\nIn your analysis plan, specify:\n\n- Primary effect modifier(s) to be tested with full $\\alpha = 0.05$\n- Secondary (exploratory) modifiers tested at adjusted significance levels\n- How results will be interpreted differently for confirmatory vs. exploratory analyses\n\nThis prevents \"fishing\" for significant subgroups post-hoc.\n:::\n\n### 6.3 Power for Interaction Detection\n\n::: {.callout-important}\n### 📌 Critical Statistical Fact\n\nDetecting interactions requires much larger sample sizes than detecting main effects.\n\n**Rule of thumb:** To achieve the same power to detect an interaction of size $\\delta$ as a main effect of size $\\delta$, you need approximately **4 times the sample size**.\n\n**Why?** The interaction term $A \\times V$ has less variance explained because it's the product of two variables, and fewer observations inform the interaction parameter.\n:::\n\n**Example:**\n\n- To detect a main effect of $\\delta = 0.3$ with 80% power requires $n = 176$\n- To detect an interaction of $\\delta = 0.3$ with 80% power requires $n = 704$\n\n**Implication:** Many studies are underpowered for subgroup analyses. Non-significant interaction tests should be interpreted cautiously—absence of evidence is not evidence of absence.\n\n### Simpson's Paradox and Collider Bias\n\n::: {.callout-warning}\n### ⚠️ Danger: Conditioning on Colliders\n\nStratifying by certain variables can **induce** spurious associations or mask true ones.\n\nIf $V$ is a **collider** (caused by both $A$ and $Y$, or by their common causes), conditioning on $V$ opens a non-causal path and biases effect estimates.\n:::\n\n**Example:**\n\n```\nA → Y\n↓   ↓\n  V\n```\n\nHere, $V$ is a collider. Stratifying by $V$ induces a spurious association between $A$ and $Y$ even if there's no causal effect.\n\n**Implication:** Not every variable is a valid effect modifier for causal analysis. Use causal diagrams (DAGs) to determine whether conditioning on $V$ is appropriate.\n\n### Measurement Error in Modifiers\n\nIf the effect modifier $V$ is measured with error, interaction effects may be attenuated (bias toward the null) or distorted.\n\n**Example:** If age is the true modifier but is self-reported with error, the estimated interaction $\\hat{\\beta}_3$ will underestimate the true interaction.\n\n## 🎓 Advanced Topics: Multiple Effect Modifiers\n\n### Three-Way Interactions\n\nWhen multiple variables modify effects, we can have higher-order interactions.\n\n**Model with two modifiers $V$ and $W$:**\n\n$$\n\\E{Y \\mid A, V, W} = \\beta_0 + \\beta_1 A + \\beta_2 V + \\beta_3 W + \\beta_4 (A \\times V) + \\beta_5 (A \\times W) + \\beta_6 (V \\times W) + \\beta_7 (A \\times V \\times W)\n$$\n\n**Interpretation of $\\beta_7$:** The three-way interaction captures whether the effect modification by $V$ itself differs across levels of $W$.\n\n**Example:**\n\n- Drug effect ($A$) modified by genotype ($V$) and sex ($W$)\n- $\\beta_7 \\neq 0$ means: \"The genotype's modification of the drug effect is different for males vs. females\"\n\n**Caution:** Three-way interactions are hard to interpret and require very large samples. Use sparingly and only when theoretically motivated.\n\n### Machine Learning for Heterogeneous Effects\n\nModern methods allow flexible discovery of effect modification without pre-specifying functional forms:\n\n**Approaches:**\n\n1. **Causal trees/forests:** Partition covariate space to find subgroups with different effects\n   - Random forests adapted for treatment effect estimation\n   - Algorithms: `grf` package in R (Generalized Random Forests)\n\n2. **BART (Bayesian Additive Regression Trees):** Nonparametric Bayesian method\n   - Automatically captures interactions\n   - Provides uncertainty quantification\n\n3. **Meta-learners:** Two-stage approaches\n   - S-learner: Single model with treatment-covariate interactions\n   - T-learner: Separate models for treated and control\n   - X-learner: More efficient combination\n\n**Example with Causal Forests:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install if Needed: install.packages(\"grf\")\npacman::p_load(grf)\n\n# Simulate Data\nset.seed(999)\nn <- 2000\nX <- matrix(runif(n * 5), n, 5) # 5 covariates\nW <- rbinom(n, 1, 0.5) # Treatment\n\n# True Heterogeneous Effect: Effect Depends on X1 and X2\ntau <- 1 + 2 * X[, 1] + 3 * (X[, 2] > 0.5)\nY <- tau * W + X[, 1] + X[, 2] + rnorm(n)\n\n# Fit Causal Forest\ncf <- causal_forest(X, Y, W)\n\n# Predict Individual Treatment Effects\ntau_hat <- predict(cf)$predictions\n\n# Variable Importance for Effect Heterogeneity\nvar_imp <- variable_importance(cf)\nplot(var_imp)\n```\n\n::: {.cell-output-display}\n![](week-09_effect_modification-rev1_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Estimate Average Treatment Effect\naverage_treatment_effect(cf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n estimate   std.err \n3.5723938 0.0578814 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Best Linear Projection: Which Variables Drive Heterogeneity?\nblp <- best_linear_projection(cf, X)\nprint(blp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBest linear projection of the conditional average treatment effect.\nConfidence intervals are cluster- and heteroskedasticity-robust (HC3):\n\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)  0.67583    0.19505  3.4649 0.0005415 ***\nA1           2.22901    0.17372 12.8310 < 2.2e-16 ***\nA2           4.23645    0.16080 26.3454 < 2.2e-16 ***\nA3          -0.21001    0.16887 -1.2436 0.2137932    \nA4          -0.23508    0.16913 -1.3899 0.1647108    \nA5          -0.19268    0.17321 -1.1124 0.2661044    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**Advantages:**\n\n- Data-driven discovery of effect modifiers\n- Handles complex, nonlinear interactions\n- No need to pre-specify interaction terms\n\n**Disadvantages:**\n\n- Less interpretable than simple regression\n- Requires larger samples\n- Risk of overfitting without proper validation\n\n## 📝 Summary and Key Takeaways\n\n::: {.callout-tip}\n## 🧠 Key Concepts to Remember\n\n1. **Effect modification** is about heterogeneity in causal effects, NOT bias in estimation (that's confounding)\n2. **Scale matters critically:** Interaction on additive scale ≠ interaction on multiplicative scale (except in special cases)\n3. **Additive scale** (risk difference) is usually more relevant for public health and policy decisions\n4. **Identification requires:** Conditional exchangeability within strata of the effect modifier\n5. **Analysis methods:**\n   - Stratification: Transparent but limited to categorical modifiers\n   - Regression interactions: Flexible but requires correct specification\n   - Machine learning: Data-driven but less interpretable\n\n6. **Pitfalls to avoid:**\n   - Multiple testing without correction\n   - Underpowered interaction tests\n   - Conditioning on colliders\n   - Confusing statistical and biological interaction\n\n7. **Reporting:** Always specify the scale, provide stratum-specific effects with confidence intervals, and be transparent about pre-specification vs. exploratory analyses\n:::\n\n## ❓ Check Your Understanding\n\n::: {.callout-question}\n## Question 1: Distinguishing Concepts\n\nA study finds that age is associated with both statin use and cardiovascular disease risk. Additionally, statins reduce CVD risk more in older patients than younger patients.\n\n**Which of the following is true?**\n\nA) Age is only a confounder\nB) Age is only an effect modifier\nC) Age is both a confounder and an effect modifier\nD) Age is neither a confounder nor an effect modifier\n\n<details>\n<summary>Click for answer</summary>\n\n**Answer: C**\n\nAge is a **confounder** because it affects both treatment (older people more likely to take statins) and outcome (older people at higher baseline risk). It's also an **effect modifier** because the causal effect of statins differs by age group. The same variable can play both roles simultaneously. To estimate unbiased stratum-specific effects, we need to account for age as a confounder within each age stratum if there are other age-related confounders.\n</details>\n:::\n\n::: {.callout-question}\n## Question 2: Scale Dependency\n\nA vaccine reduces disease risk from 20% to 10% in adults and from 10% to 5% in children.\n\n**Calculate:**\na) Risk differences in each group\nb) Risk ratios in each group\nc) Is there effect modification on the additive scale?\nd) Is there effect modification on the multiplicative scale?\n\n<details>\n<summary>Click for answer</summary>\n\n**a) Risk differences:**\n- Adults: $0.10 - 0.20 = -0.10$ (10 percentage point reduction)\n- Children: $0.05 - 0.10 = -0.05$ (5 percentage point reduction)\n\n**b) Risk ratios:**\n- Adults: $0.10 / 0.20 = 0.50$ (50% of original risk)\n- Children: $0.05 / 0.10 = 0.50$ (50% of original risk)\n\n**c) Additive scale:** YES, effect modification present\nThe absolute risk reduction differs ($-0.10$ vs $-0.05$)\n\n**d) Multiplicative scale:** NO effect modification\nThe relative risk is identical ($0.50$ in both groups)\n\n**Interpretation:** The vaccine cuts risk in half for both groups (same relative efficacy), but prevents twice as many cases per 100 people in adults because their baseline risk is higher. For resource allocation, the additive perspective may be more relevant.\n</details>\n:::\n\n::: {.callout-question}\n## Question 3: Regression Interpretation\n\nYou fit the model: $\\E{Y \\mid A, V} = 50 + 10A + 20V - 5(A \\times V)$\n\nwhere $Y$ is blood pressure, $A$ is medication (1=yes, 0=no), and $V$ is diabetes status (1=yes, 0=no).\n\n**What is the treatment effect for:**\na) Non-diabetic patients ($V=0$)?\nb) Diabetic patients ($V=1$)?\nc) Interpret the interaction coefficient $-5$.\n\n<details>\n<summary>Click for answer</summary>\n\n**a) Non-diabetic patients ($V=0$):**\n\n$$\n\\E{Y \\mid A=1, V=0} - \\E{Y \\mid A=0, V=0} = (50 + 10) - (50) = 10\n$$\n\nThe medication reduces blood pressure by 10 units.\n\n**b) Diabetic patients ($V=1$):**\n\n$$\n\\E{Y \\mid A=1, V=1} - \\E{Y \\mid A=0, V=1} = (50 + 10 + 20 - 5) - (50 + 20) = 5\n$$\n\nThe medication reduces blood pressure by only 5 units.\n\n**c) Interpretation of $-5$:**\n\nThe interaction coefficient of $-5$ means that the medication is 5 units less effective for diabetic patients compared to non-diabetic patients. Equivalently, diabetes reduces the treatment effect by 5 units. This suggests diabetes may interfere with the medication's mechanism or that diabetic patients have different underlying pathophysiology.\n</details>\n:::\n",
    "supporting": [
      "week-09_effect_modification-rev1_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}