{
  "hash": "cc78b5d61a69cf9018066fd9c0f78f0b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Instrumental Variables (IV) Estimation\"\n---\n\n## Overview\n\nWelcome to Week 8. To this point in the course, our methods for causal inference have all relied on a single, powerful, but untestable assumption: **conditional exchangeability**. We have assumed that we have measured a sufficient set of covariates, $L$, to control for all common causes of the treatment and outcome. But what if we haven't? What if there is a strong, unmeasured confounder—like genetic predisposition, patient motivation, or latent \"ability\"—that we simply cannot adjust for?\n\nIn this scenario, all our previous methods (regression, matching, weighting, g-computation) will fail to produce an unbiased estimate. This week, we introduce a fundamentally different and remarkably clever approach for when the \"no unmeasured confounding\" assumption is untenable: **Instrumental Variables (IV)**.\n\nThe IV method leverages a special kind of variable—the instrument, $Z$—that is \"as-if\" randomly assigned and influences the treatment but has no direct effect on the outcome. By exploiting the exogenous variation in the treatment induced by this instrument, we can isolate the causal effect of the treatment, even in the presence of strong unmeasured confounding. However, this power comes with a significant trade-off. As we will see, the IV estimate does not typically recover the Average Treatment Effect (ATE) for the whole population, but rather a **Local Average Treatment Effect (LATE)** for the specific subpopulation of \"compliers\" whose behavior is changed by the instrument.\n\n## Learning Objectives\n\nBy the end of this week's module and lab, you will be able to:\n\n1. **Define** an instrumental variable and articulate the three core IV assumptions: Relevance, Exclusion Restriction, and Exchangeability.\n2. **Represent** the causal structure of an IV analysis on a Directed Acyclic Graph (DAG) and explain how the instrument isolates a causal pathway despite an open backdoor path.\n3. **Calculate** the IV estimate of a causal effect by hand using the Wald estimator (the ratio of the reduced form to the first stage).\n4. **Implement** a two-stage least squares (2SLS) regression in R using the `ivreg` package to estimate a causal effect.\n5. **Define** the Local Average Treatment Effect (LATE) and the \"complier\" subpopulation it applies to, and contrast this with the Average Treatment Effect (ATE).\n\n## R Packages\n\nThis week, we'll introduce the `ivreg` package, the standard for IV estimation in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) {\n  install.packages(\"pacman\")\n}\npacman::p_load(\n  tidyverse, # For data manipulation and visualization\n  ggdag, # For plotting DAGs\n  dagitty, # For DAG logic\n  broom, # For tidying model outputs\n  knitr, # For table formatting\n  ivreg, # For instrumental variable regression\n  stargazer # For creating comparison tables of models\n)\n\n# A consistent plot theme\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\n## Comprehensive Topic Explanation\n\n### The Problem: Unmeasured Confounding\n\nAll methods we have studied thus far—regression, matching, IPTW, g-computation—are designed to control for confounding by adjusting for a measured set of covariates $L$. They all fail if there is an unmeasured common cause, $U$, of the treatment $A$ and outcome $Y$.\n\n```tikz\n\\begin{tikzpicture}[node distance=2.5cm, main/.style={draw, circle, minimum size=1cm}]\n    % Nodes\n    \\node[main] (A) {$A$};\n    \\node[main] (Y) [right of=A, xshift=1cm] {$Y$};\n    \\node[main, dashed] (U) [above of=A, xshift=1.75cm] {$U$};\n\n    % Paths\n    \\path[->, thick, blue] (A) edge node[above, midway] {Causal Path} (Y);\n    \\path[->, thick, red] (U) edge (A);\n    \\path[->, thick, red] (U) edge (Y);\n\n    % Annotation\n    \\node[red, align=center] at (U.north) [above=0.2cm] {Unmeasured!};\n\\end{tikzpicture}\n```\n\nThe problem of unmeasured confounding. The backdoor path $A \\leftarrow U \\rightarrow Y$ is open, but we cannot close it by conditioning because $U$ is unobserved.\n\nIn this situation, the association between $A$ and $Y$ is a biased mix of the true causal effect and the spurious correlation induced by $U$.\n\n### The Instrumental Variable Solution\n\nAn instrumental variable, $Z$, is a variable that breaks this deadlock by introducing a source of \"clean\" or \"exogenous\" variation into the treatment. It acts as a handle on the system, allowing us to see how the outcome responds to changes in the treatment that are unrelated to the unmeasured confounder $U$.\n\nFor a variable $Z$ to be a valid instrument, it must satisfy three core assumptions:\n\n::: {.callout-important}\n\n## The Three Core IV Assumptions\n\n1. **Relevance (The \"First Stage\"):** The instrument $Z$ must have a causal effect on the treatment $A$. ($Z \\rightarrow A$).\n\t  - *In plain English:* The instrument has to actually influence the treatment decision. If it doesn't, it's useless. This is a testable assumption.\n2. **Exclusion Restriction:** The instrument $Z$ affects the outcome $Y$ *only through* its effect on the treatment $A$. There is no direct arrow from $Z$ to $Y$.\n\t  - *In plain English:* The instrument itself doesn't cause the outcome. Any association between the instrument and the outcome must be fully mediated by the treatment. This is an untestable assumption that relies on subject matter knowledge.\n3. **Exchangeability (or Independence):** The instrument $Z$ does not share any common causes with the outcome $Y$. In other words, there is no unmeasured confounding of the $Z-Y$ relationship.\n\t  - *In plain English:* The instrument must be \"as-if\" randomly assigned with respect to the outcome and any unmeasured factors $U$ that affect the outcome. This is also an untestable assumption.\n:::\n\nThe causal structure of a valid IV is shown below.\n\n```tikz\n\\begin{tikzpicture}[node distance=2cm and 2.5cm, main/.style={draw, circle, minimum size=1cm}]\n    % Nodes\n    \\node[main] (Z) {$Z$};\n    \\node[main] (A) [right of=Z] {$A$};\n    \\node[main] (Y) [right of=A] {$Y$};\n    \\node[main, dashed] (U) [above of=A] {$U$};\n\n    % Paths\n    \\path[->, thick] (Z) edge node[above] {1. Relevance} (A);\n    \\path[->, thick, blue] (A) edge node[above] {Causal Path} (Y);\n    \\path[->, thick, red] (U) edge (A);\n    \\path[->, thick, red] (U) edge (Y);\n\n    % Annotation for assumptions\n    \\node[text width=4cm, align=center] at (Z.west) [left=0.5cm] {3. Exchangeability: No arrow from $U$ to $Z$.};\n    \\node[text width=4cm, align=center] at (Z.south) [below=1.5cm] {2. Exclusion Restriction: No direct arrow from $Z$ to $Y$.};\n\\end{tikzpicture}\n```\n\nThe DAG for a valid instrumental variable, $Z$. $Z$ allows us to estimate the $A \\rightarrow Y$ effect despite the confounding from $U$.\n\n### The IV Estimator: The Wald Estimator\n\nThe magic of IV lies in a simple ratio. The IV estimate of the causal effect is the effect of the instrument on the outcome (the **reduced form**) divided by the effect of the instrument on the treatment (the **first stage**). This is known as the **Wald estimator**.\n\n$$\n\\hat{\\beta}_{IV} = \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[A|Z=1] - E[A|Z=0]} = \\frac{\\text{Reduced Form}}{\\text{First Stage}}\n$$\n\n**Rationale:** The numerator captures the total change in $Y$ associated with the instrument. Since the instrument is assumed to only affect $Y$ through $A$, this change must be due to the instrument's effect on $A$. The denominator tells us exactly how much the instrument changed $A$. By dividing the two, we are essentially calculating the change in $Y$ *per unit of change in A* that was induced by the instrument. This isolates the causal effect.\n\n::: {.callout-tip icon='false'}\n## 🧠 Insight\nThe IV estimator can be thought of as a \"natural experiment\" where the instrument randomly nudges some individuals into treatment. By comparing outcomes between those nudged into treatment and those not, we can infer the causal effect of the treatment itself.\n:::\n\n### The IV Estimand: Local Average Treatment Effect (LATE)\n\nA critical nuance is that the IV estimator does not, in general, recover the Average Treatment Effect (ATE) for the whole population. Instead, it recovers the **Local Average Treatment Effect (LATE)**.\n\nTo understand this, we divide the population into four \"principal strata\" based on how they would react to the instrument:\n\n- **Compliers:** Individuals who would take the treatment if encouraged by the instrument ($Z=1$) but not otherwise ($Z=0$). These are the people whose behavior is changed by the instrument.\n- **Always-Takers:** Individuals who take the treatment regardless of the instrument's value.\n- **Never-Takers:** Individuals who do not take the treatment regardless of the instrument's value.\n- **Defiers:** Individuals who do the opposite of what the instrument suggests (e.g., refuse treatment only when encouraged). This group is typically assumed not to exist (the **monotonicity** assumption).\n\nThe IV estimator isolates the causal effect **only for the group of compliers**.\n\n::: {.callout-note}\n### LATE vs. ATE\n\n- **ATE** = $E[Y^1 - Y^0]$ (Average effect for everyone)\n- **LATE** = $E[Y^1 - Y^0 | \\text{person is a complier}]$ (Average effect for compliers only)\n:::\n\nLATE equals ATE only under the strong assumption of **homogeneous treatment effects** (the effect is the same for everyone) or if the compliers are perfectly representative of the entire population.\n\n## Intuitive Clarifications of Challenging Ideas\n\n### Analogy: The Encouragement Design\n\nImagine you want to know the effect of attending a tutoring session ($A$) on exam scores ($Y$). You know that unmeasured student motivation ($U$) is a huge confounder—motivated students are more likely to attend tutoring and also get better grades.\n\nYou can't run a full RCT, but you can run an **encouragement design**. You randomly send a personalized encouragement email ($Z=1$) to half the students, while the other half gets no email ($Z=0$).\n\n- **Relevance:** The email should increase the probability of attending tutoring ($Z \\rightarrow A$).\n- **Exclusion Restriction:** The email itself (a few lines of text) shouldn't have a direct effect on the exam score, other than by getting students to attend the tutoring session.\n- **Exchangeability:** Since you randomized the email, the group who got the email is, on average, just as motivated as the group who didn't.\n\n#### The IV Logic in Action:\n\n1. **First Stage:** You measure how effective the encouragement was. Suppose 60% of encouraged students attended tutoring, vs. 40% of un-encouraged students. The first stage effect is $0.60 - 0.40 = 0.20$. The email increased attendance by 20 percentage points.\n2. **Reduced Form:** You compare the final exam scores. Suppose the encouraged group scored 85 on average, while the un-encouraged group scored 81. The reduced form effect is $85 - 81 = 4$ points.\n3. **The IV Estimate (LATE):** The Wald estimate is $\\frac{4}{0.20} = 20$.\n- **Interpretation:** A 20 percentage point increase in tutoring attendance (caused by the email) led to a 4-point increase in average exam scores. Therefore, the effect of tutoring *per person who was induced to attend* is 20 points. This 20-point effect is the LATE—it is the causal effect of tutoring specifically for the \"compliers,\" the 20% of students who went to tutoring *because* they got the email. We learn nothing about the effect on students who would have gone anyway (always-takers) or would have never gone (never-takers).\n\n## Simple, Hand-Calculation Numerical Example(s)\n\nLet's use a small dataset to calculate the IV estimate by hand. We want to estimate the effect of having a college degree ($A$) on annual income ($Y$, in thousands). We suspect \"ability\" ($U$) is an unmeasured confounder. Our instrument ($Z$) is whether the person grew up near a college (1) or not (0).\n\n::: {.callout-note}\n### Assumptions Check\n\n1. **Relevance:** Growing up near a college increases the likelihood of getting a degree.\n2. **Exclusion Restriction:** Growing up near a college does not directly affect income, except through its effect on getting a degree.\n3. **Exchangeability:** Growing up near a college is independent of unmeasured ability (plausible if college locations are random with respect to family background).\n:::\n\n**Observed Data (10 people):**\n\n| Person | Near College (Z) | Has Degree (A) | Income (Y) |\n|:------:|:----------------:|:--------------:|:----------:|\n| 1      | 1                | 1              | 90         |\n| 2      | 1                | 1              | 80         |\n| 3      | 1                | 1              | 70         |\n| 4      | 1                | 0              | 50         |\n| 5      | 1                | 0              | 40         |\n| 6      | 0                | 1              | 85         |\n| 7      | 0                | 0              | 45         |\n| 8      | 0                | 0              | 35         |\n| 9      | 0                | 0              | 30         |\n| 10     | 0                | 0              | 25         |\n\n**Step 1: Calculate the First Stage (Effect of Z on A)**\n\n- **Group Z=1 (Near College):** 5 people. 3 have degrees. Mean of A = $3/5 = 0.6$.\n- **Group Z=0 (Far from College):** 5 people. 1 has a degree. Mean of A = $1/5 = 0.2$.\n- **First Stage** = $\\E{A|Z=1} - \\E{A|Z=0} = 0.6 - 0.2 = 0.4$.\n- *Interpretation:* Growing up near a college increases the probability of getting a degree by 40 percentage points.\n\n**Step 2: Calculate the Reduced Form (Effect of Z on Y)**\n\n- **Group Z=1 (Near College):** Incomes are {90, 80, 70, 50, 40}. Mean of Y = $330/5 = 66$.\n- **Group Z=0 (Far from College):** Incomes are {85, 45, 35, 30, 25}. Mean of Y = $220/5 = 44$.\n- **Reduced Form** = $\\E{Y|Z=1} - \\E{Y|Z=0} = 66 - 44 = 22$.\n- *Interpretation:* Growing up near a college is associated with a $22k increase in average income.\n\n**Step 3: Calculate the IV Estimate (LATE)**\n\n- **IV Estimate** = $\\frac{\\text{Reduced Form}}{\\text{First Stage}} = \\frac{22}{0.4} = 55$.\n\n**Final Interpretation:** Our estimate for the causal effect of obtaining a college degree is a **$55,000** increase in annual income. This effect applies specifically to the \"compliers\"—the subpopulation of individuals who are induced to get a degree because they live near a college.\n\n## R Code Examples & Interpretation\n\nLet's simulate data where there is unmeasured confounding and use `ivreg` to recover the true causal effect.\n\n### Step 1: Simulate Confounded Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 2000\n# Z is a Random Instrument (e.g., Encouragement email)\nZ <- rbinom(n, 1, 0.5)\n# U is an Unmeasured Confounder (e.g., motivation)\nU <- rnorm(n, 0, 1)\n# A (treatment) is Caused by Z and U\nA <- rbinom(n, 1, plogis(0.5 * Z + 1.2 * U))\n# Y (outcome) is Caused by A and U. True Effect of A is 10.\nY <- 50 + 10 * A + 8 * U + rnorm(n, 0, 5)\n\niv_df <- tibble(Y, A, Z, U)\n```\n:::\n\n\n### Step 2: Compare OLS (Biased) and IV (Unbiased)\n\nWe will use Two-Stage Least Squares (2SLS), which is what the `ivreg` function implements.\n\n- **Stage 1:** Regress the treatment `A` on the instrument `Z` to get the predicted treatment, $\\hat{A}$.\n- **Stage 2:** Regress the outcome `Y` on the predicted treatment $\\hat{A}$.\n\n\n::: {.cell tbl-cap='Comparison of Biased OLS and 2SLS IV Estimates'}\n\n```{.r .cell-code}\n# The Naive, Biased OLS Model\nols_model <- lm(Y ~ A, data = iv_df)\n\n# The Correct IV Model Using Ivreg\n# The Syntax `Y ~ A | Z` Means: Model Y as a Function of A, where A is Instrumented by Z.\niv_model <- ivreg(Y ~ A | Z, data = iv_df)\n\n# Compare the Models Using Stargazer\nstargazer(\n  ols_model,\n  iv_model,\n  type = \"text\",\n  column.labels = c(\"OLS (Biased)\", \"IV (2SLS)\"),\n  dep.var.labels.include = FALSE,\n  covariate.labels = \"Treatment (A)\",\n  omit.stat = c(\"rsq\", \"adj.rsq\", \"f\", \"ser\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n==========================================\n                  Dependent variable:     \n              ----------------------------\n                   OLS       instrumental \n                               variable   \n               OLS (Biased)    IV (2SLS)  \n                   (1)            (2)     \n------------------------------------------\nTreatment (A)   17.843***       9.308**   \n                 (0.389)        (3.901)   \n                                          \nConstant        45.883***      50.467***  \n                 (0.285)        (2.106)   \n                                          \n------------------------------------------\nObservations      2,000          2,000    \n==========================================\nNote:          *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\n**Interpretation:**\n\n- **OLS (Biased) Result:** The OLS model estimates the effect of `A` to be 17.843. This is severely biased upwards from the true effect of 10. This is because the unmeasured confounder `U` (motivation) is positively associated with both treatment `A` and outcome `Y`, creating positive confounding bias.\n- **IV (2SLS) Result:** The `ivreg` model estimates the effect of `A` to be 9.308, which is close to our true simulated effect of 10. By using only the variation in `A` that is driven by the random instrument `Z`, the model successfully filtered out the confounding effect of `U` and recovered the true causal effect.\n\n### Step 3: Checking the First Stage\n\nA crucial diagnostic is to check the strength of the instrument. A weak instrument (one that is only weakly correlated with the treatment) can lead to very noisy and biased IV estimates.\n\n\n::: {.cell tbl-cap='First-Stage Regression Results'}\n\n```{.r .cell-code}\n# Manually Run the First-stage Regression\nfirst_stage_model <- lm(A ~ Z, data = iv_df)\n# The F-statistic from This Model is Our Key Diagnostic.\nsummary(first_stage_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = A ~ Z, data = iv_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.5929 -0.4822  0.4071  0.4071  0.5178 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.48218    0.01560  30.908  < 2e-16 ***\nZ            0.11075    0.02217   4.995  6.4e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4958 on 1998 degrees of freedom\nMultiple R-squared:  0.01233,\tAdjusted R-squared:  0.01184 \nF-statistic: 24.95 on 1 and 1998 DF,  p-value: 6.404e-07\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The coefficient on `Z` is 0.111, which is our first stage effect. The F-statistic for the model is 24.947. A common rule of thumb is that an **F-statistic > 10** indicates a sufficiently strong instrument. Since our F-statistic is well above 10, we can be confident that our instrument is not weak.\n\n## Hands-On R Lab\n\n### Lab: The Draft Lottery and Earnings\n\n**Purpose:** This lab will give you hands-on experience with a classic IV application: using the Vietnam draft lottery as an instrument to estimate the causal effect of military service on long-term earnings.\n\n**Lab Objectives:**\n\n1. State the three IV assumptions in the context of the draft lottery.\n2. Perform a first-stage regression to check the relevance of the instrument.\n3. Perform a reduced-form regression to see the instrument's effect on the outcome.\n4. Calculate the LATE by hand using the Wald estimator.\n5. Estimate the LATE using `ivreg` and compare the results.\n\n**Scenario:**\nDuring the Vietnam War, the U.S. Selective Service used a lottery based on birth dates to determine who would be drafted. This lottery number ($Z$) was essentially random. It strongly predicted serving in the military ($A$), but it is assumed to have no other direct effect on a man's future earnings ($Y$), except through military service. This makes it a powerful instrument to overcome the unmeasured confounding (e.g., ability, patriotism) that affects both volunteering for the military and future earnings. We will use a classic dataset from @cunningham2021causal.\n\n#### Task 1: Load Data and State Assumptions\n\nFirst, let's load the data. `draft` is our instrument (1 if lottery number made them eligible), `veteran` is our treatment, and `log_weekly_wage` is our outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraft_df <- read_csv(\n  \"[https://raw.githubusercontent.com/scunning1975/mixtape/master/lottery.csv](https://raw.githubusercontent.com/scunning1975/mixtape/master/lottery.csv)\"\n)\n```\n:::\n\n\n**Instructions:**\nIn your own words, state the three IV assumptions for this analysis.\n\n1. **Relevance:** ...\n2. **Exclusion Restriction:** ...\n3. **Exchangeability:** ...\n\n##### Solution to Task\n\n1. **Relevance:** A man's draft eligibility status must be a strong predictor of whether he actually served in the military.\n2. **Exclusion Restriction:** Draft eligibility must affect a man's later-life earnings *only through* its effect on his military service. There can be no direct effect (e.g., the psychological trauma of having a low lottery number).\n3. **Exchangeability:** Draft eligibility status must be independent of any unmeasured characteristics (like innate ability or family background) that could also affect earnings. Since it was a lottery, this is a very plausible assumption.\n\n#### Task 2: The First Stage and Reduced Form\n\n**Instructions:**\n\n1. Run a regression for the **First Stage**: `veteran ~ draft`. Interpret the coefficient. Is the instrument relevant? Check the F-statistic.\n2. Run a regression for the **Reduced Form**: `log_weekly_wage ~ draft`. Interpret the coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO: Fit the First-stage Model\nfirst_stage_draft <- lm(...)\ntidy(first_stage_draft)\nsummary(first_stage_draft) # To see the F-statistic\n\n# TODO: Fit the Reduced-form Model\nreduced_form_draft <- lm(...)\ntidy(reduced_form_draft)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First Stage\nfirst_stage_draft <- lm(veteran ~ draft, data = draft_df)\ntidy(first_stage_draft)\nsummary(first_stage_draft)\n\n# Reduced Form\nreduced_form_draft <- lm(log_weekly_wage ~ draft, data = draft_df)\ntidy(reduced_form_draft)\n```\n:::\n\n\n**Interpretation:**\n\n- **First Stage:** The coefficient on `draft` is \\~0.16. This means being draft-eligible increased the probability of becoming a veteran by about 16 percentage points. The F-statistic is very large (\\~94), so we have a strong instrument.\n- **Reduced Form:** The coefficient on `draft` is \\~-0.03. This means being draft-eligible was associated with a \\~3% decrease in weekly wages later in life.\n\n#### Task 3: The IV Estimate (LATE)\n\n**Instructions:**\n\n1. Using the coefficients from your two models in Task 2, calculate the Wald estimate for the LATE by hand.\n2. Use the `ivreg()` function to estimate the same effect. Verify that your hand calculation matches the `ivreg` output.\n3. Write a one-sentence interpretation of the final result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TODO: Get Coefficients from Your Previous Models\nfirst_stage_coef <- coef(first_stage_draft)[\"draft\"]\nreduced_form_coef <- coef(reduced_form_draft)[\"draft\"]\n\n# TODO: Calculate the Wald Estimate\nwald_estimate <- ...\nprint(wald_estimate)\n\n# TODO: Use Ivreg to Confirm\niv_model_draft <- ivreg(...)\ntidy(iv_model_draft)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_stage_coef <- coef(first_stage_draft)[\"draft\"]\nreduced_form_coef <- coef(reduced_form_draft)[\"draft\"]\n\n# Wald Estimate by Hand\nwald_estimate <- reduced_form_coef / first_stage_coef\nprint(wald_estimate)\n\n# Using Ivreg\niv_model_draft <- ivreg(log_weekly_wage ~ veteran | draft, data = draft_df)\ntidy(iv_model_draft)\n```\n:::\n\n\n**Interpretation:** For men whose military service was determined by the draft lottery (the compliers), serving in the military caused an approximate 18.7% reduction in their weekly wages later in life.\n\n## Common Pitfalls & Checks\n\n::: {.callout-warning}\n### The Untestable Assumptions\nRemember that two of the three core IV assumptions—Exclusion Restriction and Exchangeability—are not statistically testable. Their plausibility rests entirely on institutional knowledge and careful causal reasoning. A statistically strong instrument that violates these assumptions will produce a precise but incorrect answer. Always spend more time defending your instrument's validity with words than with numbers.\n:::\n\n::: {.callout-important}\n### A Weak Instrument is a Useless Instrument\nA weak instrument (First Stage F-statistic < 10) is a major problem. Weak instruments can lead to IV estimates that are even more biased than naive OLS, and their confidence intervals will be enormous. If your instrument is weak, the analysis is generally not credible. You must find a stronger source of exogenous variation.\n:::\n\n## Advanced Teaching Activities & Interactivity\n\n1. **\"Find the Flaw\" IV Design Critique:**\n\n- **Activity:** I will present three potential IV study designs. Each will have a subtle but fatal flaw in one of the three core assumptions.\n- *Example 1 (Relevance Flaw):* Using a person's favorite color as an instrument for buying a blue car.\n- *Example 2 (Exclusion Flaw):* Using a doctor's preference for a new drug as an instrument, when that doctor also provides better counseling, which directly affects the outcome.\n- *Example 3 (Exchangeability Flaw):* Using a patient's insurance status as an instrument for getting a treatment, when insurance is also a proxy for socioeconomic status (an unmeasured confounder).\n- **Task:** In groups, identify which assumption is violated for each design and explain why.\n\n2. **Think-Pair-Share: Who are the Compliers?**\n\n- **Think:** \"Consider the classic IV study using distance to a hospital as an instrument for receiving a certain surgery. Who are the 'compliers' in this setting? Who are the 'always-takers' and 'never-takers'? Is the LATE for these compliers likely to be higher or lower than the ATE for the whole population?\"\n- **Pair:** Discuss with a neighbor.\n- **Share:** We will discuss how compliers in this context are likely rural patients for whom distance is a major barrier. Always-takers might be wealthy urban patients who will travel anywhere, and never-takers might be those with a philosophical objection to the surgery. The LATE for the rural compliers might be very different from the ATE.\n\n## Appendix: Advanced Theory & Derivations\n\n### Formal Derivation of the Wald Estimator as LATE\n\nHere we show that under the IV assumptions plus monotonicity, the Wald estimator identifies the LATE.\n\nLet $Z$ be a binary instrument and $A$ a binary treatment.\n\n$$\n\\text{Wald} = \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[A|Z=1] - E[A|Z=0]}\n$$\n\n**The Numerator (Reduced Form):**\n\n$E[Y|Z=1] - E[Y|Z=0]$ can be written in terms of potential outcomes. By exchangeability ($Y^z \\indep Z$), this is equal to $E[Y^{z=1} - Y^{z=0}]$. By consistency and the exclusion restriction (Z only affects Y through A), this becomes $E[Y^{A^{z=1}} - Y^{A^{z=0}}]$.\nExpanding over the principal strata (C=Complier, AT=Always-Taker, NT=Never-Taker):\n$= E[Y^1 - Y^0 | C]P(C) + E[Y^1 - Y^1 | AT]P(AT) + E[Y^0 - Y^0 | NT]P(NT)$\n$= E[Y^1 - Y^0 | C]P(C)$\n$= \\text{LATE} \\times P(C)$\n\n**The Denominator (First Stage):**\n$E[A|Z=1] - E[A|Z=0]$ can also be expanded. By exchangeability ($A^z \\indep Z$), this is $E[A^{z=1} - A^{z=0}]$.\nExpanding over strata:\n$= E[1 - 0 | C]P(C) + E[1 - 1 | AT]P(AT) + E[0 - 0 | NT]P(NT)$\n$= 1 \\times P(C) + 0 + 0 = P(C)$\n\n**Putting it together:**\n\n$$\n\\text{Wald} = \\frac{\\text{LATE} \\times P(C)}{P(C)} = \\text{LATE}\n$$\n\nThis proves that the simple ratio of observable differences identifies the average causal effect specifically for the complier population.\n\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}